* 什么是汉诗
** 《怀风藻》前的诗意识
日本汉诗史的书写，首要的工作就在于厘清“诗”这一概念在日本的生成和流变。那么，我们可以从哪些材料中对这一过程进行梳理？从现有的日本汉诗史中可以发现，《诗经》和其阐释文本，以及日本现存最古的汉诗总集《怀风藻》是研究者最为关注的。尤其是《怀风藻》，因为其贵重的文献价值，其在日本汉诗史中的地位，被认为如同《诗经》在中国诗歌史中的位置（日本汉诗发展史，141）。围绕《怀风藻》成书背景及艺术特色的分析，学界已经有许多论文。而本段意在说明《怀风藻》成书之前，日本列岛已经有了“诗”的意识。而这种“诗”意识，在不可避免地受到先秦至魏晋中国诗学传统影响的同时，更出现在以记纪歌谣为代表的日本古代歌谣中。
**** 中国的“诗”？
日本最早没有自己的文字。因而，日本首次接触“诗”，是通过中国文献的输入进行的。这些文献中，有《诗经》这样直接记载“诗”的，也有《论语》这类包含儒家论诗思想的著作。因此，考察“诗”在日本的发轫，必须从中国诗学传统对“诗”的认识出发。

中国的诗，其形态经历了从口头到文字记录的过程。陆侃如《中国诗史》对中国早期诗的形态进行考辩，认为卜辞对乐舞的记载呈现出中国诗的原始形态（中国诗史，5）。诗舞乐结合便成为中国早期诗的一个核心特征。另外，从陆侃如等人对殷商金文和周代金文协韵与否的比较中，也可以发现，“韵”这一诗歌重要形式特征的出现是经历了一定的过程的。那些用文字记录下来的，协韵且形式较为整一的内容，呈现出中国早期诗的样貌。

而进入到文字时代，中国诗的语言就逐渐与日常口语分离。吉川幸次郎概括中国诗的语言特点时指出：“文学的语言不是作为日常语言的口语,而在原则上被要求为具有一定规格的特殊语言”。而这种“特殊语言”的核心在于韵律。《诗经》中就可以看到押韵的特征。此外，随着诗歌体式的成熟，形式的整一，乃至平仄等等，都成为中国古诗语言特征中不可分离的部分。

以上是对中国早期诗特征的简单描述。那么，人们对“诗”的认识又经历了怎样的过程？考虑到本部分是对“诗”在日本的发轫，而日本对《诗经》、《论语》等文本的接受不早于魏晋，因此，这里仅梳理魏晋及之前中国诗学传统对于“诗”的认识。

描述魏晋及以前的时代中国诗学对“诗”的认识，是无法离开尚书》、《论语》、《礼记》以及《毛诗序》几个文本的。“诗言志，歌永言，声依永，律和声。八音克谐，无相夺伦，神人以和。”（《尚书》）中可以第一次看到诗言志这一重要命题。而《论语》中，“思无邪”、“兴观群怨”等命题，则与《礼记》“温柔敦厚，《诗》教也”、“其为人也：温柔敦厚而不愚，则深于《诗》者也”之“温柔敦厚”一起，成为经学之“诗”的核心理念。至于《毛诗序》，其重要性在于，它将“情”的因素引入了“诗”的本质：“诗者, 志之所之也, 在心为志, 发言为诗。情动于中而形于言, 言之不足故嗟叹之, 嗟叹之不足故咏歌之, 咏歌之不足, 不知手之舞之, 足之蹈之也。”

另外，中国古代目录学著作对“诗”的分类，也应该被关注到。魏晋及以前的目录学著作中，经学之“诗”和文学之“诗”是泾渭分明的。《七略》中，《诗经》归于“六艺略”，而屈原、陆贾等人的赋被单独归于“诗赋略”（王重民：《中国目录学史论丛》，页24-25。）。《汉书·艺文志》除了“诗六家，四百一十六卷”外，还有“歌诗二十八家，三百一十四篇。凡诗赋百六家，千三百一十八篇。”

可以认为，最早影响日本列岛的中国诗学对“诗”的理解，并非是一种相对独立和统一的认识。而这也反映出诗歌史发展初期诗意识的混沌。

<2020-12-08 Tue>
**** 日本古代歌谣中的“诗”意识？

在叙述中国早期诗的形态及相关认识后，我们也要认识到，同中国诗的形态发展过程类似的，日本民族文学中的歌谣也经历了从口头到书面文体的转化。这些上古时期的原始歌谣是中国诗歌传统系统进入之前，日本所固有的。那么，这些原始歌谣的特点是什么，又和“诗”在日本的发轫有什么关系呢？

从特点上来说，这些原始歌谣同中国诗的原始形态有着相类之处。它们都和舞蹈、音乐密切关联。而日本原始歌谣的特殊性在于，它的形成和发展是日本原始神道宗教生活的一部分。而原始神道的咒语等，又由“言灵”（ことだま）思想所统摄。这种对语言中灵力的信仰对日本古代民族文学的影响很大，从上古贯穿到江户时期的国学运动（川村湊 『言霊と他界』 講談社学術文庫 2002年，15）。因此可以认为，这种原始神道信仰是日本原始歌谣核心的精神内核。至于《古事记》、《日本书纪》中记载的歌谣，则是日本进入到文字时代以后留下的作品了。而这些作品也继承了原始歌谣的信仰因素（日本诗歌史，14）。

那么，以上所述日本古代歌谣的特点和“诗”在日本的发轫有何关系？记纪歌谣一定程度上继承了中国早期诗、早期韵文的仪礼功能，即构建皇室和国家的权威话语。上述《古事记》和《日本书纪》最早记载日本古代歌谣，数量也最可观（日本诗歌史，7）。而这两部作品都是用汉文写成的官史，是日本系统接受中国思想和政治制度的产物。其中所记载的天皇的御谣，出现在战争演讲和重要的祭祀场合，成为日本古代历史建构的重要组成。如《日本书纪》卷三记载了崇神天皇八年冬十二月，天皇和大夫祭大神，其间君臣对歌的场景（日本书纪，76）。

综上，早期律令制国家史书中的这些歌谣能够反映当时日本列岛的“诗”意识。而在记纪成书的近一个世纪之后，日本现存最古汉诗集《怀风藻》才编撰完成。现有的日本汉诗史在叙述日本汉诗的发轫时，往往忽视《怀风藻》成书之前的文献中已经存在的“诗”意识。

而除了记纪歌谣，日本在二十世纪九十年代后半叶的考古成果也能够观察到《怀风藻》成书前列岛居民对诗的运用。奈良县飞鸟寺附近的飞鸟池工房遗址就是一例。这处遗址被认为是日本古代最大的工房，在其中出土了写有如下文字的木简：“白马鸣向山 欲其上草食 女人向男咲 相游其下也”（奈良文化財研究所木簡データベース。ウエブサイトhttp://www.nabunken.jp/Open/mokkan/mokkan1.html。 木 簡 番 号 248．）这段文字的原型被认为是《千字文》“鳴鳳在樹，白駒食場，化被草木，頼及万方”（新川登亀男｢｢天皇｣木簡を考える｣『月刊しにか』一二七､二〇〇〇年）此外，尽管无法看到这段文字的押韵，但其句式规整，已经接近诗的语言。

** 什么是“诗”：以日本汉诗人对《诗经》的认识为中心
《诗经》及其阐释文本作为首批输入到日本的汉学文献，对日本诗学的形成和发展产生重大的影响。因此，日本汉诗人对《诗经》的认识应当作为梳理日本汉诗史中“诗”意识的中心问题。实际上，围绕日本诗经学，学界已经有许多成果。这些研究对《诗经》在日本的流布和日本学人对《诗经》的接受、阐释史作了细致深入的研究。而本部分并非是对《诗经》研究的研究，因此无意重复这些论述。相对地，这一部分意在考察《诗经》在日本汉诗经典化过程中起到的诗学意义，即通过透视日本汉诗人论诗文本中对《诗经》及相关话语的使用方式，揭示日本汉诗人对“诗”的认识。
*** 《诗经》
**** 《诗经》是诗的审美标准
《诗经》关乎日本汉诗人对诗的评价标准。而其中最突出的两项：风雅之“真”，以及《诗经》中情性与韵律的和谐。

小笠原优轩以《诗经》之“真”反对当时诗坛模拟唐宋的风气：“擬唐仿宋之詩亡之日，即風雅之真詩興之日也。”（3879）

何谓“真诗”？可以看到，作者凭借《诗经》风雅之“真”反拨唐宋模拟之风的论述，与晚明袁宏道的诗学思想是相类的。回到中国诗学传统，“真诗”这一个诗学命题在明代提出后，主要经历了三次转向。第一是李梦阳所谓“真诗在民间”，凭借对《诗经》中的《风》诗，强调了民间诗歌具有真情，方为真诗。第二是王士贞所谓“盖有真我而后有真诗”（《弇州续稿》巻五十一·《邹黄州鹪鹩集序》），将蕴含了诗人主体性的“真我”作为“真诗”的前提。第三是袁宏道“犹是无闻无识真人所作，故多真声，不效颦于汉魏，不学步于盛唐……大概情至之语，自能感人，是谓真诗，可传也。”（《袁中郎全集》卷十），通过与“真人”、“真声”等命题组合，扩大了“真诗”的内涵。

综上可以认为，小笠原优轩将《诗经》视作“真诗”，是在上述“真诗”脉络之中的。而他的诗学观点，也反映出江户汉诗中后期反复古、扬性灵的诗风。在《优轩诗话》中，他还概括了《诗经》的本质，和诗人所应追求的最高标准：“三百篇以思無邪爲主，詩人之興趣止於此而已。”（3871）评述屈原、宋玉、陶渊明等人的艺术风格，小笠原将“自然之真趣”视作“思无邪”的核心。而在此之前，祇園南海也表达过类似的观点，认为《诗经》作为中国诗歌发展史的源头，其造化之妙，非后世之诗人所能企及。而这种极高的地位，是因为其“上世之口氣，真情流出”（5281）。从这些论述中可以看到从江户汉诗诗学思想中以“真诗”为核心，兼谈“真情”、“真趣”的脉络。

同时，在这一“真诗”的诗学命题中，也能反映出江户时期堀川、萱园两派古学学者《诗经》阐释中关注人情的面相。尽管从日本汉诗诗学传统的发展看，反复古、扬性灵的诗风主要针对萱园派（近世东亚汉诗流变，385），但如果考虑到其《诗经》阐释的特点，就能够发现萱园派诗人菅茶山等人的观念转向具有其内在逻辑。

除了理论上的倡导，小笠原优轩本人的创作实践也努力贴近《诗经》的风格。下面例举两首：

《王丹麓河之渚 二章》：


“河之渚，梅以爲春。我廬於斯，我室於斯。乘舟而綸，游泳無時。河之渚，葭以爲秋。我竹既藝，我魚既餒，卒歲優遊，樂其生遂。”（3879）

这首诗化用了蒹葭的意象，体现出作者悠游其乐的心态。


《陟阻，一谷懷古也。二章皆賦，章六句 成美》：

“陟彼阻兮,松柏苍苍，平氏之亡，三军于没，北风飙飙，波涛蕩兮。铁拐之峻，王宫焕兮，維昔之盛，今其邈兮。月出慘矣，慨其嘆矣。”（3883）

这首诗抒发了怀古的心情，其中融入了对源平之战的感慨，以及重获安定后，与战时气氛的对比所生出的叹息。




森槐南《参订古诗平仄论》云：“殊不知《詩三百篇》發諸情性，諧於律吕，降而爲《離騷》，爲樂府，皆莫不以聲調鏗鏘爲美。”（5063）在他看来，以《诗经》-《离骚》-乐府为脉络的中国诗歌传统有着共同的美学特点，即声调铿锵。

何谓“铿锵”？森槐南此书是对王士稹《古诗平仄论》的校订和评注，因此，声调之“铿锵”被用以针对一些日本汉诗人作古诗音节混乱而不自知的现象。而这些汉诗人在森槐南看来，是受到了袁枚的影响：“概皆借口于袁才子，谓古诗‘到恰好处，自成音节’”。

回到《随园诗话》，则能发现袁枚此番评论是关于赵执信《声调谱》的。而赵执信此书显然是受到王士稹古诗声调论述的影响。《四库全书提要》：“执信尝问声调于王士稹，士稹靳不肯言，执信乃发唐人诸集，排比钩稽，竟得其法。”对王士祯，袁枚则评价其七言古诗“如杞國伯姬，不敢挪移半步”。森槐南对袁枚的攻击持反对态度，认为其不过“佛家骂祖手段，语相戾而理实相该”。

然而，细观《随园诗话》后文的论述，则能发现森槐南对袁枚的评议也是基于误解。具体来说，第一，袁枚认为诗经之风雅颂一直到乐府“各有聲調，無譜可填”；第二，若填谱作诗，则“四始、六義之風掃地矣”。《随园诗话·四/54》这两处都说明袁枚并非反对古诗声调。相反，他重视《诗经》以来各种诗体自身的声调特点，更将《诗经》作为自成音节的典范。

可以认为，《诗经》在两人诗说中的功能，都是一种诗的审美标准。只是森槐南所谓“铿锵”，除了强调其声调之规整和谐，更突出《诗经》声调与情性的融合。通过对《诗经》这一特点的强调，“情意-义理-音节”三者和谐统一的论诗标准也跃然纸上。


**** 《诗经》是诗的最高典范
:LOGBOOK:
CLOCK: [2020-12-09 Wed 10:07]--[2020-12-09 Wed 10:12] =>  0:05
:END:
《诗经》被认为是诗的审美标准，这意味着符合《诗经》之“真-情-韵”三位一体的诗才能进入日本汉诗人的评价视野。在此基础上，可以看到《诗经》转变成了诗的最高典范。这种典范地位决定了日本汉诗经典化的路径。

《侗庵非诗话》的作者古贺侗庵（1788-1847）尤其强调《诗经》于入门者的典范作用。他赞同朱熹“《三百篇》性情之本”的论述，又沿承朱熹“读《诗》正在于吟咏讽诵，观其委曲折旋之意”的读诗方法，认为师法古人之诗，吟咏讽诵，是学诗的不二法门。

那么，在古人之诗中，《诗经》的地位又有何特殊？作者提到：“詩至《三百篇》超化人神,非人力可及，盡矣至矣。自非子貢、子夏之徒,未可與言。”（2160）可见，其典范地位在于其出神入化，尽善尽美。而正因为《诗经》的地位崇高，《诗经》的读者也应该具有一定的学识。古贺侗庵认为，只有孔门四科十哲中的子贡、子夏那样好古敏求的人才能与之谈论《诗经》。

作者将《诗经》和其他诗加以区分，体现了日本汉诗创作大众化的背景下的汉诗经典化意识。《侗庵非诗话》是一部批评本国诗话的著作。诗话的大量出版，以及职业诗人的出现被认为是江户时代日本汉诗人诗学自觉的体现。然而，作者却以之为非。在他看来，要作好诗，“故必作大儒，先大君子,然後可以有真好詩矣。甘自爲一詩人，則其詩必不足觀也。”（2070）在儒者、君子、诗人的等级序列中，诗人的地位是最低的。而通过对《诗经》典范地位的树立，作者试图将这些以诗为业，却不在心性上修己问学的诗人及其作品排除在日本汉诗的经典脉络之外。


**** 《诗经》是诗史、诗体之源
《诗经》的崇高地位亦影响到日本汉诗人对宏观诗史，具体来说，是中国诗歌史的认识。《诗经》既然被视作是诗史、诗体之源，那么诗史对诗人、诗作的经典化的过程中，《诗经》也应该是一个无法绕开的标准。所以，在日本汉诗人对《诗经》诗史之源的肯定中，我们可以看到他们以中国诗歌传统为参照系，对诗的本质进行探讨。中国诗歌史如何从《诗经》中展开，又遵循着怎样的规律？对这些问题的反思可以回到本国汉诗的发展中来：日本汉诗人应该接受怎样的传统？日本汉诗自身的传统又是如何？
 
***** 诗与乐
日本汉诗人注意到《诗经》与后世诗歌之间的区别，在于能否入乐。而《诗经》入乐又决定了后世诗得以在语言形式上继承《诗经》押韵的特征。可以说，以《诗经》为基础阐述诗乐关系，反映出日本汉诗人对诗的普遍特征，即音乐性的思考。

小野泉藏从风雅正变的角度说明了诗、乐分离的原因：“以《三百篇》言之，風雅之正者皆可被之管絃,而其變者皆徒詩也。但雖其被於管絃者，亦可以徒唱歌，此所謂行而不相悖者也。至於漢,則詩皆徒詩，而樂府則特製焉，其别判然不待明辨。”（《社友诗律论》，1707）这里可以看到，《诗经》中正风正雅即使与音乐分离，也可以歌唱。这种音乐性是后世诗乐分离的基础。

关于《诗经》自身的音乐性，《诗学逢原》从诗的分类着手，认为《诗经》原是六经之一，是圣人所写的音乐，根据古代的音乐进行演唱，用来教化百姓的（日本诗话丛书，2，2）。《唐诗平侧考》也指出，从入乐的《诗经》开始，诗的核心特征就是韵。（日本诗话丛书，2，125）《诗格集成》则引明代薛冈《天爵堂笔余》：“三百篇，诗之祖也”，及胡应麟：“三百篇，荐郊庙，被管弦，诗即乐府，乐府即诗也”（日本诗话丛书，3，381），以说明《诗经》的音乐性影响了日本汉诗人对诗之核心特征的理解。

而从《诗经》考察诗的音乐特征出发，日本汉诗人继而发现《尚书》中的一些韵文也具有诗的特性。《诗辙》就指出，《尚书·虞书》记载的“股肱喜哉！元首起哉！百工熙哉！”可以视作是诗的起源之一（日本诗话丛书，6，58）。这意味着，基于《诗经》，日本汉诗人对诗的音乐性有了更深入的认识，并在此基础上开始关注《诗经》以外的经典中的存在的诗意识。




***** 诗与情
在认识以《诗经》为基础的诗的音乐性的同时，日本汉诗人也注意到后世诗人对诗的声律的过分雕琢，会有害于诗的精神内核——性情。但强调性情并不意味着对诗人个性的无限张扬。相对地，凭借《诗经》议论诗之性情的诗人，都注意到诗的性情或受制于与音调节奏的配合，或服从于对性情特质的具体规定。

小野泉藏曾批驳后世论诗者用声律肢解《诗经》章句的行为。他提到：“夫《三百篇》邈矣，秦漢而降，吐露性情而音調節奏自然動人者爲詩，詩而不能動人則不如不作之爲勝也……诗出性情者，自然也。聲律者，人作也。”（1693）在他看来，《诗经》对诗的本质的规定不仅出于其音乐性，还在于其本是诗人性情之吐露。性情与诗的音调节奏的和谐使得诗具备感动人心的审美效果。从小野泉藏对《诗经》性情与声调关系的议论中可以看到，诗人以诗为载体对性情的发挥并不是没有限度的。

赤泽一堂《诗律》则认为，《诗经》作为诗体、诗史之源，其价值更在于性情。他发挥了儒家诗学重要命题之一的“诗言志”，对诗人、诗作提出了自己的标准：“詩雖有諸體不同，皆原于周，所以尊矣。……周詩三百，各有六義，曰風雅頌，是其格也。曰賦比興，是其體也。是故爲詩者，須真才實學，本性反情。詩出於實情不可止之地，哭者善哭，喜者善喜，是爲真詩。”（3582）需要注意的是，这里的“真诗”和前文“真诗”命题中的自然真趣有着本质的不同。如果说前文之“自然”是和复古模拟的诗风相对，强调的是诗人在创作中的主体意识，那么此处“哭者善哭，喜者善喜”中，具体规定了何为“哭”，何为“喜”，只有符合这一先验规定的诗性表达才能算作是“真诗”。“實情不可止之地”也说明，在赤泽一堂的“真诗”命题中，诗人的个性表达实际上是服从于这一规定的。


***** 诗与经
《诗经》是首批进入日本的儒家经典。而随着日后东亚各国的交往深入，一部分发源于中国的文教制度，如五经博士、学寮等也在日本建立。这些制度促进了日本对于《诗经》的系统研究。而日本对《诗经》的经学研究也由此开始，一直延绵到战后。因此可以认为，在日本汉诗经典化的过程中，日本汉诗人对《诗经》话语的运用始终是与《诗经》的经学阐释相关的。

冢田大峰从诗史发展的视角出发，展开了诗歌发轫阶段“诗”与“经”的名实之辨。他的论点在当时研究《诗经》的儒者中较为难得。在《作诗质的》中提到，“诗”的产生是一系列文体逐渐定型和发展的结果。而《诗经》是这一过程的起源：“風雅之變，爲騷爲賦，乃至稱詩。”（1441）在这里，《诗经》同骚体、赋体一同位于诗的序列中。而且，从《诗经》到骚赋，“诗”的概念是逐渐定型和发展的结果。这说明，《诗经》之风雅并不等同于诗，只能算是诗的早期形态之一。在这里，《诗经》作为后世诸种诗体的开端，作者将其诗体价值从经学阐释中独立出来。考虑到冢田大峰是通学朱子学、古学、阳明学的大儒，曾自注十三经，其经学学问在其督学的江户名古屋藩内有“大峰学”之称（三百藩家臣人名事典，新人物往来社，1988），这种对《诗经》诗体价值的强调是值得关注的。

津阪东阳则提出了相反的观点，将六经之一的《诗经》与“诗”对立，将学者与诗人对立，单纯突出其经学地位：“詩之於學者也，特其剩技耳。行有餘力，乃以學之。近時學風輕薄,舍本而趨末，以詩爲性命。六經群史一切束之高阁。”（《夜航诗话》，4，1527）津阪东阳是江户中后期的儒者，而当时日本诗坛出现了相当多的职业诗人。这些诗人和江户时代初期、中期的儒者学问与文章兼修不同，他们以诗为业，有的还靠卖诗为生。加上町人阶层的作者加入到汉诗的创作活动中，俗语、俚语入诗已然成为一种风格。儒者东梦亭曾评价说：“少年輕俊之徒，風流自喜，忘吾本分,專心詩章,以要虚譽,四書五經舍而不講。”（2857）由此可见当时诗风浮躁。在这样的背景下，津阪东阳对《诗经》的认识，可以认为是对以《诗经》为代表的雅正诗风、温柔敦厚之旨的回归。

与津阪东阳观点类似的还有小笠原優軒。同样是针对当时诗风，他批评时人苦学近代诗集，却将《诗经》四诗视作异调。对于这种异象，他号召有志之士“更讀三百篇，而洗滌一過,而後詩人之雅致渾渾流出,句法清穆，格調高潔矣。”（3875）《诗经》相对于近时诗歌，或具体来说，强调“平侧之调”的近体诗，是古诗传统的源头。《诗经》的功用也因此在于洗涤诗人被平侧之调、靡靡句法玷污的心髓，使诗人复得雅致。而这种功用与儒家诗教中对《诗经》正人心、端正教的观念是同构的。


*** 《诗经》学中的重要命题
上述论述证明，日本汉诗人以《诗经》论诗，反映出一定的经典化意识。将《诗经》作为构建诗歌传统的核心参照，体现出日本汉诗人的诗意识。而同时，除了对《诗经》本身的思考，围绕《诗经》展开的一系列重要的诗学命题，日本汉诗人也进行了阐释。这些阐释也应视作日本汉诗经典化过程中的重要依据。

古贺侗庵在批驳古今诗话时曾感慨，儒家诗学有关《诗经》重要命题，如“诗言志”、“思无邪”、“兴观群怨”、“温柔敦厚”、“不以文害辭，不以辭害志”、“以意逆志”等，“学诗之要尽乎此矣”（2058）。而这些命题中，影响最深的应是“诗言志”。通过以“诗言志”为中心的阐释，日本汉诗人钩连起儒家诗学的其他重要命题，并在此基础上提出了对诗和诗人的标准。这些标准是日本汉诗经典化的意识所在。

**** 诗言志

“诗言志”的命题在日本汉诗人看来，是与“思无邪”紧密相关的。“思无邪”规定了诗人言志的方式和诗的价值取向。《锦天山房诗话》对此二者关系的总结尤为精到：“夫詩者，言志也。志有邪正，故言有美惡。”（2947）

虎关师炼在日本第一部诗话《济北诗话》中对“诗言志”和“思无邪”进行了阐释：“夫诗者，志之所之也，性情也，雅正也。……今夫有人端居无事，忽焉思念出焉。其思念有正焉，有邪焉。君子之者，去其邪取其正，岂以其无事忽焉之思念为天，而不分邪正随之哉？……况诗人之者，元有性情之权，雅正之衡。不质于此，只任触感之兴，恐陷僻邪之坑。”（296）在这里，虎关师炼认识到诗人的个体意识在权衡性情雅正的过程中得以发挥。也就是说，诗是诗人对触物感兴进行剪裁的结果。

小笠原优轩指出，正因为诗是志之所至，思有正邪，诗人才要对诗的表达反复斟酌:“耻一言不爲戒，耻一句不自敬。”（3873）。也只有“防邪如雠，守正如城”，才能接近思无邪的境界。

以上论述中可以看到，诗人的创作应该根据儒家诗教思无邪的要求，选择合适的诗性语言进行言志，而后成诗。可以认为，这种观念尽管规定了诗的价值取向，但同时赋予了诗人一定的主体地位。

在此基础上，诗人有责任锻炼诗的语言，谨慎措辞，用善言来传达自己的心志。而这亦在儒家诗学“修辞立其诚”的传统之中。正如《诗法授幼抄》一书指出的：“蓋詩，言志也。雖然言不善則志不達，其善言达志，在慎所由矣。”林荪坡《梧窗诗话》则将炼句和措辞的慎重视作是对心之“诚”的诗学实践：“詩者，言之永也。言者，心之聲。言不可苟吐，苟吐之爲自欺者也。”“不自欺”是为“诚”。成徳隣、檜長裕亦认为，“詩者,君子之辭也，可不修乎?”

那么，如何锻炼诗的语言，以至于符合对无邪之志的言说？这里牵涉到日本汉诗人对诗人心志与诗的特殊语言形式，如用韵和声律等关系的思考。以下试呈现两种相对的观点。

小野泉藏认为，言志乃诗之本色，诗人咨嗟詠嘆,自成音響。这是自《诗经》至汉魏以来的古诗传统。此后，“梁唐以下乃稱聲律，而詩之道自此拘矣”。在他看来，格律诗的传统是对诗道的约束，遮蔽了诗的本色。那么，何者才能算作是诗的本色？答案正在于诗人的感物言志。

释教存的观点则相反。“且也情動於中而形於言，言成聲，聲成文，文乃宫商是也。然則有語言則有聲律，有聲律則有格法，是勢之所必至也。升堂入室，不得不由其門也。格法者，升堂入室之門也。”通过化用诗大序中对诗的发生结构的论述，作者构建了一条从格法入门，学成作诗的路径。和其他汉诗人强调诗人应重视学问、性情，认为雕琢声律有害于言志不同，释教存认识到，诗人的内在性情和外在的格调法度是诗发生过程中的不同环节。在这样的逻辑中，诗就是诗人生命、性情的延续，因此不能够将性情和格法割裂开来。

从以上围绕“诗言志”这一命题展开的论述中可以看到，日本汉诗人眼中的“诗言志”，其指向的是诗与诗人生命的结合。而对于诗的读者来说，这种指向的意义有二。

第一，诗可以同时体现普遍人性和诗人的个性气质。冢田大峰就认为：“詩者，所以言志。而後世之作詩雖多工設詞,非其實情,然亦足以觀其人之曲直剛柔矣”（1444）。在他看来，普遍人性并不会因为诗人工于诗语而被遮蔽。相反，诗对普遍人性的彰显是一种应然。同时他也指出：“以詩觀人者，因其風調趣向，以可觀其氣質也”。这意味着，诗人的个性与普遍人性在诗中是可以并存，不相矛盾的。

第二，读诗的目的是知人之志，因此对读者来说，应用“以意逆志”的态度去阅读。而诗人各有其志，这就为诗的多样阐释开辟了空间。小笠原优轩谈读《诗经》之法，称：“讀三百篇之法，必先得詩人之原志，而後見其若比、若興、若賦。”（3875）有诗三百，即有诗人三百。友野霞舟也认为《诗经》记载了不同阶层和职业的诗人的心志，因此可以作为观察当时社会政教得失的依据。至于后世之诗，他认为：“一代自有一代之詩，指歸雖同,氣格各异”（3875）。对一人、一时、一代的关注，说明友野霞舟其人对诗的审美已经超越了对单一价值取向的追求。

从诗言志，到以意逆志，再到诗的多样阐释，《侗庵非诗话》就提到这样一个例子：虽然杜甫的诗作在宋代以来的诗话中占据了重要的地位，但这些议论将杜诗中的草木禽兽，一字一句都用怨讽、刺乱来阐释，最终将杜诗和经史的理解结合在一起。在古贺侗庵看来，这种单一的阐释方式有损诗杜诗的价值：“如老杜詩古來注解且數百家，其能得老杜之心者無一二。往往固滯牽强，塗人耳目，杜詩妙處不可復睹。”（2067）

综上，“诗言志”这一命题尽管从一开始对诗人之志和诗的价值取向作了规定，但日本汉诗人对这一命题的阐释，在承认“思无邪”这一普遍价值的同时，也强调诗人修辞的主动性，以及诗发生过程中诗人生命与诗性表达的统一。市野迷庵有云：“詩者，志也。讀其詩，而其人之志可知矣稱。”（1679）有诗与志，也有其人、其志、其诗，这两组对立关系可以认为是一个适当精到的总结。

**** 孔子删诗说
孔子删诗说最早出于《史记·孔子世家》：“古者詩三千餘篇，及至孔子，去其重，取可施於禮義，上采契后稷，中述殷周之盛，至幽厲之缺，始於衽席，故曰「關雎之亂以為風始，鹿鳴為小雅始，文王為大雅始，清廟為頌始」。”而班固在认同孔子删诗的同时，具体限定了孔子取诗的范围：“孔子純取周詩，上采殷，下取魯，凡三百五篇，遭秦而全者，以其諷誦，不獨在竹帛故也。”至于《毛诗正义》：“孔子刪定在三百一十一篇內，遭戰國及秦而亡。”

“孔子删诗说”在日本汉诗人中也被广泛接受。他们的论述中，除了强调孔子删定诗经的理由是为了匡复古道，以诗为教之外，还发掘出删诗这一行为所表现出的孔子的诗才。在这样的论述逻辑中，孔子删诗的政教目的与《史记》中的最早论述无异，同时，作为典范诗人的孔子也完成了其在日本诗学中的形象建构。

***** 诗可以教化人心
根据司马迁对孔子删诗说的描述，这一行为的目的，是为了保留可以“施於禮義”的诗。班固也认为，孔子取周诗，是为了能使统治者“观风俗，知得失，自考正”。因此，孔子删诗说首先突出了诗的政教功能。日本汉诗人对孔子删诗说的发挥，主要是为了针对诗坛的不良风气。

《如云诗话》引菱屋孫兵衛之《淇園詩話》，批评诗人作诗长篇累牍，工于词藻的现象，认为这些雕琢无益于为人。作者凭借孔子删诗一说指出，孔子采诗删诗是为了宣扬“天下所宜志之志，因以立天下所宜道之道者也”（5106）。这才是儒家诗教提倡的温柔敦厚，其并非指向诗的辞藻风格。所以，从诗的内容上看，这些经过孔子删定而保留下来的诗，已经脱离了“田亩紅女之谣”的范畴，成为了具有教化功能的“諷歌之辭”。

而江村北海对孔子删诗说的发挥则直接针对时风。他在评《诗学新论》的产生背景时指出，时人空论经学文章，以此博得虚名。在这样的条件下，学问也被认为无用于家国。在他看来，这种风气就如同中国春秋时期“周纲解纽，学教否否，君子道消，肉食不业”，已经到了必须纠正的地步。如果说，面对当时礼崩乐坏的局面，孔子的选择是删定《诗》《书》，为了匡复古道，以惠后学。那么在日本，是否也有这样一个人能够在论诗中恢复古业？在江村北海看来，《诗学新论》的作者原田东岳（1729-1783）可以担此重任。原田先受业于伊藤仁斋的古义学派，后来又师从服部南郭专心于古文辞学派（大分县教育会：《大分伟人传》，东京三省堂书店，明治40年，55-56）。这两个学派都提倡摒弃朱子学、阳明学的注释，直接阅读古代儒家经典。

江村北海用春秋与时事类比，将孔子删诗与原田作《诗学新论》类比，意味着诗的教化功能没有国别之分。以古代儒家经典为中介，圣人在经典中体现的王道和古义是共通于日中两国的。此外，他将原田与孔子相比附，实际上悬置了朱子学、阳明学等阐释学派，直接以日本儒者为中心，试图构建了日本诗论、儒学在儒家经典阐释史中的话语权，反映出了一定的自觉意识。


***** 作为典范诗人的孔子
如前文所述，日本汉诗人对《诗经》的接受是广泛的。而其典范地位，亦有“万代诗法”（《济北诗话》）之称。因此，日本汉诗人在对孔子删诗说的阐释中，树立了中国诗歌史上第一个典范诗人的形象。

虎关师炼就将孔子视作诗人：“孔子诗虽不见，我知其为诗人矣。何者？以其删手也。方今诗人不能作诗者，岂能得删诗乎？若又不作诗之者，假有删，其编宁足行世乎？今见《三百篇》为万代诗法，是知仲尼为诗人也，只其诗不传世者，恐秦火耶？”（285）将《诗经》在诗学传统中的典范地位与孔子相关联的还有石川鸿斋。他也认为：“夫《國風》《雅頌》，孔子選其佳者爲三百篇，數變至唐，唐之詩人最多，又選其佳者而爲法爾。”（4835）

从这些论述中可以看到，《诗经》文本的典范地位确立后，孔子作为《诗经》编订者，其诗人身份才被建构。那么，这一诗人的身份有什么特殊之处？虎关师炼认为孔子能作诗，只是因为秦火而失传。更重要的是，孔子也是一个具备高度审美标准的诗的读者。通过删诗，孔子完成了对后世诗人的立法。




** 日本诗话中的诗：什么是诗？
从“《怀风藻》前的诗意识”这一部分可以看到，日本列岛对诗的认识，同时受到中国诗学和本土上古歌谣的影响。而这双重影响都包含着对于诗的音乐性的认识。再加上日本汉诗人对《诗经》的接受中，入乐的《诗经》和后世诗歌的关系也是他们关注的焦点。因此，诗的音乐特征是日本汉诗经典化过程中，日本汉诗人始终关注的一个重要问题。而这一问题又牵涉到对两国语言差异所带来的诗的价值判断的认识——如果声律是诗的本质规定，那么无法完善使用声律的日本汉诗，是否在价值上天然地劣于中国诗歌？对这一拷问，也引出了日本汉诗人克服两者差异的策略。


*** 音韵是本质规定：日本汉诗人面临的困境 

那么，诗的音乐特征包含哪些因素？诗的用韵、平仄，乃至形式的规整。而对这些因素的认识，是日本汉诗人对诗的本质规定之理解的重要组成。

赤泽一堂在其《诗律》一书中，就将诗律之于诗，类比为法律之于国家，认为音韵和谐是诗的本质：“如官府所頒甲條乙令，一一憶記，能斷妄念，能誡惡事，便是篤行君子也。佳矣哉詩之有律。”（3581）在他看来，一国之法能够规范人的行为，使人行动谨慎，不至犯恶，因此，诗律之于诗，也是必需且有价值的：“詩主音韻。音韻不協，終不可爲詩也。”（3585）冢田大峰也认为，诗所以为诗，本质正在于声调协调：“詩者主諷詠。諷詠之調，古之詩者在五音宫商之協焉，近體之詩則在四聲之協焉。……斯詩之所以爲詩亦可以知也。專尚其聲調爾。”（1443）

然而，日本汉诗人尽管能通过训读或借由通译翻译的方式理解古代汉语，但古代汉语终究是异国的语言，他们在汉诗创作中也认识到了两种语言的差异。

赤泽一堂就曾描述过一个现象：被本国诗人视作大家的诗人，其作品在中国诗人看来价值全无：“长崎港漢人讀本邦所稱名家大家之詩，皆必廢不取焉。無他，其人不知音韻故也。”（3585）在日本汉诗史中，江户时期日本汉诗人的创作已经相当纯熟，并且产生了一批在本国乃至东亚都具有影响力的诗人。然而，在这些诗人中，也有不知音韵的诗人。在此之后，赤泽一堂感慨，尽管古今诗人也常犯蜂腰，鶴膝等声病，但“漢人自有調音之法，可免其帶齒粘喉之病也。本邦之人不可如此。”

冢田大峰也看到本国诗人在汉字四声、用韵上的问题：“而我方作詩者,徒分字之平仄耳,而不得辨四聲。故雖巧作句，或聲調不協，將有不可以諷詠者。”（1442）日本读汉字的读法分为音读和训读，但两者的结果都是不带有声调的，这就去除了汉诗用韵中最关键的因素。

日本汉诗人对本邦诗人不知四声的特点有所认识。然而，倘若将音韵和谐视作诗的本质规定，那么日本汉诗人的诗是否不能算作诗？在日本汉诗人承认诗是两国通用之传统的前提下，这种假设是对日本汉诗价值的挑战。对此，以上汉诗人分别提出了补救的方法。

冢田大峰认为，本国作诗者应当着重注意入声字：“作者雖不能悉辨四聲，尤於入聲字不可以不用心也。”相对于其他三声，入声韵的特点在于短促，而非调值的区分。因此，用对入声的强调进行弥补，是有一定依据的。

赤泽一堂则细辨四声的特点，以使诗的音韵有参差变换之妙。他提出了两点：第一，由于上声和平声相近，因而在作诗时要将两者相隔。第二，去声和入声则是“哑音”，相连会有期期艾艾之感，因此也需要避免连用。

这种对于本国诗人作诗特点的认识，也使得诗韵、诗律类著作在日本诗话中的占到了很高的比例。实际上，从空海《文镜密府论》第一次系统将中国诗学论述引入日本开始，如何根据诗韵、声律进行规范的创作就成为日本汉诗人的必修。







*** 诗是华人之音
以汉字文化圈为中心，以《诗经》为源头构建的汉语诗歌的传统，本是有着自体的延续性的。通过汉字，诗歌形式乃至意象、典故种种话语实现了共有。野口苏庵的《诗规》曾提到，当时的日本汉诗人无法对古人诗格作出有效的解释：“於是返而思之，與質之今人，不如索之古人。”从《诗规》一书所引的材料（严羽（《沧浪诗话》）、魏庆之（《诗人玉屑》）、王世贞（《艺苑卮言》））看，作者所谓“古人” ，指的是中国古代诗人。可见，在他看来，日本汉诗与中国诗歌为代表的汉语诗歌传统是一脉的。

然而正如上文所言，两国之间的语言差异是天然存在的。而对这种差异的认识使得上述延续的汉语诗歌传统产生了断裂的可能。

**** 断裂及其克服：音不重要

在这样的情况下，对“诗”这一概念的国别性，在日本汉诗人对“诗”的认识和定义中得到了强调。他们承认本国汉诗传统与中国诗歌传统之间的界分，同时也认识到了中国诗歌传统对本国汉诗人创作的制约。《日本诗史》对此的总结最为精到：“夫诗，汉土声音也。我邦人不学诗则矣已，苟学之也，不能不承顺汉土也。”（46）。

而在一些日本汉诗人看来，尽管日本汉诗的创作确实受到中国诗歌传统的影响，但语言，特别是语音的差异并不妨碍日本人对诗意的理解。

小野招月认为，日本汉诗人在创作时：“况在此方用彼之言語以叙我之性情，摸其聲調於髡鬚影響之間，不得不依準其一定之矩镬。”（1697）在这里，语言和性情的对立成为了日本汉诗生成过程中的特殊矛盾。在这样的情况下，日本汉诗人在创作时就必须依照汉语的声律规范。但在另一方面，他也从读诗的个人经验出发，指出日中两国诗人对于诗的节奏、意义的感受并无大异：“試取明清人評古詩者覽之,曰某篇有調者，我亦覺其有調,日某字不響者，我亦覺其不響。非意有異同，所争音節而已。是故詩之驚心動魄總在吟誦之際，不必待細繹其義，而涕已墜之。定知聲音之道，和漢無大異也。”（1710）

三绳桂林亦指出：“夫詩，華人之語也。修其辭者，學華人所爲也。若必欲爲和語，則自有國風三十一言在焉，何以詩爲？”（1409）在这里，華人之語被视为诗的本质属性。此处的“国风三十一言”并不是指《诗经》的国风，而是指以《万叶集》中五句三十一音的歌为代表的和歌。他反对当下诗人将本民族的语言写入诗中，正是要保持两种语言文学的泾渭分明。具体到汉诗创作中，则是要求汉诗人的修辞遵从中国诗歌传统。同时，他也注意到，两国语言的差异最主要还是语言层面上，至于意义则是相通的，所谓“辞無彼我，而有彼我者，音也。”（1413）在此基础上，他认为诗的价值不以两国语言语音之差别为标准，而是在于对意义的表达方式是否精工，诗格的彰显是否高昂。这意味着，通过一定的学习和训练，日本汉诗人也可以达到和中国诗人的高度。

这些论述若通过对汉字本身特点的分析也是可以成立的。汉字是形音义三者的结合。而日本汉诗人之所以能读中国诗人的作品，以至于能写汉诗，主要还是因为，相对于语音的历史变化，汉字的形状和字义是相对固定的。汉字的这一特征也使得汉字文化圈下的古代汉语诗歌传统能够在东亚地区生根、发展出各自的民族特色。


**** 断裂的克服：诗与日本民族文学的关系

重新定义日本汉诗在整个东亚汉字圈为中心的汉语诗歌传统的位置，以及日本汉诗与中国诗歌传统的关系，也会引发日本汉诗人对“诗”与“歌”两种文体关系的反思。然而与三绳桂林强调诗、歌相异不同，也有汉诗人从歌、诗关系出发，试图克服日本汉诗与中国诗歌传统之间可能出现的断裂。具体来说，他们的策略主要从两者对普遍人情的表现和创作技巧两方面入手。

《诗辙》指出，诗是将人情语言中不能够说尽的事情，在咨嗟咏叹之余中所发出的。不管哪个国家，都应该有诗。本国的歌，其中的字原来是被翻译过来的缘故，因此其字都是训读。和歌就是和诗（日本诗话丛书，7，206）。

而俳谐是和歌的变体，所谓“古國風之一體”。金田梅邨提到，俳谐与诗尽管从文体发展的角度来看不属于同一个类别，但都是俳人、诗人诉说心曲，描摹所见之物的载体，因此，两者在创作上是相通的。赤泽一堂也表达过类似的观点：“二條家和歌者流之言曰：臨題起思，應須仰看雲之往來。作詩亦有此理。”（3582）

这些论述强调诗、歌乃至俳谐共有的言志功能。而到具体的创作中，兼康百济就认为，从以花为贵的立场出发，日中两国的人情是相通的：“本邦謂櫻爲花，稱花王。鹤林玉露云：洛陽人謂牡丹爲花，成都人謂海棠爲花，尊貴之也。可謂東西同一人情矣。”（《浪华诗话》，2648）

东梦亭在其《锄雨亭诗话》中提到：“詩人輕和歌，歌人亦仇視之（2915）。彼此俱非。至其妙悟，詩歌一致。”妙悟是诗人与歌人写出优秀作品的前提。同时，他引用了藤原爲家和藤原俊成对和歌创作之技法的论述，认为诗人和歌人在创作过程中，都会十分注意前后句子的衔接；另外，和歌的妙处不在于对细节的雕刻，而在于对整体的呈现，这种艺术观念也是诗人与歌人所共有的。


*** 天地自然之元音：对人工声律的超越
市河宽斋曾言：“近體至唐而大定”（1473）《诗律》一书也指出：“近體之詩，雖有諸家不一，皆出於唐，所以不及矣。”（3582）这说明，日本汉诗人认识到诗的声调、格律在唐代已经大致定型。小野泉藏也认为后世诗人所依照的诗律，大多是指唐代的诗律。而他同时指出，诗的声律发展到唐代，成为后世诗人创作所必须依据之法，其原因并非是诗人们对声律的雕琢，而是出于天制：“天工人作，始非有二也。人豈以天地間所無者别制出一機軸者哉?故以聲律爲唐之制作則不可也，天之制也。”（1703）他认为，人是天地万物的一种，因此人在诗歌格律上的制作是天地规律的体现。

而实际上，这种将诗的形式特点视作天地自然运作之结果的观点并不只是小野一家之言。而通过诗律与天地自然规律的统合，诗其本体也称为天地运作之结果，与诗人考
刘總在《文心雕龙物色》篇巾指出对诗律的精工没有关系。卢松江在其《唐诗平侧考》中提到，能够留存到后世的诗律法度，是因为这些诗律规范符合天地自然：“詩者,天地自然之音也,豈無自然和谐之律耶？若夫心之所之，與律抵牾，則詩非其詩，尚何自然和諧之有?”（5290）在这样的观念下，诗律的正体和拗变被统合在了自然之律下。只要是符合天地自然之音的，不论正拗，都是和谐适宜的。

日尾省斋在《诗格勘误》中引袁枚《随园诗话》：“夫詩爲天地元音，有定而無定，到恰好處自成音節，此中微妙，口不能言。試觀《國風》《雅颂》《离骚》乐府，各有声调，无谱可填。”（3644）从中国诗歌传统来看，不同的诗体之所以有其特点，并非是因为人工制谱而形成的。诗是天地运作规律的体现。

那么，将诗作为天地元音，诗人又在诗的发生过程中承担了什么样的功能？《社友诗律论》云，学诗者，其首要在于能够辨别天地自然的音律，只有善于聆听，才能在创作中加以相应和协调：“故学者未知音律也，求善聆也。夫瓦釜金玉,誰不辨之?至其鐘鼓鏗鈸，宫商相證，則調不調，必有善辨者矣。”（1705）如同一般的陶器和金属，它们之间的材料、音响的区别是容易辨认的。但是各个乐器之间倘若配合演奏出和谐的乐章，那么乐者首先要能辨别每个乐器的特质，而后再根据音律协调的规律作出调整。可以认为，以天地元音为诗之本质的诗的意识中，诗人感于物而发于声。冢田大峰所对诗人与诗的关系就曾有过这样的论述：“蓋作詩者，素何由也?春秋風月之望，花鳥物候之看，水煙波之觀，人世哀樂之會，觸乎其物,應乎其事感於心胸，發於唇舌，乃假文詞以伸其志情，斯所謂詩者也。”（1448）

可以看到，将诗视作天地自然之元音，超越了格律的人工生成之说，继而超越了日中两国语言差距对日本汉诗人规范使用格律的制约。


*** 口语与书面

**** 书面性

从以上论述中可以看到，日本汉诗人将音乐性视作诗的核心特征。然而，在追求规范用韵、声律的过程中，一部分日本汉诗人意识到，两国语言存在着差异。这意味着，对他们来说，若作为“汉土声音”的诗及其声律，不仅可能无法完全掌握，甚至有害于本国诗人诗作的价值。这里以“汉土声音”为代表的语言差异观，实际上指涉的是语言的语音层面。而相对于其语音的历史变化而言，汉字的字义是相对固定的。因为汉字的这一特点，两国语言语音层面上的差异对汉诗人对文本的理解和创作并不构成无法克服的困难。

汉字是汉语的书面表记。如果说诗的音乐性是从文学的口传时代在书面文字中的一种留存，那么，在音乐性之外，作为一种书面文体的诗有着怎样的特点？对这些问题的回应可以对日本汉诗人的诗意识作进一步的探寻。

菊池五山对诗的书面特征作了精到的总结：“詩人則識文字，故把口頭之話化作筆端之話，把一場之話化作千萬場之話，把對面數人化作不對面千萬人，唯恐聞之喜之快之笑之記之忘之者之不多，是詩人之心而詩人之神通力也。”（1733）他认识到，诗是口头语言转化到书面语言的产物。而由于其书面的特质，诗的传播范围更广，成为诗人与读者进行对话的中介。

市野迷庵则是从诗人创作和读者接受的角度，看到了诗的语言和日常语言的区别：“是以言之所不能述，詩能出之；人之所不能睹，評能發之。”（1680）在他严重，诗歌一方面拓展、补充了日常语言，特别是口头语言在表意方面的缺憾；另一方面诗的价值的完善，也必须有评价者揭示他人所不能察见。如此，作为一种书面文体的诗，其语言在表意上就具有模糊性、朦胧美。


**** 和其他文体，尤其是和歌的区别与关系：雅与俗

那么，诗与其他书面文体相比，又呈现出怎样的特点？长野丰山总结过：“有經語，有史語，有小說家之語，有語錄隨筆之語。論，記，序，書，尺牘之類，文體已異，語氣自别斷斷不可混用也。有套語，有歇後之語，用之詩、尺牘、小文辭猶可也。至作大議論、大文章，則必不可用也。”（2680）在这里，作者具有相当的文体自觉意识。而从他对诗语的论述中也可以看到，诗与尺牍等文体的共同特点是短小精炼。另外，从语用色彩来说，作者认为诗与文的差异在于，诗可以加入习惯用语以表达轻松、诙谐，但其不可以用以进行严肃话题的议论。这种区分将“诗”分离出“经”的范畴，更强调诗的生活和娱乐性。

同样是从创作角度出发，山本北山的视角则更为微观。他观察到了诗与文在虚字使用上的不同。所谓“虚字”，即在诗中起到承接词句功能的字。如杜甫“久客惜人情，如何拒邻叟”中的“如何”；杜牧“千里暮云重叠翠,一溪寒水浅深清”中的“重叠”。作者认为，写诗和作文所用虚字不同，不可错用：“童蒙之游词场者，用虚字最難。而文自有文之虚字，詩自有詩之虚字，若失之用，文不文，詩不詩也。”（5542）


像“经”、“史”、“小说”等文体，均是从中国舶来的。而关于诗与日本民族文学之源的“歌”在用语上的区别，日本汉诗人也有相关的论述。总的来说，他们认为诗与歌最大的区别在于语言的雅俗。《诗学逢原》一书提到这样的观点：“有人认为，诗是风雅的容器，而不是俗用的物品。如果里面充斥了大量的常语、俚语，那么诗就不是诗，而是和日本的歌差不多的存在。特别是白居易的诗，有人就用这一点批评其诗不风雅。”（日本诗话丛书，2，27）在这里，语言的雅俗不仅区分了诗与歌，语言之“雅”还成为了汉诗经典化的重要依据。

对诗的语言之雅的追求无法否认儒家诗学的影响。本居宣长在其歌论著作《石上私漱言》中将歌与诗的意趣进行了比较，认为诗“以其国风习左右,故悉闻如说教而不生怀想”（东方文论选，774）。在本居宣长看来，儒家诗学对诗温柔敦厚之旨的要求，对诗的语言形式产生了影响：出于对正统价值的追求，诗人往往使用雅语。而本居宣长对诗的评价也因此不如本国之和歌。他认为，诗的雅语是诗人对语言加以粉饰的产物，遮蔽了对人之真情的表达；而和歌的语言相较而言更加生动活泼，也更能表现自然的情趣。

然而，从诗发展的客观规律来看，语言的雅俗并不构成诗的经典化的唯一依据。上文《诗学逢原》中提到的以“雅”作为批评白居易诗的观念，并不能否认白诗在平安朝时代的流行。而本居宣长的论述则是通过对诗中雅语和教化之价值观的贬斥，突出和歌在本国文艺中的优先地位，其论述是为其国学思想服务的。而其他汉诗人也对诗语的多样性有所认识。广濑淡窗有言：“诗无唐宋明清之时代的区分，只有巧拙雅俗之分。”（日本诗话丛书，4，246）对古代诗的学习，要注意到诗的文本自身的话语特殊性，去品味诗人在字句上的推敲。至于诗语的雅俗与否，并非评价诗的价值的唯一依据。而服部南郭在其《南郭先生灯下书》中的论述，不仅从不同的文体中发现语言的雅俗，还注意从四书五经的注释中去思考相关的问题。他发现朱熹对经典的注释中有时也会使用俗语（日本诗话丛书，1，54）。而朱子学在当时的日本被奉为唯一的正统思想。这证明语言之俗，有时并不能决定文本的思想纯正与否。因此，诗句中也应当可以用俗语。



诗有别才


**** 诗有别才
综上，作为一种书面文体的诗，在形式和语言表达上有其特殊性。这就是所谓诗家语。而对诗家语的认识，可以看到日本汉诗人对诗这一文体的自觉意识。于是，诗才也被认为是一种特殊的才华。

广濑淡窗的弟子评价其师时认为，鉴赏诗的能力是创作好诗的前提：“世知淡窗师妙於詩，而不知其最深於知詩。唯其深於知詩,是以妙于詩。”（5378）“知诗”，即知道如何评价诗，知诗者往往拥有高深的学识和鉴赏能力。而“妙于诗”，当指善于诗的创作。广濑淡窗的汉诗成就很高，而这一成就离不开他对诗的深入理解和认知。他的学生说他：“故自三百篇及唐宋之作，沉潛涵泳,心會意融，於古人性情與古詩神味，莫不契合”。也就是说，这种理解和认知，又是长期浸晕在以诗经、唐宋诗为代表的诗歌传统中。在此过程中，人既吟味了古诗，又契合了古人的性情。因此，可以说古人性情和古诗神味是“知诗”的两个方面。以上这些都是妙于诗所必不可少的。

但在另一部分汉诗人眼中，一位诗人作诗的才能和论诗的才能是不同的。山田翠雨在《翠雨轩诗话》中就总结过：“凡作詩者無話,話詩者無詩,能詩能話兼之者鮮矣。”（5388）《锦天山房诗话》评价太宰春台时亦提到：“春臺操行學術，卓绝時輩。其詩文似亦解作者之旨者矣。及其自運則椎魯粗笨，殊乏興象，宜乎詩有别才也。”（3059）在这里，友野霞舟说时人春台对诗的理解相当精到，以至于如同了解了原作者的心思一样，但是春台自己写诗却一般。友野霞舟将论诗的眼光和作诗的能力加以区分，是所谓“诗有别才”。

