** 日本汉诗史的分期及其重估

这章以日本汉诗史的分期问题为中心展开，一共分为三个部分。第一部分阐述日本汉诗人在论诗时所体现的分期意识。而这种意识一方面来源于日本汉诗人对中国诗歌传统的阅读；另一方面则体现在他们对本国汉诗传统的认识上。第二部分梳理现有日本汉诗史的分期方式。第三部分则是从多种民族文学史中，在定位日本汉诗位置的基础上，重估现有日本汉诗史的分期。

**** 日本汉诗人的分期意识
***** 中国诗歌史

日本汉诗人的分期意识首先来自于对中国诗歌、诗学文本的长期阅读。在此过程中，日本汉诗人也会注意到中国诗歌历史的变化，并对此加以总结。

日本汉诗人通常很重视《诗经》和唐诗在中国诗歌史中的地位。从上文的描述可以看到，《诗经》作为中国诗歌史的开端，这在日本汉诗人的心目中几乎是不容置疑的。而唐代诗歌则是另一个高峰。而唐诗的影响也从日本汉诗的发轫期一直延续到了繁盛期，即江户时代。大儒林罗山曾说“李杜全集，到今家家有之。”（林罗山文集卷七十三，转引自 概论日本汉文学中的杜甫受容）再加上平安时期崇尚白诗，这些从一定程度上可以反映出唐代诗歌在日本受到的关注持续了很长时间。

而对中国诗歌发展史的宏观认识上，严羽的总结影响较大。三浦梅园《诗辙》卷二引《沧浪诗话》原文云：“《風》《雅》《頌》既亡，一變而爲《離騷》，再變而爲西漢五言，三變而爲歌行雜體，四變而爲沈、宋律詩。五言起於李陵、蘇武，七言起於漢武《柏梁》，四言起於漢楚王傅韋孟，六言起於漢司農谷永，三言起於晉夏侯湛，九言起於高貴鄉公。”（日本诗话丛书，6，104）同时，《诗辙》一书还采《诗品》、《诗薮》等中国诗学经典，细探古体、近体诸体。

相较《诗辙》对中国诗歌发展史的认识沿用中国诗学传统的话语，江村北海的《日本诗史》则以日本汉诗为基准，重构了中国诗歌的发展历程。“文武天皇，大宝元年，为唐中宗嗣圣十四年，上距梁武帝天监元年，几二百年。弘仁天长 初唐天历应和，崇尚白并勉乎百年之后。五山诗学之盛，当明中世在彼，则李何王李，唱复古于前后。在此则南宋北元。专传播于一时。我元禄，距明嘉靖亦复二百年。则七子诗，当行于我邦，气运已符。”（46）以日中两国汉诗发展中的两百年距离为参照，江村北海构建了一条从梁武帝天监元年开始至当时清代的中国诗歌史。

除了以诗话为载体的论述，赖山阳等诗汉诗人也尝试用论诗诗的形式，对他们眼中的中国诗歌、诗学理念作出诗性的评价（近世东亚汉诗流变，403）。而这种以诗论诗的传统，从日本汉诗的发轫期就开始了。菅原道真就有论诗诗留世，而江户后期的折衷派诗人更长于以这样的方式表达他们对中国诗歌传统的理解（亚洲汉文学，98）。可以认为，论诗诗在日本汉诗史的书写中是特殊的：它既为日本汉诗史的书写提供了值得关注的史料，呈现出日本汉诗人对中国诗歌传统的阅读史、接受史，又是泱泱日本汉诗经典中的一部分。







  
***** 日本汉诗人的诗史书写

****** 日本诗史书写与中国诗史书写的关系

在展开本部分之前，必须对“诗史”的概念作简要的介绍。“诗史”产生于中国诗学传统。这一概念最早源于孟棨《本事诗》的概念，与杜甫在安史之乱期间的叙事有关；而自宋到清，诗家对这一概念的阐发也始终围绕着“诗史”叙事与抒情功能展开（张晖的《诗史》（台湾学生书局，2007）257-267）。

而日本的诗史传统同中国的诗史书写有着相当的联系。而其核心关联在于对杜甫的推崇。市野迷庵（1765-1826）的《诗史颦》一书在进入近代后受到了诸多关注。以明治时期日本政治家柳原前光为代表的读者，对于“诗史”的理解，围绕着杜甫这一典范诗人，以及“诗史”记录时事的功能展开。具体来说，柳原前光认为：“古之詠史者，一言一詠，皆有所爲而作,故往往有詩史稱。後之作者，率不察當時情勢，慢然品評,赞之罵之，亦不過玩弄古今人物而已，豈詩史云乎？”（1678）又有汉学家市野光彦：“杜少陵，詩聖也，而有詩史之稱。”（1689）

为何推崇杜甫？除了因为杜甫是历代“诗史”观念的核心，还因为市野迷庵创作此书的动机。他有感于日本南北朝战乱时期价值观混乱、伦理无常，于是择其中南朝忠诚有义之士的诗史之作，以重新赋予本国南北争战时期与杜甫诗史所体现的家国思想相当的时代价值。
而明治时期的政治家、汉学家们重视此书的原因也在于此。虽然南北争战的结果以足利幕府支持北朝为胜利告终，但明治天皇亲自裁决，认定南朝为正统。在这样的情况下，对南北朝时期历史的重新构建，便成为明治政府书写新的国家记忆的必要环节。诗圣杜甫和他的诗史也在此过程中被视作价值的典范。

这些观点是近代日本诗、史、经三位一体思想中尊皇理念的集中体现。那么，诞生于江户时代的《日本诗史》便具有其特殊性。作为一部具有文学史性质的诗话著作，江村北海的诗史书写尽管在品评诗人时也具有儒家诗教观念的痕迹，但从整体的体例上来说，它较完整地呈现了日本汉诗从奈良平安时代到江户时代的发展，同时也对当时京都、江户，乃至其他地区的诗人诗作作了全面的整理。

而对于该书的情况，论文第一章已有专文论述。这一部分将对日本汉诗人对本国诗歌发展史的思考进行梳理。

****** 对诗史源头的描述

首先，日本汉诗人关注本国汉诗传统的源头。围绕经典文本和典范诗人的争论，日本汉诗人建立起以《怀风藻》为中心，大津、大友二皇子为典范的诗史观念。

细川十洲的《梧园诗话》在卷首讨论了日本诗赋之始的相关争议：《怀风藻》的作者是谁：大津皇子、大友皇子，还是淡海三船？另外，大津、大友两皇子谁才是日本的诗赋之祖？实际上，前一个问题至今没有定论（日本汉诗发展史，145）。而对于后一个问题，细川当时搜罗的观点中，《日本书纪》、《古今和歌集》、《古今著闻集》等著作认为大津皇子是本国诗赋的开始，而这一观点被古人广泛接受。但是《怀风藻》则载录大友皇子所作汉诗。《今昔物语》的观点则与《怀风藻》相同。
作者关注到了两种观点的差异，认为：“想二皇子虽有前後，大抵同時，俱好文學能詩賦，易致混淆，故有此二说已。”（4946）而除了这两种主流的观点，还有观点认为：“又按《朝野群載》載《詩境記》，謂我朝詩賦起於弘仁承和，則不知前此有二皇子也。”

可以看到，有关本邦诗赋之始的观点冲突，展现了当时的诗话作者，已经有意识地思考本国诗歌史中的里程碑事件和典范诗人。

而关于日本诗赋之始的讨论，《诗法详论》则倾向于大友皇子：“按弘文帝述懷之御製，我國作詩之始也。爾來朝野争賦詩，而白氏之體尤行於世，觀江菅諸家之詩而可知也。蓋當時往來唐山，禮樂文物往往摸傚焉，勢不得不然。”（4833）

除此以外，作者在这里还讨论了日本汉诗发轫时期的诗风，即对白居易诗的效仿。更值得注意的是，作者还分析了其中的原因。他认为，由于日本和唐朝交通往来，日本在礼乐文化等等方面受到对方全方面的影响，因此赋诗在日本贵族阶级的流行是大势所趋。从作者对平安时期日本诗风，乃至文化风气的分析中可以看出，当时作为汉诗创作主体的贵族阶级，其对赋诗的热情，是包摄于日本对唐代仪礼制度的全面模仿上的。


****** 诗史发展的展开
也有诗人对本国汉诗传统的发展历程作了梳理，其中可见其分期意识。

中井竹山认为，平安、江户时期是日本汉诗发展中的两个高峰，而自五山至江户的近五百年时间，可说是日本汉诗发展的低谷，所谓“聲詩之道墜在浮屠氏”（1006）具体来说，平安时代的高峰地位是因为日中两国的往来，使得日本得以输入大量的唐代诗歌。至于江户时代，则是因为德川幕府主政，全国政局稳定，亦重文教。

细川十洲则论《怀风藻》到五山时期的汉诗风尚：“本邦古詩，如懷風藻所載，氣象敦樸，有西土漢魏六朝之風。及白詩傳于我，則上下靡然以此爲宗,不獨菅家也。北條氏時，禪僧與西土人相往來，而五山之僧好誦《联珠诗格》《律髓》《三体诗》。”（4947）总的来说，细川对本国汉诗传统的描述，强调中国诗歌的影响，日本汉诗发展过程中每一次诗风变化都是因为中国诗歌、诗学文本被受容的体现。

信夫恕軒则将日本汉诗的发展历程经历了“四开四败”（明治诗话，5005）。具体来说，他描述了从平安，到五山，再到江户、明治的发展过程。同中井竹山一样，他也否定五山时期汉诗的价值。同时，他也观察到本国汉诗创作主体的变化：从公卿到僧侣，再到士人、儒者、农民商人，最后再到明治时代的政治家、平民。可以看到，与汉诗发展历程同步的是，汉诗创作主体范围的扩大。可以认为，到了明治时期，汉诗的创作逐渐成为了一项全民性的活动。然而，作者并因此认为日本汉诗的价值也随之提高。他指出了日本汉诗发展到当时的两个缺憾：一是缺乏长篇的创作；二是剽窃模拟，缺乏创新，视野局限在近体诗中。他敏锐地意识到日本汉诗表面的兴盛和内部创新活力的缺乏之间的矛盾。

总的来说，这些汉诗人对本国汉诗发展历程的分期，大致与当前学界对日本汉诗史的主流看法相当。此外，他们也注意到区分本国诗人的不同身份，并以至为一条描述日本汉诗发展的线索。而这种对诗人身份的关注在《日本诗史》中已经有所体现。其卷二专论江户时期之前不同身份的诗人，具体分为武家、隐士、医者、僧侣和闺阁。

****** 典范诗人的树立 - 和分期的关系是什么？

而在早期汉诗总集的编撰中，强调诗人身份的意识已经存在。如《怀风藻·序》：“凡一百二十篇。勒成一巻。作者六十四人。具題姓名，并显爵里，冠于篇首。”《凌云集·序》：“依爵次……作者二十三人，詩總九十首，合為一卷。”《经国集·序》：“作者百七十八人……人以爵分，文以類聚。”（小島之氏『国風暗黑時代文学』）在这些汉诗集中，除天皇、皇子以外，编撰者会写明每个诗人的官爵和姓名。只是王朝时代的日本汉诗人从职业、阶层来看主要集中在贵族和公卿，因此其分类不如江户时代丰富。

那么，对诗人身份的关注和对日本汉诗传统的分期意识有什么关系？有两点。第一，日本汉文学史的书写中，以各阶段创作主体身份的转移为分期依据是一种主流。这种分期依据同样适用于日本汉诗史，因为这种分期依据的背后，是汉文作为一种知识教养，由于各种因素不断转移和扩大的过程，而汉诗的发展是在这个框架中进行的。

其次，对诗人身份的关注，意味着对日本汉诗传统的构建是以作者而非文本为中心的。这些诗人在日本汉诗史中的典范地位也因此得到确认。

******* 用人名的数量
在日本汉诗人的论诗著作中，常可见到列举典范诗人的做法。

森如云在论本国汉诗发展历史时，就总结了各个阶段的典范诗人：如中古，有菅原道真、小野篁夫、大江匡房等人；五山，则有虎关师练、中津绝海等人。至于江户时代，有名诗人更是不可尽数。藤原惺窩、石川丈山、伊藤仁齋、木下順庵等儒学者及其门人，主持了享保正德年间的诗风发展。而到文化年间，则有賴山陽、梁川星嚴、廣瀨淡窗等汉诗人。其笔触虽不及《日本诗史》那样广泛，但其论述聚焦在诗学上，因此对于日本汉诗发展历程的勾勒还是简洁有力的。冢田大峰对本邦诗家的介绍则偏重于天皇、公卿、武家大名。在他看来，这些诗人的风格或精练，或有风雅之趣，皆是本国汉诗的代表。（1458）

大田淳轩则是用详细的名录说明本国赋诗的悠久历史。以下试举一部分：“而营公菅文時，大江匡衡、大江以言、三善清行、藤原冬嗣、藤原兼良、藤原賴長、藤原伊周、都良香、源順、源經信等諸臣，亦皆相争賦詩。當時作詩之盛可概見矣。”（5164）由此，作者认为本国可以称得上为“诗国”。从其论述看，所谓“诗国”，要满足两个条件：一是悠久的赋诗历史；二是有蔚为可观的创作群体。作者略于诗风的描述，而详于诗人姓名的排列，实际上是将这些姓名作为构建本国汉诗传统的符号。


******* 诗人内部的比较 - 本国汉诗传统的建立

西岛兰溪以诗人对本国汉诗传统的构建，则是通过本国诗人在诗的意象和主题上的创造、传承为起点展开的。西岛兰溪沿用了皎然《诗式》中“三偷”的说法，认为“偷其語者爲之下”（2562）。其后，他例举了祇園南海、江村北海诗句中和新井白石意象和主题相似的诗：

“君不見東家阿嫗年七十,夜來向市買燕脂。”（白石）
“東鄰妖嫗尚效顰，夜買燕脂佩鸡舌。”（南海）
“歸意蘼蕪绿，離情芍藥红。”（白石）
“離情寂寞蘼蕪綠，愁心生憎芍藥紅。”（北海）

此处可以同《作诗质的》对“三偷”的发挥作类比。冢田大峰以“三偷”为切入口，考察了中国诗歌发展史中，不同阶段之间的关系：“唐人則偷之於六朝以上古人,往往有徵之者。又盛唐以下，則有偷之於初唐者。……明七子联句，多窃句势于唐人律调。”

由此可见，“三偷”这一说法，是在同一诗歌传统中，考察不同阶段诗人诗作，在语、意、势三个方面与前人的关系。于是，一个互文的诗歌传统就被构建了出来，每一个阶段的诗人才得以在传统中找到自己的位置。

如此，西岛兰溪对南海、北海、白石三人诗句的考察，其意义也就不仅局限在相似之处了。更重要的是，此处对三者语、意、势的观察，是在日本汉诗传统内部进行的。这意味着，尽管《弊帚诗话》并非像《作诗质的》那样，从一个相对成熟、完整的诗歌发展过程中入手，但它体现出了对日本民族文学意象和主题的重视，以及对区别于中国诗歌传统的日本汉诗传统的关注。






**** 现有日本汉诗史的分期方式
***** 日本诗史

从凡例中可以看到，江村北海撰写《日本诗史》时，其关注的重点在于元和以后，即江户幕府时代的日本汉诗。尽管如此，《日本诗史》的第一卷涉及到所谓“中古近古”的汉诗。此卷也是现存较早的对日本汉诗发轫期文献、主要作者进行系统梳理的文本。

《日本诗史》的体例并不像文学史那样结构分明，并非全然按照日本政治史或文化史的推进来进行的。相对地，该书以日本汉诗人为主轴展开。卷二有云：“五山禪林之詩，固不易論也。蓋古昔文學盛於弘仁天曆，夷於延久寬治，泯沒於保元延久平治。於是世所謂五山禪林之文學代興。亦氣運盛衰之大限也。”（24）由此可见江村北海将江户之前的本国汉诗传统分为四个阶段。结合平治之乱等历史事件，可以认为江村北海也在政治之治乱的框架下讨论本国汉诗的兴盛衰落。

在《日本诗史》的分期中，中古近古之后又一个重要的时期便是五山时期：“於是世所謂五山禅林之文學代興，亦氣運盛衰之大限也。”（卷三）也就是说，在江村北海看来，五山时期是日本汉诗发展过程中的一个低谷。从其所选择详细论述的作者数量看，绝海中津和义堂中信二人尽管诗才卓越，但这一时期的整体创作风气不能与前一个时段相比。而这一时期之所以“五山”为名，是因为幕府的扶持，使得五山寺庙、僧侣集中了大量的物质和文化资源：“於是凡海内談詩者，唯五山是仰。”（卷三）从中可以看到五山在当时的地位。

五山之后便进入德川幕府的统治。江村北海本人生活在江户中期，又为当时大儒，又与当时汉诗人多往来，所以对这段时期的汉诗情况着墨甚多。而对这一阶段，江村北海并未再以时间顺序对其再作整理，而是转换以空间的维度，对京都、江户及其他令制国地区的汉诗人、汉诗作品进行整理。

****** 总结

总的来说，《日本诗史》是一部具有文学史性质的诗话著作，以诗人为主体展开，并没有形成明确的分期意识。同时，本书中已经能看到“中古”、“近古”等时间标志，呈现了江村北海对本国汉诗传统的整理意识。

***** 日本汉诗史
菅谷军次郎的《日本汉诗史》，其分期按照日本政治史的发展，从奈良朝时代写起，再到平安朝、镰仓幕府时代、室町幕府时代、江户幕府时代，最终以明治时代告终。
具体来说，每个部分的关键人物、重要事件和特点如下：
奈良朝时代以前。天智天皇时期，百济博士传来儒家经典。从诗风上来说，受到了六朝和初唐诗歌的华丽风格。
奈良朝时代。和铜三年三月，元明天皇迁都奈良，直到光仁天皇，共计七十五年。这一时期的诗风同上一个阶段没有多大变化，但七言诗的创作增多了。
平安朝时代。桓武天皇于延历十三年迁都平安京，直到源赖朝建立镰仓幕府。这一时期围绕汉诗创作展开的游戏、诗会等活动成为主流，诗的风格也带有游戏的色彩。
镰仓幕府时代。这一时期日本佛教兴盛，尤其是禅宗。汉诗的创作较上个阶段更加衰减。整体的诗风，尚宋诗、《三体诗》。
室町幕府时代。这一时期被认为是文教衰败的时代。足利学校和寺子屋在战乱中保存了日本的文脉。
江户幕府时代。应仁之乱被平定，德川幕府统一天下，复兴了日本的文教。
这种分期方式背后的文学史观，实际是将日本汉诗的发展统摄在“政治-文教-文学”的框架中。在《日本汉诗史》中可以看到，它的分期是以日本政治史的重大事件为依据。此外，它的分期中还包括日中两国文化往来的重要事件，如遣唐使、禅宗输入日本等。而每个阶段执政者对文教的重视与否，乃至政策等等，都规约了汉诗的发展。总的来说，《日本汉诗史》在分期上强调与汉诗创作密切相关的政治、文化背景，没有树立日本汉诗发展的自身脉络。

***** 日本汉诗发展史
在《日本汉诗发展史》第三章，作者专门讨论了日本汉诗的分期问题。
首先，作者对冈田正之和吉田学轩两位学者的分期方式作了评述（56-58）。这两位学者分期方式的共同点在于，以创作主体身份的变化为主要线索，试图勾勒出日本汉诗演进的面貌。针对冈田正之的《日本汉文学史》，作者认为其缺憾在于书写不完备；对于吉田学轩的《平安朝时代的诗》，作者则指出其分期的标目修辞整饬，但逻辑不严。
从作者的评述中可以发现日本汉诗史发展的一种重要面向：
在日本汉诗史的演进过程中，作者群体身份的几次转变是很明显的，并且可以作为考察某个时期日本汉诗审美特点的重要切入口。
那么，作者自己在书写日本汉诗史时，所采用的是哪一种分期？作者认可了猪口笃志以时序为标目的分期方法，将日本汉诗分为发轫期的王朝时代、嬗变期的五山时代、成熟期的江户时代和衰替期的维新时代（59）。
单单从作者的标目来看，被称为“嬗变期”的五山时期应是受到尤其关注的。因为这一时期处在日本汉诗从发轫到成熟之间，对“嬗变”的观察或许可以窥见江户时代日本汉诗中强烈的民族风格形成之前的迹象，继而有助于从整体把握日本汉诗的演进逻辑。然而，作者对“嬗变”却别有解释：“如果说王朝时代的汉诗较近“唐风”的话,那么,五山时代的汉诗则渐具“宋调”。这不能不说是随着世移世迁而发生的大嬗变。被奉为偶像、备受崇尚与模仿的人物已经不再是白居易,而变成了北宋诗坛的巨擘苏轼、江西诗派的领袖黄庭坚以及宋人最为折服的诗圣杜甫。”（63）

可见，此处所谓“嬗变”，指的是日本汉诗风格的变化。而这变化是以日本汉诗人师法之对象为原点提出的。
诚然，随着师法对象的不同，各个时期的诗风也会发生相应的变化。正如《日本汉诗史》中所叙述的那样，日本汉诗人的模仿对象经历了长时段的变化：从《毛诗》、《文选》，到白居易、韩愈、黄庭坚，再到性灵派诗学，而这些诗人、诗作乃至诗学思想，都对日本汉诗诗风的形成产生了重大的影响。但需要注意的是，如果单将对中国诗坛的学习视作日本汉诗嬗变的原因，那么日本汉诗就仅是中国诗坛的延伸，其内部的演进逻辑被悬置了。

其后，作者总结道：“而五山时代的诗人固也致力于模仿,但不仅其模仿的水准要高出一筹,以致达到惟妙惟肖的地步,而且也常常能独出机杼,变化生新。一句话,已从机械模仿的状态中蝉蜕出来。”（64）

在这里，“嬗变”意味着日本汉诗人师法水平的提高——他们可以充分理解宋诗的风格，以至精神。同时，也说明这一时期日本汉诗有了新的风格。这里的“变化生新”可以认为是与中国诗坛相区别的部分。五山汉诗的文学史意义于是呼之欲出：从这一阶段开始，日本汉诗的民族特色首次被承认了。如此一来，江户时代对本民族特有风情的张扬，是继承了五山时期的创作遗产，因而被视为日本汉诗的成熟和繁荣期，可以说是符合作者的汉诗史构建的。

然而，从日本汉诗史的全局着手，我们不免疑问：什么样的“和臭”是可以被文学史承认的，抑或是有成为经典的审美价值的；什么样的“和臭”是对中国诗坛“笨拙”、“机械”模仿的结果？作出如此划分和判断的依据又在哪里？
从本书的叙述来看，王朝时代的汉诗被视作机械模仿，原因在于其内容多是应制，少有针对现实，或直抒胸臆的主题（61）。而本书的汉诗史观倾向于肯定日本王朝时代汉诗中抒情言志，符合“兴观群怨”的诗学品格的作品（24）。而这种价值判断是统摄全书的。比如，作者对奈良朝时期的宴游之诗评价不高，认为其“为文而造情”（98）。相反，平安朝前期那些体现着“文章经国”思想的现实主义作品则获得了较高的评价（118）。到平安朝后期汉诗总集《本朝丽藻》时，作者也强调日本汉诗人对汉诗讽喻和批判作用的忽视（272）。而五山时期的汉诗被认为有新意，主要是因为题材丰富，名家甚多（65）。
此外，这种汉诗观也决定了菅原道真成为本书最核心的典范作者。作者认为《菅家文草》与《菅家后草》两部诗文集中，写他人之未写，抒个人之真情的诗才是菅原道真有价值的诗学遗产。而为了说明菅原道真抒情诗的价值，作者在菅原道真的生平上铺陈了大量的笔墨。从其少年神通，到谪守地方，再到重返台阁，最后因小人谗言悲愤而终，菅原道真的个人经历可谓曲折。而作者尤其注意到人生的苦难对诗人的造就：“五年的谪居生活,使道真由诗臣进化为诗人”（325）

***** 近世东亚汉诗流变
《近世东亚汉诗流变》中的“日本汉诗的近世流变”一章，主要梳理了江户时期的日本汉诗发展史。江户时代的日本汉文学在整个日本汉文学史中具有重要意义，江户时代的日本汉诗更是其中颇具特色的一支。
由于研究对象集中在江户时代的日本汉诗，作者并未从整体上对日本汉诗史的分期作展开，而是将研究视野聚焦在江户时代的日本汉诗发展史上，从更为微观的角度剖析了近世日本汉诗史。
作者系统总结了中日学界对江户时代日本汉诗史分期的两种主流意见：三分法和四分法。其中，三分法描述了在该时期日本汉诗由尊唐到性灵的转向，而转向性灵之后，又有师法宋诗到学习清诗的变化；而四分法相对于三分法，更具体地阐述了江户时代日本汉诗主题和师法对象的变化。可以认为，四分法是三分法基础上的延伸。
而作者的分期方式，则首先关注到江户时代日本汉诗较长的繁荣期（1680-1829）。然后以此为中心，作者将江户时代的日本汉诗分为三期：繁荣期之前的为发展期（1603-1679），其后的为总结期（1680-1829）。（312）
作者分期方式有如下几点值得关注：
首先，作者尽管聚焦江户汉诗，但并未脱离对日本汉诗史的整体观照。不论是发展期还是总结期，作者都注意到它们在日本汉诗史上承上启下的关键位置。
其次，作者的分期方式较为完整地展现了江户汉诗繁荣期的诗风、诗学的特点和转向。由于学界普遍认为，江户时代的日本汉诗是日本汉诗史发展的最高峰，而作者对江户汉诗之繁荣期特点的突出，实际也是对从奈良平安时代以来，日本汉诗史整体的艺术巅峰的显现。

***** 总结
现有的日本汉诗史在书写的时间范围上有所不同，以下试分通史和断代史两类写法分别讨论它们在分期意识上的共同点。首先是《日本诗史》和《日本汉诗史》。这两部著作在分期上都注意到汉诗发展与本国政治、文教状况的关系。因此，它们的分期都有着以政治之治、乱作为标准的意识。同时，两部著作都对五山时期的汉诗评价较低，并都肯定德川幕府定天下、兴文教对本国汉诗发展的影响。其次是《日本汉诗发展史》和《近世东亚汉诗流变》。这两部著作分别选取了日本汉诗史中特色最为鲜明的两个阶段：汉诗发轫期的王朝时代与本土化特色显著的江户时代。它们对日本汉诗传统的分期，都强调描述某一阶段的日本汉诗人是如何受容中国诗歌和诗学思想的。


**** 从多种日本民族文学史中重估现有日本汉诗史的分期
日本汉诗是一种特殊的文体。它既是以汉字文化圈为中心的汉语诗歌传统的重要组成，又属于日本的民族文学。而这种同一性与差异性共存的双语环境往往被一些研究者所忽视。他们认为，对日本汉文学史的书写，并不需要观照日本上古时期的文化和原始形态，只从汉学输入日本谈起就好（日本汉文学史，43）。这种观点是值得商榷的。实际上，正如第二章所言，对日本列岛诗意识的认识是不能离开日本上古的宗教生活的。如果仅从字面意义去理解汉文学、汉诗，那么将会妨碍对其审美因素中民族底色的认识。日本汉诗史的分期也是如此。一方面，我们要注意到日本汉诗史的发展阶段和方向同中国诗歌、诗学传统的联系；另一方面，我们也不能忽视在这一过程中，日本汉诗同汉文学传统中的其他文体，以至于和歌、俳句等日本民族文学文体的关系。因为它们之间并非独立发展的，而是存在着客观的互动和交融。

本节之所以尝试站在多种日本民族文学传统中思考日本汉诗史的分期问题，即是站在整体的日本民族文学发展的角度，来审视日本汉诗在这一传统中的位置和，并以此为基础，尝试重估现有日本汉诗史的分期。需要注意的是，本节尽管以多种日本民族文学传统为基点，但并不涉及到对具体作家、文本的受容分析。具体来说，本节将会从以下着手进行分析：在不同的日本汉文学史、日本诗歌史和日本文学史视域中，日本汉诗分别处于什么样的位置？而通过对这一问题的分析，本节最终得出围绕重估现有日本汉诗史分期的两个结论：第一，应当重视对五山和明治时期汉诗价值的重估；第二，应当注意到“诗”的概念在近代日本文学史中发生的衍变，以此重思日本汉诗本土化的历程和意义。

***** 日本汉文学史中的日本汉诗：对五山和明治汉诗的重估

日本汉文学史的分期同日本汉诗史的主流分期并无差异。猪口笃志的《日本汉文学史》是目前涉及时间段最广、对汉诗相关材料的引述相对最丰富的日本汉文学史，它采用的分期方式是传统的朝代模式。此外，亦有以冈田正之《日本汉文学史》（东京共立社，1929年）等为代表的日本汉文学史著作，将汉文学创作主体身份的变化作为日本汉文学的分期依据。

从两种文学史的书写对象上看，日本汉文学史对“何者为汉文学”的定义似乎不如日本汉诗史明确。以猪口笃志的《日本汉文学史》为例，其中将外交国书、《十七条宪法》为代表的律令制国家制度文本，乃至《日本书纪》等汉文史书悉数纳入其文学史视野，呈现出较为丰富和包容的文学观念。而绪方惟精专用一节阐述平安时代明经家学的各个流派的谱系、训点经书的传统等，强调经学甚于文学。由此可见，汉文学的定义较之汉诗是更为宽泛和不确定的。在这样的情况下，日本汉诗的发展脉络应当是日本汉文学史中较为清晰的一支。这也凸显了日本汉诗在日本汉文学中的特殊价值。从猪口笃志和绪方惟精两部日本汉文学史通史的选例就可以看出，汉诗占所有文体的比重最大。

而与现有日本汉诗史不同的地方在于，日本汉文学史对五山和明治两个时期的评价相对较高。

首先是五山时期的日本汉文学。《日本诗史》就感慨，尽管五山禅林的文学相较于平安时代后期的汉诗文而言，因为引入了宋元诗风而别有新气，但也是“氣運盛衰之大限”。日本汉诗人对五山诗僧的评价也不是很高，如《诗律兆》：“聲詩之道墜在浮屠氏”（1006）。

但在日本汉文学史的书写中，作者却往往肯定五山时期承上启下的作用。猪口笃志一书中所收录的汉诗人、作品数量，五山时期与上古至平安时期相比开始增多。同时，该书还注意到武家、大名等所谓“山外的诗人”。通过“山外”对“山内”的补充，作者呈现出五山汉诗创作主体身份的多样化，以及汉诗主题的丰富性。

绪方惟精则直言：“在日本汉文学史上，（五山时期）占有最紧要的位置。”（126）相对于现有日本汉诗史对江户时代汉诗评价颇高的写法，绪方惟精反而认为这一时代的日本汉诗多是经学的附庸。至于背后原因，应是当期的汉诗作者多是儒者和士人的缘故。回到其对五山汉文学的评价。尽管五山禅僧有很多人工于四六文，但书中所录汉文学作者，绪方惟精皆强调其汉诗的才能。而从五山禅僧诗作的特色来看，绪方惟精看重的有两点。其一，他高度评价中日僧侣交往带来的宋元诗风。这种诗风有别于平安后期贵族文学的游戏化倾向。其二，他意识到，由于和宗教生活密切相关，五山禅僧在汉诗创作中必然充盈着以个人为中心的内观，所以摆脱了对中国诗歌亦步亦趋的状态。从绪方惟精对五山汉文学的评价中，可以重新发现这一时期汉诗的价值。

至于明治时期的日本汉诗，当前的日本汉诗史均对幕末明初的日本汉诗有着较高的评价。但对明治以降的汉文学整体发展态势，现有的日本汉诗史基本认为，随着西学在日本的影响越发深入，包括日本汉诗在内的日本汉学，其价值受到批判。尽管在此后，儒学思想随着与国粹主义的结合而复苏，但这时候的汉学已经转向为一种皇权制度为中心的国家意识形态（日本中国学史稿，128）。在这种情况下，汉诗失去了思想上的丰富和活力。

以上观点是将汉诗在内的汉文学放在日本近代思想转向的脉络中考察的。然而，猪口笃志引述日本近代诗人大町桂月的说法，鲜明地反驳了这种成见：“到了明治时代，西洋的文学和思想快速输入，这不足为奇；小说的写作面目一新，亦不足为奇；新体诗的勃兴也是如此。只有尚且存在的汉诗反而兴盛了起来。我国诗人的诗艺在这段时期也达到了不可思议的程度。汉籍进入日本两千多年来，还没有出现过这样的盛况。”（507）通过猪口笃志对这一观点的支持分析，可以看到，他十分重视私塾、新闻以及杂志的作用，这些因素分别从教育和传播的角度解释了明治汉诗是兴盛而非衰弱的原因。这种论证逻辑超越了西学思想对包括汉诗在内的汉学的冲击，而是从日本的教育和媒介发展的历史中寻找明治汉诗兴盛的原因。而这种兴盛的态势是在整个日本汉诗、汉文学发展的脉络中成立的——相对于古代和近世，西学引发的教育、媒介的改革和发达使得汉诗的创作和传播速度达到了前所未有的高度。从这里可以看到，日本汉诗史分期的另一条线索，即与汉文教育、媒介出版之历史的同步。绪方惟精也认为，进入明治时代后，汉诗“盛大而有势力”（213），其发展态势超过了汉文。从两位汉文学史家的阐述中可以看到，日本汉诗是日本汉文学中最核心的文体。

日本汉文学史家对五山、明治两个时期的汉诗之价值的重新发现，对日本汉诗史的分期而言有着怎样的启发呢？首先，两位作者对五山时期汉诗、汉文学的重视，凸显了他们的线性进步的文学史观。从日本汉文学的宏观发展上来说，不论是诗人主体身份的多样化、新诗风的建立，还是和习的产生，五山时期的汉诗都是一个承上启下的关键阶段。在这种文学史观下，五山汉诗是整个日本汉文学不断完善、演进的过程中的一个环节，并不是以往观念中的日本汉诗史中的低谷。

其次，是两位史家对明治时期汉诗的盛誉。这种高度评价一方面依然服从于线性进步的文学史观，特别是猪口笃志从教育和媒介发达的历史观照明治汉诗在整个日本文学史中的位置；同时，从汉诗与汉文的关系来看，汉文自身文学功能的衰退更衬托出明治汉诗在当时汉文学中的地位。绪方惟精认为，明治汉诗“盛大而有势力”（213），其发展态势超过了汉文。其原因还是在于，进入明治以后，汉文转化成了所谓的“训读体”（読み下し文・文語文），从功能上来说，则是从古典教养转向为实用文体。“训读体”混杂了汉文、和文与西文的词汇和语法，例如是在评论文章中，为了表现实验的科学性，常使用西文的比较级（飛山純子，《明治普通文の研究》，《日本文学》，1964年，第23期，第74-85页）。在汉文发生转向的同时，汉诗的形式特征、作法规范等相对固定，因此未如前者那般受到结构性的冲击。

然而需要注意的是，这样一种线性进步的文学史观，其发展究竟有无限度？以猪口笃志的《日本汉诗史》为例，江户时代的汉文学作家是整个日本汉文学史中数量最多，身份也最丰富。更重要的是，该时期的汉文学历经流派的变化，呈现出百家争鸣的活泼局面。然而与之相比，明治时期被收录的诗人大多是馆阁僚臣，诗人身份的多样性较江户时期的是萎缩的；而从诗的表现内容上来看，随着汉学和国粹主义的结合，明治至昭和时期的汉诗也呈现出缩窄的态势。在猪口笃志看来，国分青崖“诗宗”地位的确认，使得当期其他诗人在其面前莫过于“蜉蝣撼树”（599）。因此，即便是在线性进步的文学史观下，这种在各方面逐渐衰落的趋势也是不能被否认的。




***** 近代以后“诗”的概念的衍变 - “诗”的终结 - 方向/为什么？

日本诗歌史是日本文学史中的一个体类，是以专门的文体为结构进行组织的。于是，用日本诗歌史和日本文学史的视野去观照日本汉诗的分期，首先便是要分析日本诗歌的范畴，以及日本民族文学的精神底色是什么，而“诗”在其中的位置又发生了怎样的变化。以《日本诗歌史》和《日本文学史序说》两个文本为中心，我们会发现，“诗”这一概念以近代为分界发生了衍变——近代之前，诗即是现代学界所认为的日本汉诗；而进入近代，诗则成为新体诗的专门指代，在此之前的诗也同时被冠以“汉诗”的名称。

那么，这种衍变是如何被观察到的？在这一部分，本文将观察日本汉诗这一文体在日本诗歌史和日本文学史中的消失点，并讨论这一消失点的意义。首先，从物质载体的有限性看，任何文学史都是有其终点的。其次，文学史书写中的一个核心任务就是依照某种文学史观，构建一个有限的时间范围。而这种被建构的有限的时间正是文学史家对史料进行分期的前提。只有在文学史家规定的时间跨度内，文学要素运动中的此消彼长才能够被观察到。综上，文学史中普遍存在着消失点。而对于“诗”的概念衍变的分析，亦是以消失点为凭借，去观察对此概念的旧的阐释的中顿、新的阐释的生发，以及从前者到后者的转化所遵循的逻辑。

《日本诗歌史》将汉诗与上古歌谣、和歌（连歌、狂歌、川柳）、俳句、近代新体诗统称为“日本诗歌”。该书中最后一次提到汉诗，是在“五山文学体制内外的诗”这一章。作者指出，五山汉诗发展到江户时代初期之前，在语言和内容上出现了日本化的转向（286）。而这种转向的核心在于世俗化、庶民化，被认为是日本民族文学的底色所在。将五山汉诗视作中世日本庶民文艺的一部分，标志着汉诗进入到日本民族文学传统之中。而此后，以日本本土之和歌为起点生长的连歌、俳谐和俳句依次登场，并作为日本文艺世俗和庶民化特征的代表，成为日本诗歌史的主流。于是，日本诗歌史的中世便成为了日本汉诗在这一脉络中的消失点。

加藤周一也反映出与《日本诗歌史》相类的观点，即日本汉诗在日本诗歌、文学史中的消失，意味着其进入到了日本民族文学传统之中。而他的日本文学史书写中，这一消失点幕末明初。

为了理解这一节点的选择，首先要说明加藤周一眼中的日本民族底色是什么。而对这一问题的回答说明了汉诗日本化的方向。在他看来，日本文学发展的形式，并非在消解旧的要素的基础上用新的因素取代，而是对旧的因素加以补充（4）。于是，以日本本土的世界观、文学观为基底，日本汉诗是中国文化日本化的产物。而所谓日本化的倾向，旨在于对此岸世界，包括现实生活和个人情感的具体写实。于是，他的《日本文学史序说》体现出这样一种分期观念：以每个阶段日本对于外来文化的本土化受容为依据，将日本文学史分为四个转折期：平安时代（律令制国家日本化为摄关制）；镰仓幕府时代（禅宗的日本化）；德川幕府时代（朱子学的日本化）；幕末明初（町人文化和西方思想的日本化）。

在这种文学史观下，由于其主要是通过诗的形式对中国的仪礼功能进行模仿，所以《怀风藻》获得的评价并不高，“既不是他们的感情生活的表现, 也不是他们的思绪的结晶。”平安时代的汉诗也是如此。作为官学教养的汉诗文属于“公”的领域，与和歌所代表的“私”的——即个人的、现实情感的领域是对立的。而对于五山时期的禅僧文学，加藤周一也并未施加过多的笔墨，相反，着重突出禅僧这一群体之外的诗人，如一休宗纯的写作。最后，在近代之前，十八世纪的江户汉诗，特别是以菅茶山之诗作，因为表现出此岸世界的写实风格，包括对日常环境和青楼恋情的描写（200）而进入到其文学史的视野中。

可以看到，加藤周一对日本汉诗的书写，以日本本土世界观为线索，日本汉诗史中的茫茫材料中那些符合现世的、抒张个人情感的诗被保留了下来。而这些诗在以往的日本汉诗史、日本文学史中是作为边缘的、支流的样式被文学史家加以呈现的。以《近世东亚汉诗流变》对菅茶山诗的评价为例，作者强调其感时忧怀和写景之诗，并将其视作近世日本汉诗折衷诗风的代表（408-409）。而这种选诗的眼光，体现的是中国诗学评价中对诗歌言志述怀和吟咏自然的重视。而在《日本文学史序说》的写法中，对菅茶山写景诗的评价，则是从其对周边生活世界的写生出发的，这亦符合加藤周一对日本本土世界观的描述。两者之对比凸显出不同的文学史观和评价视角。于是，从日本汉诗在这部文学史中的位置来看，日本汉诗的分期体现的是其日本化的过程。在这一过程中，中国诗歌传统中的文化内核也从清晰转向模糊，直至与本土世界观融合。十八世纪那些表现出町人趣味的江户汉诗，正是这一过程的终点。

总的来说，日本汉诗在日本诗歌史和日本文学史中的消失点，就可以看作是日本汉诗的精神内核完成了从汉文化向本土世界观的转向。那么如何看待以上两种文学史书写中消失点的不同？从日本诗歌史来看，江户时期本土化意识最强烈的诗歌形式显然不是汉诗。若与日本汉诗史参照，即可看到当期日本汉诗中，其尊唐、崇宋乃至折衷的诗学思想才是主流。相对地，由于江户中后期汉文素养的大众化，使得当期的日本汉诗人能够较之前的诗人更为熟练地运用汉诗的形式书写日常的、具体的世界。而这种现象是具有特殊意义的——古典汉语诗歌形式与本土世界观的对立统一在当期达到了顶峰，于是，这些汉诗人的作品在加藤周一的文学史书写中是具有典型色彩的。     
       
而这种以本土化为终点的演进，使得日本汉诗成为了日本民族文学传统的一部分。从日本诗歌史的描述来看，随着西方文学输入日本，对西方诗歌的翻译实践使得日本的“诗”与“歌”与西方舶来的“诗歌”（poetry）发生了互动。明治时期的汉诗人石川鸿斋曾在其《诗法详论》中所展现的观点，便是西方文学话语进入后，日本学人对“诗”的认识发生改变的一个例子：“詩其可廢歟?曰：否，萬國皆有詩。或曰：凡物必有則，妙用其則，使人感動者，謂之美術繪畫也。雕刻也，歌詩也，音樂也，皆美術也。……今歐、米諸國，美術日盛，互相誇張。我素富于美術，不可不益修之以壓彼也。”（5833）这里的“诗”，即指的是作为文体的诗。于是，“诗”的存在不再是某一国家、某个民族所特有，而是世界上每一个国家所共有的特质。日本有诗，中国有诗，欧美亦有诗。凭借着这一论证，石川发现了日本汉诗与世界文学，抑或日本与以欧美为代表的世界万国对话的可能。此外，作者亦将诗归类于美术中。而所谓美术，就是“使人感动者”。从幕末到明治，特别是随着文明开化的展开，日本对欧美各国的认识已经深入到文化艺术的诸方面，同时，欧美的学术体制也被日本受容。“我素富于美術”，不仅仅是作者按照西方话语重审自身的结果，更重要的是，其背后“修之以壓彼”的思想中体现着追赶欧美，乃至超越欧美的愿望，是福泽谕吉“脱亚入欧”论（日本通史，403）在文学艺术上的一种阐述。

图片

如图可见“诗”的衍变：在近代以前，“诗”和现在的“汉诗”同义；而进入近代，“诗”的范畴涵盖了汉诗、和歌、俳谐、俳句，乃至新体诗在内的日本诗歌。也就是说，“诗”的外延扩大了。

更重要的是，“诗”的衍变意味着“汉诗”这个表述实际上是一个相当晚近的发明。根据美国学者拉宾诺维奇（Judith N. Rabinovitch）的考辨，“汉诗”一词最早出现在1877年出版的白井篤治的《汉诗作法幼学便览》。而第一个将“汉诗”用直译表述的则是日本近代文学家国木田獨歩。（NO Moonlight in My Cup，4）.


在欧美学者的日本文学史书写中，由于存在着术语翻译的问题，因此能够更明显地观察到西方文学话语中的“诗歌”是怎样观照日本汉诗的。以下是《剑桥日本文学史》一书中的术语对译：

表格

可以看到，在作为文体的诗歌的观照中，汉诗被明确划归为日本文学。它不再是“以唐诗为代表的中国古代诗歌影响并繁衍到海外的最大一脉分支”（马歌东著. 日本汉诗溯源比较研究. 北京：商务印书馆, 2011，13）。日本汉字作为其日本民族语言书面表记的核心部分，也成为了本民族文学的风格载体。




***** 被排斥的日本汉诗：本土中心文学史观中的日本汉诗

而在一些日本文学史家的眼中，作为外来文化产物的汉诗和本土民族文学是完全对立的。在鲜明的本土中心意识下，汉诗基本被排除在了日本文学史之外。

西乡信纲的《日本文学史》中，汉诗只出现在奈良和平安时期。汉诗作为外来文化的产物之一，而日本汉诗人的创作则被视为受到了中国文化的“殖民”（46）。于是，相对于“卖弄学识”的汉诗，和歌则象征着本民族的文学传统，能够抒发歌人的真情，因此具有无限的生命力。而汉诗作为文学，则是昙花一现（47）。

古桥信孝的《日本文学史》则肯定了汉诗在早期日本本土文化发源中的位置。在诗歌史的部分，汉诗惟一的功能，是为和歌的书面表记提供符号的支撑。以大伴家持有为代表的日本歌人多转向音假名进行创作后，作为与和歌对立的文体，汉诗在这部文学史中也就不再能看见。

小西甚一《日本文学史》也是基于对汉诗的正面影响进行阐发的。他认为，以敕撰三集为代表的汉诗总集，将中国六朝的诗风带入了和歌。而和歌正是因为吸收了汉诗的表现方式，才最终达到了与汉诗相提并论的阶段（见48）。此后，日本的诗歌史便依循着和歌、连歌、俳谐、近体诗的脉络发展，再也不见汉诗的影子。

谢六逸（1898-1945）编著的《日本文学史》（北新书局，1929年）则是基于学习近代西方文明的特殊文学史观，对日本汉诗加以排斥的。该书是近代中国集中译介日本文学的先锋之作。本书从上古叙述到近代，编写方式以明治时代的文学为分界线——明治前以作品为纲，明治及以后则以文学团体、流派为主轴。之所以作出这样的区别，是因为作者考察了日本文学与世界文学潮流的互动，认为日本文学在近代以前没有派别之分。这种文学史观是近代西方文艺理论影响的结果。也是在这种文学史观下，作者尤其看重近代日本文学的“世界价值”（欧洲文艺潮流），并呼吁时人对日本文学加以关注。于是，在这本日本文学史中，日本汉诗，以及汉文学本身，甚至是汉字，价值都受到贬低。在本书每个分期的“诗歌”部分只见和歌而不见汉诗。而汉字和日本固有语言的关系则是汉字压迫后者，并导致了后者被消灭。
 
第一章 对现有日本汉诗史的回顾
本章的主要内容，是评述现有的日本汉诗史著作。在这一部分，选取了现有日本汉诗史的经典著作。它们分别是：江村北海的《日本诗史》、菅谷军次郎的《日本汉诗史》、肖瑞峰的《日本汉诗发展史》以及严明的《近世东亚汉诗流变》。
《日本诗史》是首部对日本汉诗发展历程进行系统总结的著作。它阐述日本历代诗学的变迁，并注重对当时日本汉诗创作情况的总结。
《日本汉诗史》则是近代以来唯一一部以日本汉诗史为书写对象的专著。此书完整勾勒了日本汉诗自产生以来的历史发展。与一般文学史大多仅包含作家、作品批评不同的是，此书着重构建了与日本汉诗发展有关的制度史。
中国的日本汉诗研究界虽然尚未有专门的日本汉诗通史著作出版，但在断代文学史的书写中，已经出现了两部重要的著作。《日本汉诗发展史》和《近世东亚汉诗流变》分别建构了王朝时代和近世日本的汉诗理论和实践脉络，呈现出日本汉诗史上两个重要时期的状况。
本章在评述以上日本汉诗史著作时，注重对两个基本问题的回答：什么是日本汉诗？日本汉诗发展动力和演进逻辑是什么？对这两个问题的解答，反映出每个作者的日本汉诗史观。具体来说，第二个问题可以通过对每本著作的文本进行细读作具体的阐述；而相对而言，第一个问题，即对“什么是日本汉诗”这个问题的解答，可能并不会显明地出现在文本中。它需要以每本著作所采用的参照系作为起点观察。
最后，有关现有日本汉诗史著作的分期，将在第三章专门论述。





 
第一节	《日本诗史》
江村北海、《日本诗史》及其研究概况
江村北海（1713-1788），名绶，字君锡，号北海，通称传左卫门。其出身藩儒世家，长于诗文，是诗社赐杖唐的盟主。晚年在京都开设対梢馆，传授儒学。其著作有《日本诗史》五卷、《授业编》十卷、《北海诗钞》八卷、《北海文钞》三卷。
江村北海的《日本诗史》是日本第一部具有诗史性质的诗话著作。该书刊行于明和八年（1771年）。根据日本《国书总目录》，该书共五卷三册。唯一的写本藏于日本宫内厅书陵部。而版本则分别藏于国立国会图书馆、内阁文库、静嘉堂文库、庆应大学图书馆。其中，该书的活字本可见于《日本儒林丛书》第三册和《日本诗话丛书》第一册。尽管有这些版本，但是该书在刊行后就没有再版。
《日本诗史》起稿于明和三年（1766年），成稿于明和五年（1768年）。原本计划出版十卷，但因为经费原因，只出版了现存世的五卷。据江户狂歌三大家之一大田南畝（1749-1823）记载，天明八年一月三十日（1788年3月7日）在京都发生的特大火灾中，《日本诗史》的原版被烧毁。
现存的五卷中，卷一阐述了日本诗学变迁的概略，时间从白凤时代（654年-710年）到庆长末年（1614年）的朝廷文学。卷二在时间上与卷一相同，内容分为十二个部分，分别论述武士、医生、隐者、僧侣、闺阁等诗作。卷三记载了元和元年（1615年）之后的文学情况。所记载的作品以京畿之地为创作中心，另有日本其他地方的文学。卷四同样记载了元和元年以后的江户文艺，以林凤冈（1645-1732）、木下顺庵（1621-1699）及其门徒为代表的诗作为中心。卷五顺承着第三、第四卷对京畿以外地方文学的记载。全书的重点在卷三及以后，也就是元和年之后的文学。
《日本诗史》在日本汉诗研究领域具有重要的学术价值，具体体现在：
一、它第一次系统总结了日本诗学变迁的情况，是日本江户时期汉诗学的代表作品。
二、它注重总结元和元年（1615年）起，即丰臣氏灭亡，日本长时段和平状态开始之后的日本汉诗创作情况，保留了当时相当多的史料。值得注意的是，江村北海在《日本诗史》以外又有《日本诗选》十卷补遗一卷，共七册。其中采集书目157种，除了别集以外，还有以幕末新出版为主的各种总集；而收录的诗人数量高达520人，其中收录5首以上的有75人。
三、其中提到的“日中时距两百年”、“气运”等概念，同时观照了日本汉诗与中国文学的关系，以及日本汉诗自身的发展和演进逻辑，具有相当的视野。
目前国内学界对《日本诗史》的研究并不完全。其中，《论〈诗薮〉对〈日本诗史〉的影响》一文详实考察了江村北海《日本诗史》在形式、内容和诗歌审美方面对明代胡应麟《诗薮》的继承。作者提出，《日本诗史》的特色之一，就是对中国传统史书体例的运用，呈现出《日本诗史》中对史学传统的自觉运用。此外，“气运”的诗学概念被江村北海用以解释日本汉诗的发展动因。同时，“气运”也被用以论述汉诗的功能、中日两国古典诗传统的关系等日本汉诗史书写中的重要问题。对《日本诗史》体例和“气运”说的分析，突出了《日本诗史》的诗史意识。
在诗史意识中，本文作者尤为强调江村北海提出的：日本汉诗发展与中国历代诗歌“二百年”的时间差的意义和对日本诗学界的影响。这是日本汉诗史书写中的一个重要命题，即日本汉诗与中国古典诗歌是两种不同历史时间中的产物。其中原因，固然有汉籍向域外传播和日本诗人阅读、接受汉籍之速度的影响。而更重要的是，两种不同的历史时间所隐含的前提是，日本汉诗自有其本体与演进逻辑。一些日本汉诗研究中的以中国古典诗歌为绝对参照系，单纯视日本汉诗为对中国古典诗歌模仿、接受的结果，实际上也是忽视了上述重要的前提。
如此，以两种不同的历史时间为构建日本汉诗史的前提，则会对另一个表述——“本土”产生影响。依照《近世东亚汉诗流变》一书的说法，近世汉诗人开始产生明确的本土意识，其创作也展现出鲜明的本土色彩 。可以认为，此处的“本土”指的是有别于中国古典诗歌传统的实践。那么，近世以前的汉诗创作如何？以日本汉诗为例，既然其与中国古典诗歌根本处在不同的历史时间，那么“本土”的时间和文脉显然是自日本汉诗发生起就存在，“本土意识”、“本土色彩”也并不是凭空出现和明确的。对“本土”的重新思考，或许可以为日本汉诗史的书写，特别是对早期日本汉诗的评价提供新的标准。
此外，格律声调的审美标准、风雅和日本传统“哀”美学的融合，对《日本诗史》这些方面的论述，则提示出日本汉诗史建构中的审美价值和经典选本的问题。什么风格的诗作能够代表日本汉诗的整体风格？江村北海的答案是：深郁厚笃、委婉细腻。那么，新的汉诗史的建构即要在更长的历史区间内作出新的解释。
 
《日本诗史》的诗史观
《日本诗史》开宗明义地规定了其题名“诗史”的涵义：

“ 是编论诗以及人，非传人以及诗，即巨儒学苟无篇章存在者，亦不论载焉。此所以名诗史之义。”（凡例）

江户时代在日本汉文学史上被称为“儒者文学的时代”（绪方惟精，日本文学史，156；猪口笃志，日本汉文学史，231）。相对于十八世纪才出现的专门的诗人阶层，儒学者在江户时代之初就有着较为独立的地位。藤原惺窝、林罗山等大儒在京都的积极活动，以及时任将军家康不限制清原氏、中原氏两个明经家门以外的学者对经书进行加点、阐释，一些大儒的讲学遂招徕了许多倾心儒学的人士，到最后发展成为颇有影响的门派。
但《日本诗史》所透露的观念，并非盲随时风追捧大儒，而是以诗为纲目，突出了诗在诗史编撰中的中心地位。而这种书写上的尝试，除了和当时风气有所相对外，还体现了一种将文学和经学进行分离的努力。有学者总结过江户时代汉文学的一个显著特征，即经学和文学处在没有分化的状态，对汉文学的研究亦无法摆脱与经学的纠缠。《日本诗史》显然是逆潮流而行的特例。
这种观念体现在其书写中，则并不绝对因为某位人士诗才不足而不录其名。相反，江村北海采取的策略是，详录某人官职、世系，而后道其诗才不足。如评价平安中期的贵族和公卿：“文章博士为长，大学头在高。并有《水乡春望》七绝，俱非佳境。” 、“庆滋保胤也。贺阳丰年也。朝野鹿取也。当时甚有声誉，而遗诗皆不满人意。菅野道真撰《续日本纪》，文才可想而诗殊不谐。” 从这种“声誉-诗才”，甚至“文才-诗才”对立的结构中，可以看出《日本诗史》所具有的，对“诗”这一文体的自觉意识。
而这种自觉意识体现是诗史编撰者的独特眼光。不难看到，江村北海在《日本诗史》中所做的，并非简单对日本汉诗发展史的回顾，而是去发现，并建立一种新的秩序。从以下评价中可以看到《日本诗史》对世间常识的批判：“内大臣实隆（三条西实隆），号逍遥院。因课子弟誊写六经及《史记》、《汉书》等，世知公为和歌巨擎。而不知有文学。故揭而出之。”（15）
为何江村北海能够揭示常识以外的现象？上文提到，江户时代汉文学的研究和经学密不可分。而在这一时期，汉文历史，尤其是《本朝通鉴》、《大日本史》等正史的编撰也是日本汉文学史家考察的重要对象。这些历史文献的成立需要儒学者具备丰厚的历史学养，来对现有的文本进行整理和批判。此外，除了儒学者，这种以文本批评为核心的方法也被广泛运用到国学者的学问思考中间。因此可以认为，彼时日本社会中，具有汉文素养的学者对于文献中的历史性知识是有着较为自觉的追求的。
而这种自觉的追求，在《日本诗史》中有较多的例子。如：

“左卫门尉周光，《冬日山家即事》虽有小疵，自是胸臆中语，古平淡中反觉有味。史称周光宦仕不達。……余阅无题诗集。载周光诗多至百首。大抵山题咏，则史言诚是。” 

“大伴池主有上已诗。见《万叶集》。大伴氏上有《观渤海》，贡使入朝七言律，见《凌云集》。渤海朝贡始未具见旧史。后辽太祖灭渤海，改为东丹国。以长子倍为东丹王。其地濒北海。明时名哈密者。” 

可以看到，《日本诗史》的文献基础，除了历代诗家诗集，还有涵盖人物传记乃至地理等诸方面的历史材料。江村北海对这些材料的使用，除了对诗人生平、诗集作品，乃至诗作中所涉事件与历史作相互印证，证明其真实性外，也体现出当时儒学者综合性的汉文学养。
《日本诗史》的本土意识
尽管我们可以看到《日本诗史》中自觉的文献批判意识，但若细读文本对历史材料的运用，则能发现在这种意识背后的，对“我邦”的强调。
整部《日本诗史》，是经由“阿直岐、王仁来日献书”这一事件展开的。一般汉文学史，乃至汉学史的研究，都十分强调这两位渡来人在汉学传入日本时所起到的作用：首先，《周易》、《论语》、《孝经》等，构成了日本最早接触到的汉文经典，标志汉字开始系统传入日本；其次，自继体天皇开始，百济会定期献上五经博士，汉文化于是有了稳定的输入来源；此外，渡来人自此以后长期在朝廷担任史官或博士，成为日本的一个重要氏族。
那么，《日本诗史》是如何展开这一事件的呢？对阿直岐和王仁两位博士来日的时间，江村北海的记述和一般史书记载并无出入。而值得注意的是，《日本诗史》提到王仁在仁德天皇即位迁都之时，献上了所谓的《梅花颂》。江村北海认为这是“三十一言和歌”。
但同时，《日本诗史》亦记载了对于这段史料的质疑：王仁是外邦人，怎么可能会作和歌？“距今千有四百年，载籍罕传，其详不可寻而知也。”可见江村北海自己也认为这段史料过于久远，可信度不那么高。
然而，他仍旧采纳了这短短数语，并针对上面的质疑给出了自己的回应。他认为有两种可能：一、可能是当时的史臣翻译了王仁的意思，写成了和歌；二、王仁归化已久，已经熟悉了日本的语言，向别人学习，而后作了和歌。
这种做法和《日本诗史》正文中所体现的文献批判意识似乎有所出入。一方面，北海自己也不确定史料的来源是否可靠；另一方面，他将这模糊的史料放在了卷首——“献和歌”作为一个象征性的事件，被归在了王仁的名下。
这种意识上的内在矛盾意味着什么？
从《日本诗史》引征的史料来看，江村北海并没有说明这三十一言和歌是有史以来的第一首和歌。而其中所要传达的意义要从两方面来看。一方面，在《日本诗史》所载文献的序列中，这篇和歌出现在日本最早一批输入的儒家经典之后，同时位于大友皇子所作五言四句的汉诗之前，说明日本的和汉文学在诞生之初并未出现显著的差距。另外一方面，作为渡来人的王仁献和歌于天皇，象征了渡来群体的归化，而归化的前提是：接受归化的这个民族已经有了相当程度的文化自觉。
接着看江村北海对于这段史料的回应。
一、可能是当时的史臣翻译了王仁的意思，写成了和歌。这首先意味着当时的和歌已有较为固定的体式，包括文字的形态、发音以及和歌的形式都有了一定的规范。其次，按照这种说法，王仁并非《梅花颂》的原作者，但江村北海依旧肯定了王仁在其中的作用。这说明王仁的功能很重要。按照本编的说法，他不仅是推动汉文化在日本上层传播的重要人物，更是第一个将和歌带到天皇面前的人——这意味着开启了和歌进入贵族文化的可能。
二、王仁归化已久，已经熟悉了日本的语言，向别人学习，而后作了和歌。这种理解除了如之前所述，证明了和歌在当时具备一定体式以外，还说明，在《日本诗史》对汉学传来这一事件的构建中，并非汉学的单方面输入、影响日本，还有和文化的反向作用。在这里，王仁这一符号，同时具备了汉学传播和受容日本本土文化的功能。

《日本诗史》中的“我邦”意识还表现在对人名、地名的命名规定上。凡例中提到：

“我邦多复姓，操觚之士，或以为不雅驯，于是往往减为单姓，不翅代北九十九姓，其义得失，姑置之。是编多完录姓氏，要使后人易捡索而亦不尽然者，又说也。余已载诸《授业编》，因不复赘。地名亦然，远江州称袁州，美浓州称襄阳，金泽为金陵，广岛为广陵之类，于义有害，是以一槩不书。”

日本人复姓改为单姓，有的是出于对典雅文辞的考虑。例如上文提到的平安时代的贵族庆滋保胤，就在《江谈钞》中被称为“庆保胤”；同时期的贵族大江以言则在其中被称为“江以言”。《江谈钞》是一部说话集，其记录了当时中纳言大江匡房的谈话，反映出平安时代贵族社会的不同侧面，因而从中可以看出当时的一些风气。从“是编多完录姓氏”的做法可以看出，江村北海是倾向保留原来的复姓的。只是由于改为单姓的做法已经成为一种风俗，所以在此，北海对人名改动所造成的影响采取悬置的态度。
而在这段话中，针对时人用中国的地名取代日本令制国名的做法，江村北海的反对态度是很坚决的。《日本诗史》卷五所涉及到的令制国，以京都和江户为端点，主要集中在东海道区域；余下的令制国，最西端在山阳道的备后国，最南端是南海道的阿波国，最北端位于东山道的陆奥国，最东则延伸到常陆国。
而有关这些令制国的地理位置、风土人情的知识，有的是江村北海从别人那里听说的，比如陆奥国：“陆奥大国，大小藩府，无虑二十，而仙台为大。余闻藩中以儒业世禄者，有数十人。而其文藻无所闻见。” 但更多的是他从亲身的见闻中得出的，如在越中国的游历：“客岁之春，佐伯季雘游京数，过余家。闻余好山水，盛说立山奇绝，遂以秋九月，余游富山，并五十日。” 又如其与各地好诗者的交往：“然客岁余游越中，高山人某，因富山渡边公庸，请诗于余。斯知其土人。”；“备中文艺，余未考之。近惣社邑人，藤野如水，游京师，数过余家。为人短小黑瘦，口讷讷焉。见之，如无才者。会晤再三，渐测其所蕴，殊为该博。” 
从以上来看，《日本诗史》中充满了对京畿、江户以外的地方的关心。

《日本诗史》的“我邦”意识，亦体现在对日本汉诗与中国诗人、诗作之间关系的表述中。
卷二提到了两位日本僧人。释智藏曾在唐高宗武德年间前往中国，是第一个诗作见诸日本古代汉诗选集的僧人。但北海认为其诗“并无可采”。另一位僧人辨正也曾到过中国，受到唐玄宗赏识，并与盛唐诗人交往甚密。而其诗虽然受到盛唐诗人的润色，但北海认为“绝无可佳者。可谓空手自玉山还。” 
这两位僧人从履历上看，可以说是日本僧人作诗的先驱者，但《日本诗史》对他们诗作的评价显然不高。而对于评价中所提到的，两位僧人共同的赴唐经历，北海的态度是暧昧的。尤其是辨正，说他“空手自玉山还”——北海一方面承认了盛唐诗的地位，另一方面否认了盛唐诗人润色过的辨正诗作的艺术价值，可见他并不赞同对盛唐诗的一味推崇。
除了王朝时代日本诗人前往中国学习以外，还有明末清初来日本避难的中国文人。《日本诗史》卷三记载了其中的双向互动。
据《日本诗史》，明朝人归化日本，又闻于诗者有元赟、朱舜水、林荣、何倩、顾卿和僧独立。其中，元赟的诗才最受北海赞扬，但也不过“间有佳者”。而林荣、何倩、顾卿的诗作“鄙俚最甚”。
值得注意的是，《日本诗史》在这一部分还提到了当时一位名叫大高坂季明的儒者与上述归化人的往来。对于大高坂季明，江村北海认为他“博览而有大志，最研理义”，给予肯定。林荣、何倩、顾卿三人对大高坂季明的诗，也赞赏称：“我辈来贵国，视数家文章，虽各有所长，然或未谐，章法句法，唯足下所作，尽合规矩。……足下文章，意深语简，韩柳欧苏无过。” 但江村北海以为，这三人的话不过是吹捧，但季明信以为真，于是其诗“遂欠精细工夫”，其人“深惜为三人所误也”。
此处的叙事实际构建了两组人像。第一组是以大高坂季明为代表的，以汉土诗人的评价为唯一标杆的日本人。第二组是明末来日的中国诗人，无论是诗才还是论诗的眼光，都为北海所不屑。虽然我们无法确切地从这里获悉北海对当时中国诗坛的看法，但他在后文中所提到“日中时距两百年”的差距，在这些归化的中国诗人身上已经无法体现。总而言之，在这段叙事中，迷信汉土的日本诗人终将误入歧途，而言过其实的渡来诗人则消弭了中国诗相对日本汉诗的优势。


 
本土意识的展开和成立：日中两百年和气运说
《日本诗史》对于“我邦”意识的展开，是通过“日中汉诗两百年时距”和“气运说”进行的。而这两个诗学现象的提出，显明了《日本诗史》的汉诗史观。
所谓“日中汉诗两百年时距”，指的是日本汉诗的发展较中国诗歌要滞后两百年。对这一规律的论述出现在《日本诗史》卷四：

余谓明诗之行于近时，气运使之也。请详论之。夫诗，汉土声音也。我邦人不学诗则矣已，苟学之也，不能不承顺汉土也。而诗体每随气运变迁，所谓三百篇，汉魏，六朝，唐宋元明。自今观之，轶然相别。而当时作者，则不知其然。而然者，气运使之者，非耶。我邦与汉土相距万里，划以大海，是以气运每衰于彼。而后盛于此者，亦势所不免。其后于彼，大抵二百年。 

以上这段论述中，江村北海回答了关乎汉诗史观的几个重要问题：
一、什么是诗？
“夫诗，汉土声音也。”北海认为，所谓诗，其源头在中国，是一种注重音韵的文体。可以看到，北海在论及诗的本质时，并没有明确汉土之诗与我邦之诗因环境不同而产生的区别。
二、诗的发展动力和演进逻辑是什么？
作为抽象概念的诗，自有其演进逻辑。诗三百是诗的源头，而诗在往后的每个阶段都呈现出皆然不同的风貌。在这里，北海提到了一个有关视角的问题。他认为，对于诗体的发展，处在某个阶段当时的作者大多是不知其然的，但如果拓展时距，诗体之间的差异也就一目了然。这种视角上的变化是通过时间的作用自然形成的。这意味着，对诗的演进逻辑的观察，并非由着论诗家的自觉就能够得到的。而从人的“不知其然”的状态中则可以看到，北海将诗的发展视作独立于人的历史的特殊运动——不是人知晓了诗的演进规律，而是诗呈现了阶段式的样态，为人所发现。
而气运是诗发展的动力所在。何为气运？北海对这一概念的运用是受到了胡应麟的启发 。而细读《诗薮》原文，气运首先主导了诗歌体裁的变化，具体表现在“势”和“时”的影响中 ；其次，气运决定了诗史的界分 ；此外，气运影响了诗人对诗才的运用，如刘禹锡和杜牧，“才皆不下盛唐，而其诗迥别” ；最后，气运决定了诗的读者对经典的选择 。可见，在胡应麟这里，气运全面渗透到诗的发展之中。
而江村北海虽然用气运解释了日本汉诗的滞后性，但也对气运自身的原理作了思考。从这思考中可以发现其论述的特殊之处。“我邦与汉土相距万里，划以大海，是以气运每衰于彼。而后盛于此者，亦势所不免。”在这里，江村北海将日本与中国之间客观存在的空间距离视为本国气运衰弱的原因。可见《日本诗史》对诗的发展动力的构建，并不全然以气运作为最基本的因素。在不可见的气运之上，显现的空间距离才是真正被强调的。
而这种显现的空间距离，并不仅仅存在于日本和中国之间，还存在于日本国内的各个地方之间。《日本诗史》有云：
“以余观之，清人篇咏，大抵诸家相似，其继整雅柔颇似于元季明初作家，较诸近时所谓明诗者，无剽窃雷同之病，而其气格则稍淡弱矣。当今京摄才髦所作，往往出于此途……而遐州远境，至今犹尸祝七子者。”
此处，京都和遐州远境之间诗风迥异的原因，亦在于地理方位的距离。所以北海才说：“气运推移，有本末，有迟速。”气运在运动中会受到制约。
三、日本汉诗和中国诗歌的关系如何？
如前所述，日本汉诗和中国诗歌在《日本诗史》中皆称为“诗”。而日中两国之间气运变迁，使得日本汉诗在发展时较中国滞后大约二百年。
《日本诗史》首先构建出一条“飞鸟（文武天皇）-弘仁（平安时期前期）-五山-元禄”的日本汉诗的线索。这种分期与近代日本汉诗研究者的写法不同。它并非是全然按照日本政治史或文化史的标准来进行的。与这条线索对应的中国诗歌史，则是依照“梁武帝天监元年-唐中宗嗣圣十四年（注释：原文是这样写的， 但实际上这一年号在唐中宗时期只存在了两个月）-宋元之际-明中世（弘治、正德、嘉靖年间）-清”的关键节点展开的（46）。
这里值得注意的是，以上的线索不是先有的中国诗歌史作为标准，而是恰好相反：日本汉诗发展的阶段性节点反过来构建了新的中国诗歌史。由此我们不得不重新考虑前文所述“滞后性”意味着什么。如果将“气运每衰于彼”视作一种贬义的价值判断，并将滞后等同于落后，那么这种写法和《日本诗史》中所呈现的“我邦”意识产生了矛盾。为了判明“其后于彼”的真正意思，重要的是看到江村北海所说的“而后盛于此者，亦势所不免。”也就是说，北海认为日本汉诗只是在成熟、兴盛的时机上后发于中国诗歌。发展时间上的先后并不能绝对地决定诗的优劣、高低。
那么，“我邦人不学诗则矣已，苟学之也，不能不承顺汉土也。”又作何解？“承顺汉土”是否与“我邦”意识冲突呢？此处首先和诗的本质有关——既然北海认为所谓诗就是汉土声音，那么这意味着日本汉诗人学诗，或“承顺汉土”，是为了在区别“我邦”与“汉土”的声音——因为语言不同，所以学诗是作诗的必要途径。


 
第二节 《日本汉诗史》
《日本汉诗史》概况
菅谷军次郎（？-1965）的《日本汉诗史》（大东出版社，1941）是日本第一部以“日本汉诗史”为题的专著。作者菅谷军次郎曾在太田中学校（今于茨城县常陆太田市）任教。之后在宫城学院女子大学担任讲师，关注唐宋文学及思想。在日本文部省主办的夏季讲习会上看到了与日本汉诗相关的讲义题目，于是便有了梳理日本汉诗之历史的想法。
本书撰写时所依照的材料，是以太田中学校的文库为基础的。值得注意的是，该校所在的茨城县，在明治维新废藩置县以前曾在水户藩的管辖范围内。关于水户藩，一方面它是当时重要的文教中心之一——弘道馆是幕末日本国内最大的藩校；另一方面，在水户藩形成的水户学，以儒学为中心，结合国学、神道等学问，既推动保留了数量可观的汉籍，又带有鲜明的尊皇思想。菅谷军次郎认为自己在太田中学校的执教，是“传皇学、授圣教”，其思想脉络也很明显了。
此外，在完成后，本书受到了当时知名的汉学家市村瓒次郎(1864-1947)的校阅。市村瓒次郎专攻东洋史学，以中国史的研究闻名。从术业专攻的角度看，他似乎不是校阅本书的最佳人选，但是考虑到其和水户学密切相关的家学渊源（日本汉学史，364），菅谷军次郎的选择也并不让人意外。
本书叙述了奈良时代以前到明治时代，约一千二百四十年的日本汉诗的变迁沿革。本书对于汉诗发展的分期遵循日本历史的朝代分期。相较于江村北海的《日本诗史》着重介绍江户时期的汉诗创作情况，本书较为完整地呈现了日本汉诗的发展。特别是对明治时代日本汉诗的呈现了，弥补了近代日本汉诗史书写的空缺。
每一章的内容基本涉及四部分：和汉诗创作有关的风俗、诗风、音韵学与作诗法、主要作者和作品。


 
《日本汉诗史》的汉诗史观（1）：对“汉诗史”或“文学史”的自觉
《日本汉诗史》首先具有日本汉诗史的书写自觉。它对“日本汉诗史”这一文学史类别作了明确的定义。而这种定义，首先是通过和江村北海的《日本诗史》的比较得出的。
从本书的自序部分来看，作者菅谷军次郎接触过《日本诗史》。对于江村北海的著作，他的意见是：“它只能看作是日本诗话，不能够作为汉诗史构成、书写体裁的样板。（1）”
菅谷军次郎的评价是不无道理的。现代意义上的“文学”（Literature）和人文学科是在幕末，由思想家西周（1829-1897）年自英国引进的（日本文学史，近古，657），因此，在《日本诗史》编撰的年代，日本知识届并没有“文学”或“文学史”的概念，这部著作也不能被归入到作为文学史的汉诗史中。尽管从《日本诗史》的结构中，我们可以看到江村北海对汉诗史中基本问题的解答，但在菅谷军次郎看来，北海并没有书写汉诗史的自觉。
此外，当时日本业已出版了许多日本文学史、中国文学史，可见文学史书写已然形成了基本的范式。从当前可考的目录来看，日本史学者三上参次（1865-1939）的《日本文学史》（金港堂，1890）是第一部影响较大的日本文学史。而至《日本汉诗史》成书之前，至少有50部左右的日本文学史出版，期间亦不乏第一部用英语写作的日本文学史，由英国外交家阿斯顿（W.G.Aston，1841-1911）撰写。至于日本的中国文学史著作，自十九世纪以来也有将近20部问世。
从以上近代日本的文学史出版概况来看，另有一个值得注意的现象，就是最早的一批文学史大多作为高等学校文学科的讲义而印发的。因此，也可以认为，当时撰写文学史的主要目的，是为了配合日本高等教育制度的建设。此外，也有经由博士论文整理出版的学术论著。
菅谷军次郎又是如何对待这些文学史著作的？他举了冈田正之的《近江奈良朝的汉文学》以及《日本汉文学史》两本著作为例，认为学位论文和课堂讲稿都不能算作真正意义上的文学史（3）。恐怕是因为这两种作品在书写时都兼带有文学史书写以外的目的。
可见，菅谷军次郎想要写作的，是“专门的”汉诗史（4）。也正因此，他在本书开篇进行学术史的回顾时，以“至今以来的汉诗史研究和汉学的传来”为题，明确地将汉诗史作为研究和书写的对象。从他的回顾中可以看到，所谓专门的汉诗史，除了需要将诗人、诗作这些基本的材料按时间的顺序组织起来，还需要对与诗相关的背景进行论说。这也是为什么，这部《日本汉诗史》使用大量篇幅记载诗会、诗合等与汉诗创作有关的活动。加上作者在其中对诗风、汉诗评论、音韵学著作等不被过往研究重视的因素的深入研究，使得这些部分的比重超过了对某一阶段诗人及其作品的评介。综上，可以认为，《日本汉诗史》是一部“专门的汉诗史”，同时也是一部以汉诗为中心的文教制度、文艺理念的变迁史。
《日本汉诗史》的汉诗史观（2）：尊皇思想
《日本汉诗史》的汉诗史观，带有明显的尊皇思想。这种汉诗史观较之《日本诗史》的“我邦”色彩更进一步。如前所述，江村北海认为诗的本质是汉土声音，并没有与中国文化和文学传统作彻底分割。但到了菅谷军次郎这里，可以看到他试图在叙事中将中国对于日本汉诗，乃至日本汉学的影响边缘化。
以《日本汉诗史》对汉学传来这一事件的建构为例。作者认为，中国进入到这一事件中，要到日本推古天皇时期，也就是日本官方和向隋唐两朝正式派遣使者开始。在此之前，汉学的输出与受容，全以百济和日本为中心。然而，即使中日两国展开官方往来，中国仍然处于这段叙事的边缘地位。作者详录当时在朝廷中担任要职的百济人士姓名及官职。被称为“汉诗之祖”的大友皇子，也是受到了百济贵族沙宅绍明的指导，以至能写汉诗（6）。同样认为大友皇子始作诗赋，江村北海只言“典重浑朴，为词坛鼻祖二无愧者也大友”（10）。因此，对比《日本诗史》的写法，《日本汉诗史》在建构汉学传来这一事件时，采取的是突出百济的策略。
对于“什么是汉诗”这一问题的回答，《日本汉诗史》通过比较日中两国诗的起源作展开：

“汉诗兴起于皇室，是值得祝贺的。在中国，《擊壤歌》（老人作）、《康衢歌》（小童作），以及《尧戒》的‘战战栗栗，日慎一日’，这些诗篇虽然被认为是中国诗的起源，但根据森槐南博士的考证，应当认为商颂五篇才是中国诗的源头。所谓商颂五篇，指的是《诗经》中的《那》，《烈祖》，《玄鸟》，《长发》，《殷武》。这些都是臣子作的诗。从这点来看，日本和中国的差异是非常明显的。”（8）

在这里，菅谷军次郎区分了“诗”与“汉诗”。“汉诗”并非汉土声音，而专指皇室首先创作的一种韵文。而“诗”，可以指臣子之诗，也能指百姓在劳动时吟唱的歌谣，本来是一个中性的表述。对“汉诗”与“诗”的作者身份的标注，并非就两者的艺术价值作区分，而是意在突出万世一系的皇统。
对皇统的推崇也体现在《日本汉诗史》对汉诗功用的总结中。彼时是所谓皇纪二千六百年，即昭和15年（1940年）。在日本当局宣扬国威的一系列活动中，尤为引人注目的，是在宫崎市建造的八纮一宇塔。“八纮一宇”作为二战时期日本的国家格言，目的是为了动员国民。
在这样的背景下，汉诗的实用功能就被尤为强调。作者认为，幕末尊王攘夷的藩士藤田东湖、吉田松阴等人的诗可以激发国民的慷慨之气、忠诚之心；同时，军人的诗也有助于养成刚健的气质和义勇奉公的决心（451）。尽管他反对将汉诗纯粹作为道德的教材（453），但从他的论述看，他并不反对，甚至乐见汉诗成为动员国家精神的意识形态工具。





《日本汉诗史》每章都会论述该时代的诗风。总的来说，其中所谓“诗风”包含了两个因素：该时代日本汉诗人所学习的范本；日本汉诗的体式。
日本汉诗人的学习对象从六朝、初唐诗，到《文选》、《白氏文集》、《三体诗》，再到苏轼、黄庭坚等人的诗作。《日本汉诗史》并未详明其中变化的逻辑。我们只能从文本中对中日两国人员和书籍往来等线索中，看到一些外在的因素。例如明代的诗风在室町幕府时期就有影响，原因是五山诗僧和明朝的往来增多（167）。又如江户汉诗人学习对象的多样化，是由于这一时期文教发达，引进中国的诗集较为容易（218）。
日本汉诗的体式则呈现出复杂化的趋势：五言诗，包括排律和古诗是日本汉诗人最早熟练运用的体裁，而七言诗最早多局限在一些零散的俪句上，少成篇章；进入奈良朝以后，七言诗和绝句诗增多；平安时代是日本汉诗体式发展的第一个高潮，在这一阶段除了杂言诗、回文诗、乐府等新体式之外，还出现了作为文字游戏的字训诗；第二个高潮则出现在江户时期，其间有诗余（词），更出现了用假名创作的诗——之所以仍认定其为汉诗，是因为它符合原先汉诗的押韵和节拍，只是根据日语和汉语的音节关系，将五言、七言扩充到十字和十四字（224）。
如此，日本汉诗变革到江户时代，最甚者到了只保留韵律的地步。《日本汉诗史》总结日本汉诗史的演进道路时指出：汉诗有污隆，有盛衰，但总体上来说，走的是一条逐渐发达的道路。菅谷军次郎认为这是皇统的恩惠所致（450）。然而正因为其尊皇观念贯穿始终，不能就此停止追问，否则会有将日本汉诗发展的内在动力过分简化的危险。
抱着这样的疑问，我们将重新回顾《日本汉诗史》中的隐含线索。
文本强调了日本汉诗人所共有的精神特点：同化他国的文化物质，并发挥出新的特征。这里的“同化”和在当今的日本汉诗研究中广泛运用的“受容”具有相近的语义，但仍有不同。受容（じゅよう）的基本含义是：从他者处取得某物，并吸收。这里可以看到受容者的主动性，以及受容对象的异质性，两者在学术研究的实践中是同时被强调的。但本书中的“同化”，是强调主体性的同时，试图取消异质性。假名汉诗对汉诗形式中汉字核心地位的消解，就是取消异质性的一种尝试。
与“同化”模型相对的，概括日本文化接触异质文化方式的，还有一种“郊外”模型。日本古典文学专家古桥信孝认为，日本自平城京建立以来，就形成了所谓“郊外文化”。郊外文化的空间特征就是：没有明确的城墙对城内、城外进行区隔，而是通过郊外这一区域来连接二者（日本文学史，334）。这种空间特征决定了日本文化与异质文化的互动方式。首先，没有城墙的情况意味着内部的一方对外部文化采取开放态度，地理边界的消失同时对双方构成可能的向心力。其次，因为权力中心固定且辐射范围有限，作为缓冲区的郊外既是自然形成的，也是无力扩张的。在郊外，两种文化交互的结果是一种混合，而不是如“同化”模型那样带有侵略性质的取代。
由此可以认为，《日本汉诗史》视“同化”这一国民精神为日本汉诗发展的动力。而作为这一精神载体的日本汉诗人，他们的个性是无法泯灭的。正如菅谷军次郎在总结室町幕府的诗人派别时所指出的那样，不论是台阁，还是武士，抑或五山，这些只是概括，并不能遮蔽每个诗人的个人特质（167）。正因如此，体现了日本人特色和日本风格的“和臭”不应成为赏鉴汉诗的障碍，相反，它才是汉诗的趣味所在。



《日本汉诗发展史》（吉林大学出版社，1992年）是第一部由中国学者独立完成的日本汉诗史著作。作者肖瑞峰对日本汉诗的研究集中在王朝时代。总的来说，其关于日本汉诗的论述涉及以下几个方面：一是唐朝诗坛，特别是白居易、刘禹锡等人对王朝时代汉诗的影响；二是对王朝时代日本汉诗创作情况的微观研究，涉及宫廷诗会、总集和诗人；三是对王朝时代日本汉诗宏观发展历程的思考。而这些主题，均在《日本汉诗发展史》一书中作了系统而详尽的论述。
本书原计划书写从奈良时代到江户时代的日本汉诗（1），最后只出版了以王朝时代为中心的第一卷。尽管没有形成诸如《日本汉诗史》那样的通史结构，本书还是在王朝时期的汉诗史展开之前，讨论了有关日本汉诗史的宏观问题，包括日本汉诗的发生、分期和各个时期的特点。

对于王朝时代汉诗的经典建构，本书分为两部分：日本汉诗总集、日本汉诗人。在汉诗总集的部分，以时代为序，作者分别论述《怀风藻》、敕撰三集以及敕撰三集后的汉诗总集各自的编撰背景、体例特色和艺术风格。在对日本汉诗人的评介中，作者以菅原道真为中心，兼及王朝时代的有名汉诗人，介绍他们的创作概况。
虽然本书的叙述以罗列、分类王朝时代汉诗总集为主，但也关注到了历朝汉诗总集在诗集的分类方式、诗作的主要形式和创作群体的变化，具体来说：
首先，诗集的分类方式从以诗人为纲目，到以诗歌内容进行门类的划分。
其次，诗集所收汉诗的主要形式  ，从五言诗到七言诗，加上长篇古体诗，篇幅上显现出明显的增容。而所收汉诗覆盖的题材也逐渐覆盖到社会生活的诸方面。
此外，从诗集的整体风格上看，创作游戏化的倾向愈发明显。
最后，从诗集所录作者来看，日本汉诗人的群体基本涵盖了统治阶级的各个方面。


《日本汉诗发展史》注重从诗歌这一体裁观照汉诗在日本文学中的地位。与汉诗并行发展的和歌成为突出日本汉诗文学史地位的参照系。具体来说，日本汉诗从创作实践和理论两方面影响了和歌的体式和歌论的发展（7-8）。
尽管作者认为，评价日本汉诗文学价值有一个重要前提：即汉诗是非汉语母语者所创作的文学作品，不能简单将中国诗歌作为参照系。但在行文中，中国诗歌的中心地位还是被强调。这和本书的研究对象，即日本王朝时代的日本汉诗有关。在这一日本汉诗史的发轫阶段，中国文学传统，乃至中国律令制度，对于日本国家的形成和文教的发展起到了全方位的影响。

而这种写法的问题在于，它只突出了中国文学、文化传统对日本输入所造成的影响。但另一方面，这种写法并没有解决作者自己提出的问题：为什么在汉语音韵、声律极难掌握的情况下，当时的日本汉诗人还是对汉诗创作抱持着“近乎迷狂”（日本汉诗发展史，98）的热情？也就是说，强调中国文学、文化传统的单方面影响，是无法回答日本汉诗生成的动力问题的。
为了分析这一问题，就必须回到当时汉诗创作的现场，将汉诗的功能和作用从本书对“兴观群怨”这一诗学品格的追求中还原出来。而这一现场中，存在着一组矛盾，即国家仪礼的高度发达与发轫时期日本汉诗的稚拙表现。为什么当时的国家仪礼可以包容汉诗的生成、发展，而不是将其作为有碍宫廷颜面的存在加以遏制？


日本律令制国家成熟的仪礼制度，催生了以程式化语言为核心特征的汉文散文。而其中大部分文本又是直接服务于仪礼。可以说，早期日本汉文既在律令制国家的制度建设中获得了发展的空间，又同时作为文教制度的有机组成，发挥着宣扬宫廷威权的作用。


猪口笃志曾指出，最早在日本汉文学史留下位置的，是以圣德太子为中心生产的律令文本和佛教碑文，其中以佛像背铭为最多（40）。

实际上，程式化语言被广泛使用在早期汉文中。其中又以律令制国家的仪礼文本为甚。《十七条宪法》中，“以和为贵”出自《论语·学而》、“笃敬三宝”、“惩恶劝善”典出《左传·成公十四年》等等，不一而足（十七条宪法原文出自日本通史，53）。这些源自儒佛经典的程式化语言的排列、重组，构筑起新的文本秩序。而在文本秩序的井然，乃至其中展现的风雅意味，则从属于一套似旧实新的仪礼话语——它源自中国统一王朝，而以天皇为唯一中心展开。
至于这套秩序的运作效果，陈旸的《乐书》有载隋朝使节出使日本的情况，从中可见其规模：

 “倭国之俗，凡正朔大㑹，必陈仪仗，奏声乐，而五弦琴之器备有焉。隋炀帝常遣裴清使其国，彼乃遣小德阿辈台，从数百人，设仪仗，鸣角歌舞而迎之。亦可谓不失尊王人之道矣。”（174）



那么，汉诗的情况又是怎样的？

同汉文一样，汉诗的创作活动也是新秩序中不可缺少的一部分。除了宫廷诗会，我们还能够从释奠礼的细节中观察到仪礼秩序是如何操作汉诗创作的。若要在释奠礼中写出一首好诗，前提是要熟悉儒家经典。而儒家经典中提供了大量用于作诗的典故。

“释奠礼在大学寮进行。公卿参拜完毕后落座。此时由文章博士给出诗题。出题范围在《孝经》、《礼记》、《毛诗》、《尚书》、《论语》、《周易》、《左传》之内，每年选择一部。”

然而， 作汉诗除了需要同作汉文那样长于用典，还要符合汉语的格律。由于两国语言存在着天然的差异，加之音韵学研究的完成，造成了早期日本汉诗后发于汉文的现象。正如《日本汉诗史》总结的那样：国文学的发展是韵文先于散文，而汉文学则是散文先于韵文（6）。
用韵、平仄，这些对处于汉学传入阶段的日本汉诗人是很困难的：其一，因为古代日语的发音系统在形成过程中受到中古汉语的影响，到平安时代才基本稳定，所以这期间日本尚未形成对音韵的完全认识。其二，传入到日本的中古汉语又分为两支，汉语自身的发展变化也增加了日本人学习格律的难度：百济人输入日本的是当时南方的发音，称吴音；遣唐使听到的发音则以中国北方音为基础，称汉音。
而据《日本汉诗史》，直到镰仓幕府时期，日本僧人虎关才通过对《广韵》和《礼部韵略》的研究完成了《聚分韵略》（145）。所以可以认为，日本的音韵学研究晚熟于日本汉诗的成规模创作，也是制约早期日本汉诗发展的重要因素。


** 1.3.4 日本汉诗史的发展动力
那么，日本汉诗史的发展动力是什么？总的来说，作者虽然按照日本汉诗自身的周期（发轫-嬗变-成熟-衰替），但有关日本汉诗史的发展动力，作者并没有超越以往日本汉诗史、日本汉文学史有关创作主体身份变化的线索。以下试分论之：
对于王朝时代日本汉诗的发展动力，作者认为，日本汉诗人对于中国诗的热情是最主要的因素；而外交场合的赋诗，更被视为关乎民族形象的行动，因此促生了日本汉诗人对诗艺的琢磨（98）。与之相对的，当本国贵族知识分子对日本汉诗的探索意欲下降之后，王朝时代的汉诗创作就开始衰退。
到了五山时期，日本汉诗的创作主体从贵族公卿转变成了禅僧。对于这种转变，作者认为原因有二：第一，禅僧的宗教生活是以汉文佛经为中心的，因此，宗教生活中所形成的汉文素养是禅僧所以成为当时汉诗创作主体的重要基础；第二，禅僧承担了日中民间学问交流的角色，对中国诗风，特别是宋诗在日本的流行起到了关键的推动作用。而五山汉诗发展到后期，也出现了衰颓之势。在作者的书写中，这种趋势背后的根源，依然在于诗人精神和创作风气的堕落。
从作者对王朝时代到五山时期的汉诗史发展的描述中可以看出，各个阶段汉诗创作主体的精神面貌和风尚决定了汉诗的兴盛与否。而有堕落就有纠偏。在作者看来，德川幕府对儒家思想的推崇正是出于对世风的补救。而这种思想文化的转型又推动日本汉诗创作主体由禅僧向儒者转变。
儒者的登场并不意味着整个日本汉诗史的演进动力发生了颠覆性的变化。因为，不论是王朝时代的贵族公卿，还是五山时期的禅僧，抑或江户时代的儒者，他们能创作汉诗的原因在于他们有着相对其他群体更加深厚的汉文素养。也就是说，从贵族到禅僧再到儒者，汉诗创作主体身份的变化，其实际呈现的是以汉文为媒介的知识话语在历史中转移的线索。如此，江户时代后期以町人阶层为代表的日本汉诗创作的大众化倾向也能够得到解释。
然而，这一线索并不能够解释汉诗从经学中逐渐独立的趋势，也无法解释职业诗人的出现。因为单纯按照汉文知识素养的掌握程度来看，汉文知识在儒者群体中越是集中，汉诗和经学的关系就应该越紧密。但江户汉诗史所显露的趋势并不如此。








《近世东亚汉诗流变》（凤凰出版社，2018年）是中国日本汉诗研究中第一部系统研究近世东亚各国汉诗的专著。该书以15世纪到19世纪作为比较研究的时间范围，意在突出东亚各国汉诗在中国诗学总结期影响下，以及各国汉诗创作之繁盛期的民族特色。
本书第二编“日本汉诗的近世流变”，可以视作是一部较为详尽的江户汉诗史。不论是日本汉诗人对本国诗史的总结，还是现代学者对日本汉诗研究的关注度来说，江户时代被普遍认为是日本汉诗史上一个不可忽视的高峰。实际上，不仅仅是日本汉诗，在整个日本文艺史上，江户时代都被认为是“近世的文艺复兴”（猪口，日本汉文学史，231）。所以，本书对近世日本汉诗史的书写，也是对日本汉诗史高峰期发展流变、艺术特色的一次总结。

什么是汉诗？作者认为，汉诗之所以被称为“汉诗”，其核心在于作为其物质载体的汉字、汉语。具体来说，汉字重语义，因此汉诗的表意功能以词和词组为中介；同时，诗体形式的变化并不是重点，因此汉诗体式自唐大致定型后，就少有整体的突破（前言）。  


由于本书是在东亚汉文化圈的背景下，对近世汉诗的创作情况、审美风格、诗学理念等情况作比较研究，因此，对汉诗之定义的考察得以在各国汉文学传统中进行。而在汉诗在东亚不同国家汉文学传统中的位置的基础上，日本汉诗自身的特色也能够凸显出来。
朝鲜汉诗是朝鲜汉文学中数量和艺术价值最突出的文体（3）。而琉球汉诗发展时间较短，但从其发轫到被日本吞并期间，也诞生出不少有名的诗人、诗作（585）。至于越南汉诗，其产生更被认为是越南古代名族文学发端的象征，见证着越南古代文学的历史（760）。如此可以看出，汉诗不仅是东亚汉文学的重要组成部分，更在各国汉文脉中有着不同的位置。
那么，日本汉诗在日本汉文学中又处在什么样的位置？同朝鲜、越南等民族的汉诗发展史相似的是，日本汉诗的发轫也是基于日中两国的往来。而在日本汉诗的发展过程中，中国诗学典籍的输入是不可忽视的因素，其中明清时期书籍的快速流通对近世日本汉诗的发展尤为重要（304）。
而与周边国家不同的是，日本汉诗在日本汉文学传统中的位置却并非占据绝对主导的位置。菅谷军次郎就指出，日本汉文学的发展是散文先于韵文的。而纵观整个日本汉文学史，汉文的发展也是生命力与多样性并存，其数量和质量都并不逊色于汉诗：奈良平安时代的《古事记》、《日本书纪》、《风土记》；五山时期的四六文；一直到江户时期，出现了儒者的论述、《大日本史》的编撰、翻案传奇小说等等。

 1.4.4 日本汉诗史的发展动力
和本章所评述的日本汉诗史著作不同，《近世东亚汉诗流变》一书的视角更为微观。作者考察的是近世日本汉诗史的发展动力。如前所述，近世是日本汉诗史的高峰。因此，近世日本汉诗史既是日本汉诗史整体的一部分，其演进符合日本汉诗史整体的趋势，同时，它又有着独属于这个时代的特色。
从近世日本汉诗史与日本汉诗史整体之关联来看，作者的书写关注到了江户时期日本汉诗创作主体的变化。从江户初期的儒者，到繁荣期以大阪为中心进行创作活动的町人阶层，近世日本汉诗的发展是以创作活动的大众化为线索进行的。可以认为，大众化的汉诗创作从整体上进一步推动了日本汉诗的多样性。相对地，作者也关注到町人文化对于汉诗诗风的负面影响。享乐和拜金的文化氛围对日本汉诗的精神产生了伤害（385）。
以上，是作者以江户时代汉诗人身份的扩大为线索，对近世日本汉诗史的演进动力作出的阐释。而同时，作者从“诗坛领袖-诗社争鸣-诗人活动”三位一体的关系出发，更深入地探讨了江户汉诗各个阶段诗学转向的动力所在。总的来说，作者认为，诗坛领袖对某个诗风的倡导引领了同时段诗坛的风尚；而以诗坛领袖为中心组织的诗社之间产生的诗学争鸣，在推动了日本汉诗学论述走向成熟的同时，争鸣的结果也决定了当时诗风的走向；而汉诗团体中诗人个体在各地的活动，也扩散了某个诗风的影响。
具体来说，从诗坛领袖的影响来说，木下顺庵引领了江户初期的尊唐诗风，其弟子对其师门诗风的倡导进一步推动了当时汉诗的发展与创新。而此后，山本北山提倡性灵论，则是对此前尊唐诗风下，泥古模拟风气的反拨。
到这一阶段，以江湖社为代表的诗社活动，推动了近世日本诗风向性灵诗学的转向。而江湖社诗人的游历也对性灵诗学的推广起到了至关重要的作用（388）。而诗社活动的影响力，除了诗社成员对汉诗创作、诗学理念探讨的热情以外，其根本因素在于诗社开创者对新诗风的推动。因此，可以认为，诗坛领袖、诗社活动和诗人个体的活动对于本书对近世日本汉诗史的动力书写来说，是三位一体、不可分割的因素。
至于作者所言近世日本汉诗的折衷期，广濑淡窗、广濑旭庄、梁川星岩这三位诗人被尤其突出。依作者所言，这三人“对江户后期诗坛的诗风诗论起到了明显的导向作用。加之他们门下弟子众多,在他们的倡导之下,折衷融合的诗作法成为江户后期诗坛的主流。”（430）由此可见，在本书对近世日本汉诗史的书写中，诗坛领袖，抑或典范诗人的树立，是一条不变的主线。



现有日本汉诗史对幕末明初日本汉诗转型的书写
对于明治时代汉诗在日本汉诗中的位置，现有的日本汉诗史著作都一致地认为，这是日本汉诗衰微的时代。从江户到明治，日本汉诗史从高峰到式微，其原因为何？
菅谷军次郎《日本汉诗史》并未详述其中原因，但从他的叙述中，我们依旧可以看到西方文明的冲击对日本汉诗发展的影响。在第八章“明治时代”的开篇只言，在这个“一切都改头换面的光辉灿烂的时代”，传统的和文、汉籍成为了西方文化的配角，不为人所重视，汉诗也因此衰微（日本汉诗史，351）。
和菅谷军次郎的叙述相比，中国的两部日本汉诗史对幕末明初的诗风转型原因的探求更为明确。
《日本汉诗发展史》强调，幕末的尊皇攘夷运动埋下了日本汉诗诗风转型的伏笔。在内忧外患的情况下，出现了一批感时忧国的志士之作（71）。而尊皇攘夷运动发生的一个重要原因，则在于西方国家在东亚地区的殖民扩张与日本发生的摩擦逐渐升级，如文化5年（1808年）英国军舰伪装成荷兰船只进入长崎港、文化8年（1811年）沙俄军舰舰长格罗宁在国后岛被拘捕等事件。日本和西方的冲突，使得汉诗成为日本民族志士抒怀的载体。
《近世东亚汉诗流变》也提到，德川幕府的腐败政治、日本和西方的军事摩擦，日本的国内矛盾最终在美国黑船的强力叩关下爆发（428）。幕末倒幕志士，以及明治初期诗人的汉诗创作，特别是七言绝句中体现的刚健之气和民族忧患意识成为了日本汉诗史发展到明治初年时的新主题。
可以看到，《日本汉诗发展史》和《近世东亚汉诗流变》都注意到幕末明初的风云巨变对日本汉诗诗风转向的影响。尽管在这两部汉诗史的书写中，作者在交代各个分期时代背景的同时，尽可能地突出日本汉诗发展的自律性因素和规律，但这种汉诗史观无法解释日本汉诗从高峰步入衰落的趋势。这意味着，日本汉诗史发展中的自律性动力在幕末明初失去了解释效力，使得日本汉诗史的书写者必须借助以尊皇攘夷运动为中心的
以尊皇攘夷运动为中心的一系列文学以外的事件，才能构建出一种从近世到近代日本汉诗史的合理逻辑。
如此我们可以认为，以尊皇攘夷运动为中心的事件，在现有日本汉诗史的书写中是特殊的。在它们的构建中，这一系列事件既是推动日本汉诗史的外部动因，又是汉诗这一文体自律发展的直接原因。而文教、世风、汉籍输入等因素对日本汉诗史的影响和这一事件相比，它们贯穿于日本汉诗史的始末，其特殊性就不如后者。
 
第二章：日本的诗意识——日本汉诗史书写的起点	
第一节 《怀风藻》前的诗意识	
中国魏晋以前的“诗”的形态和诗学思想	
日本古代歌谣中的“诗”意识	
第二节 什么是“诗”：以日本汉诗人对《诗经》的认识为中心	
《诗经》是诗的审美标准	
《诗经》是诗的最高典范	
《诗经》是诗史、诗体之源	
《诗经》阐释中的重要命题	
第三节 诗的音乐性：差异及克服	
音乐性是诗的本质规定	
诗是华人之音	
第四节 文体自觉意识	
诗的书面特征	
 
第二章：日本的诗意识——日本汉诗史书写的起点
回顾已有的日本汉诗史，其中并没有专讨日本汉诗人诗意识的文本。然而思考日本人的诗意识是重要的，因为这一意识中包含了日本人对诗的核心特征及功能的理解、他们评价诗和诗人的标准、乃至他们对日本之诗与中国之诗关系的反思。日本汉诗史的书写是对日本汉诗进行经典化的过程，而什么样的诗才能进入到这一传统的构建中？日本汉诗人的诗意识是回答这一问题时不可绕过的，因为这种意识中凝结了对日本汉诗的本土认识。
这一章分为四个部分：
第一部分讨论日本现存最早的汉诗集《怀风藻》形成之前，日本的诗意识。这一意识的形成同时受到中国诗学传统，以及本国固有歌谣和宗教生活的影响。
第二部分透视日本汉诗人论诗文本中对以《诗经》为中心的相关命题的使用方式，较为全面地揭示日本汉诗人对“诗”的认识。之所以《诗经》为切入口，是因为《诗经》是对日本汉诗人诗意识影响时间最长、范围最深远的文本。
第三部分指出：日本汉诗人的诗意识中，音乐性作为诗的核心特征是至关重要的。然而在两国的语言差异下，这种认识可能使得以汉字文化圈为载体的汉语诗歌传统产生断裂。面对这种困境，日本汉诗人采取了三种调和的策略：强调对意义而非声音的感受；从和歌与诗的关系入手，强调两者在人情表现和创作技巧上的共同点；将诗律视为天地自然之元音，超越对诗律的人为规定。
第四部分则是在音乐性之外，探究日本汉诗人的文体自觉意识，并以此为基础讨论日本他们对诗才的理解。


第一节 《怀风藻》前的诗意识
日本汉诗史的书写，首要的工作就在于厘清“诗”这一概念在日本的生成和流变。那么，我们可以从哪些材料开始对这一过程进行梳理？从现有的日本汉诗史中可以发现，在日本汉诗发轫阶段，《诗经》和其阐释文本的影响，以及日本现存最古的汉诗总集《怀风藻》是研究者最为关注的。尤其是《怀风藻》，因为其贵重的文献价值，其在日本汉诗史中的地位，被认为如同《诗经》在中国诗歌史中的位置（日本汉诗发展史，141）。围绕《怀风藻》成书背景及艺术特色的分析，学界已经有许多论文。而本段意在说明《怀风藻》成书之前，日本列岛已经有了“诗”的意识。而这种“诗”意识，在不可避免地受到先秦至魏晋中国诗学传统影响的同时，更出现在以记纪歌谣为代表的日本古代歌谣中。

中国魏晋以前的“诗”的形态和诗学思想
日本最早没有自己的文字。因而，日本首次接触“诗”，是通过中国文献的输入进行的。这些文献中，有《诗经》这样直接记载“诗”的，也有《论语》这类包含儒家论诗思想的著作。因此，考察“诗”在日本的发轫，必须从中国诗学传统对“诗”的认识出发。
中国的诗，其形态经历了从口头到文字记录的过程。陆侃如《中国诗史》对中国早期诗的形态进行考辩，认为卜辞对乐舞的记载呈现出中国诗的原始形态（中国诗史，5）。诗舞乐结合便成为中国早期诗的一个核心特征。另外，从陆侃如等人对殷商金文和周代金文协韵与否的比较中，也可以发现，“韵”这一诗歌重要形式特征的出现是经历了一定的过程的。这些用文字记录下来的，协韵且形式较为整一的内容，呈现出中国早期诗的样貌。
而进入到文字时代，中国诗的语言就逐渐与日常口语分离。吉川幸次郎概括中国诗的语言特点时指出：“文学的语言不是作为日常语言的口语,而在原则上被要求为具有一定规格的特殊语言”。而这种“特殊语言”的核心在于韵律。《诗经》中就可以看到押韵的特征。此外，随着诗歌体式的成熟，形式的整一，乃至平仄等等，都成为中国古诗语言特征中的核心构成。
以上是对中国早期诗特征的简单描述。总体来看，中国早期的诗在形态上经历了从口头到书面的转换，在此过程中，口传时代的音乐特征被保留了下来。那么，人们对“诗”的认识又经历了怎样的过程？考虑到日本对《诗经》、《论语》等文本的接受不早于魏晋，因此，这里仅梳理魏晋及之前中国诗学传统对于“诗”的认识。
描述魏晋及以前的时代中国诗学对“诗”的认识，是无法离开《尚书》、《论语》、《礼记》以及《毛诗序》几个文本的。“诗言志，歌永言，声依永，律和声。八音克谐，无相夺伦，神人以和。”（《尚书》）中可以第一次看到诗言志这一重要命题。而《论语》中，“思无邪”、“兴观群怨”等命题，则与《礼记》“温柔敦厚，《诗》教也”、“其为人也：温柔敦厚而不愚，则深于《诗》者也”之“温柔敦厚”一起，成为经学之“诗”的核心理念。至于《毛诗序》，其重要性在于，它将“情”的因素引入了“诗”的本质：“诗者, 志之所之也, 在心为志, 发言为诗。情动于中而形于言, 言之不足故嗟叹之, 嗟叹之不足故咏歌之, 咏歌之不足, 不知手之舞之, 足之蹈之也。”
另外，中国古代目录学著作对“诗”的分类，也应该被关注到。魏晋及以前的目录学著作中，经学之“诗”和文学之“诗”是泾渭分明的。《七略》中，《诗经》归于“六艺略”，而屈原、陆贾等人的赋被单独归于“诗赋略”（王重民：《中国目录学史论丛》，页24-25。）。《汉书·艺文志》除了“诗六家，四百一十六卷”外，还有“歌诗二十八家，三百一十四篇。凡诗赋百六家，千三百一十八篇。”从这里也可以看到，魏晋及以前的中国，并未形成对“诗”的统一分类和明确的文体自觉意识。
总的来说，日本列岛最早受容的中国诗学认识，一方面并未形成有关“诗”的相对独立和统一的认识，反映出诗史发展初期诗意识的混沌；但同时，一些重要的诗学命题已经被提出，并随着文献的输入对日本产生影响。
日本古代歌谣中的“诗”意识
在叙述中国早期诗的形态及相关认识后，我们也要认识到，同中国诗的形态发展过程类似的，日本民族文学中的歌谣也经历了从口头到书面文体的转化。这些上古时期的原始歌谣是中国诗歌传统系统进入日本之前，日本列岛所固有的文艺形式。那么，这些原始歌谣的特点是什么，又和“诗”在日本的发轫有什么关系？
从特点上来说，这些原始歌谣同中国诗的原始形态有着相类之处。它们都和舞蹈、音乐密切关联。而日本原始歌谣的特殊性在于，它的形成和发展是日本原始神道宗教生活的一部分。而原始神道的咒语等，又由“言灵”（ことだま）思想所统摄。这种对语言中灵力的信仰对日本古代民族文学的影响很大，从上古贯穿到江户时期的国学运动（川村湊 『言霊と他界』 講談社学術文庫 2002年，15）。因此可以认为，这种原始神道信仰是日本原始歌谣核心的精神内核。至于《古事记》、《日本书纪》中记载的歌谣，则是日本进入到文字时代以后留下的作品了。而这些作品也继承了原始歌谣的信仰因素（日本诗歌史，14）。
那么，以上所述日本古代歌谣的特点和“诗”在日本的发轫有何关系？从功能上看，记纪歌谣一定程度上继承了中国早期诗、早期韵文的仪礼功能，即构建皇室和国家的权威话语。《古事记》和《日本书纪》最早记载日本古代歌谣，数量也最可观（日本诗歌史，7）。而这两部作品都是用汉文写成的官史，是日本系统接受中国思想和政治制度的产物。其中所记载的天皇的御谣，出现在战争演讲和重要的祭祀场合，成为日本古代历史建构的重要组成。如《日本书纪》卷三记载了崇神天皇八年冬十二月，天皇和大夫祭大神，其间君臣对歌的场景（日本书纪，76）。
综上，早期律令制国家史书中的这些歌谣能够反映当时日本列岛的“诗”意识。而在记纪成书的近一个世纪之后，日本现存最古汉诗集《怀风藻》才编撰完成。现有的日本汉诗史在叙述日本汉诗的发轫时，往往忽视《怀风藻》成书之前的文献中已经存在的“诗”意识。
而除了记纪歌谣，日本在二十世纪九十年代后半叶的考古成果也能够观察到《怀风藻》成书前列岛居民对诗的运用。奈良县飞鸟寺附近的飞鸟池工房遗址就是一例。这处遗址被认为是日本古代最大的工房，在其中出土了写有如下文字的木简：“白马鸣向山 欲其上草食 女人向男咲 相游其下也” 。这段文字的原型被认为是《千字文》“鳴鳳在樹，白駒食場，化被草木，頼及万方”（新川登亀男｢｢天皇｣木簡を考える｣『月刊しにか』一二七､二〇〇〇年）此外，尽管无法看到这段文字的押韵，但其句式规整，已经接近诗的语言。











 
第二节 什么是“诗”：以日本汉诗人对《诗经》的认识为中心
《诗经》及其阐释文本作为首批输入到日本的汉学文献，对日本诗学的形成和发展产生重大的影响。因此，日本汉诗人对《诗经》的认识应当作为梳理日本汉诗史中“诗”意识的中心问题。实际上，围绕日本诗经学，学界已经有许多成果。这些研究对《诗经》在日本的流布和日本学人对《诗经》的接受、阐释史作了细致深入的研究。而本部分并非是对《诗经》研究的研究，因此无意重复这些论述，也不按照时间顺序组织。相对地，这一部分意在考察《诗经》在日本汉诗经典化过程中起到的诗学意义，即通过透视日本汉诗人论诗文本中对《诗经》及相关话语的使用方式，多角度地揭示日本汉诗人对“诗”的认识。
《诗经》是诗的审美标准
日本汉诗人常以《诗经》作为评价诗的标准。而作为一种审美标准的《诗经》，其最受日本汉诗人关注的是这两项：“真”，以及情性与韵律的和谐。
小笠原优轩以《诗经》之“真”反对当时诗坛模拟唐宋的风气：“拟唐仿宋之诗亡之日，即风雅之真诗兴之日也。”（3879）
何谓“真诗”？可以看到，作者凭借《诗经》风雅之“真”反拨唐宋模拟之风的论述，与晚明袁宏道的诗学思想是相类的。回到中国诗学传统，“真诗”这一个诗学命题在明代提出后，主要经历了三次转向。第一是李梦阳所谓“真诗在民间”，凭借对《诗经》中的《风》诗，强调了民间诗歌具有真情，方为真诗。第二是王士贞所谓“盖有真我而后有真诗”（《弇州续稿》巻五十一·《邹黄州鹪鹩集序》），将蕴含了诗人主体性的“真我”作为“真诗”的前提。第三是袁宏道“犹是无闻无识真人所作，故多真声，不效颦于汉魏，不学步于盛唐……大概情至之语，自能感人，是谓真诗，可传也。”（《袁中郎全集》卷十），通过与“真人”、“真声”等命题组合，扩大了“真诗”的内涵。
综上可以认为，小笠原优轩将《诗经》视作“真诗”，其诗学观念是在上述“真诗”脉络之中的。而他的诗学观点，也反映出江户汉诗中后期反复古、扬性灵的诗风。在《优轩诗话》中，他还概括了《诗经》的本质，和诗人所应追求的最高标准：“三百篇以思无邪爲主，诗人之兴趣止于此而已。”（3871）评述屈原、宋玉、陶渊明等人的艺术风格，小笠原将“自然之真趣”视作“思无邪”的核心。而在此之前，祇园南海也表达过类似的观点，认为《诗经》作为中国诗歌发展史的源头，其造化之妙，非后世之诗人所能企及。而这种极高的地位，是因为其“上世之口气，真情流出”（5281）。从这些论述中可以看到从江户汉诗诗学思想中以“真诗”为核心，兼谈“真情”、“真趣”的脉络。
同时，在这一“真诗”的诗学命题中，也能反映出江户时期堀川、萱园两派古学学者《诗经》阐释中关注人情的面相。尽管从日本汉诗诗学传统的发展看，反复古、扬性灵的诗风主要针对萱园派（近世东亚汉诗流变，385），但如果考虑到其《诗经》阐释的特点，就能够发现萱园派诗人菅茶山等人的观念转向具有其内在逻辑。
除了理论的阐发，小笠原优轩本人的创作实践也努力贴近《诗经》的风格。下面例举两首：
《王丹麓河之渚 二章》一诗化用了蒹葭的意象，体现出作者悠游其乐的心态：

河之渚，梅以爲春。我庐于斯，我室于斯。乘舟而纶，游泳无时。河之渚，葭以爲秋。我竹既艺，我鱼既馁，卒岁优游，乐其生遂。（3879）

另有《陟阻，一谷怀古也。二章皆赋，章六句 成美》抒发了怀古的心情，其中融入了对源平之战的感慨，以及重获安定后，与战时气氛的对比所生出的叹息：

“陟彼阻兮,松柏苍苍，平氏之亡，三军于没，北风飙飙，波涛荡兮。铁拐之峻，王宫焕兮，维昔之盛，今其邈兮。月出惨矣，慨其叹矣。”（3883）

可以看到，作为“真诗”的《诗经》，被日本汉诗人用来建立其自然的诗风和对人情的张扬。此外，《诗经》性情与声调和谐的特征，也为日本汉诗人所注意。
森槐南《参订古诗平仄论》云：“殊不知《诗三百篇》发诸情性，谐于律吕，降而爲《离骚》，爲乐府，皆莫不以声调铿锵爲美。”（5063）在他看来，以《诗经》、《离骚》、乐府为脉络的中国诗歌传统有着共同的美学特点，即声调铿锵。而《诗经》所代表的审美标准是特别的，它体现了声调与情性的和谐统一。
何谓“铿锵”？森槐南此书是对王士稹《古诗平仄论》的校订和评注，因此，声调之“铿锵”被用以针对一些日本汉诗人作古诗音节混乱而不自知的现象。而这些汉诗人在森槐南看来，是受到了袁枚的影响，在诗中任性抒发：“概皆借口于袁才子，谓古诗‘到恰好处，自成音节’”。
回到《随园诗话》，则能发现袁枚此番评论是关于赵执信《声调谱》的。而赵执信此书又是受到王士稹古诗声调论述的影响。《四库全书提要》：“执信尝问声调于王士稹，士稹靳不肯言，执信乃发唐人诸集，排比钩稽，竟得其法。”对王士祯，袁枚则评价其七言古诗“如杞国伯姬，不敢挪移半步”。森槐南对袁枚的攻击持反对态度，认为其不过“佛家骂祖手段，语相戾而理实相该”。
森槐南对袁枚的评议便是针对袁枚之于古诗声调的负面态度的。然而，细观《随园诗话》后文的论述，则能发现森槐南对袁枚诗说的误解。具体来说，第一，袁枚认为诗经之风雅颂一直到乐府“各有声调，无谱可填”；第二，若填谱作诗，则“四始、六义之风扫地矣”。《随园诗话·四/54》这两处都说明袁枚并非反对古诗声调。相反，他重视《诗经》以来各种诗体自身的声调特点，更将《诗经》作为自成音节的典范。
通过还原森槐南对袁枚的误读，可以认为，《诗经》在两人诗说中的功能，都是一种诗的审美标准。只是森槐南所谓“铿锵”，除了强调其声调之规整和谐，更突出《诗经》声调与情性的融合的特殊标准。

《诗经》是诗的最高典范
《诗经》被认为是诗的审美标准，这意味着符合《诗经》之“真-情-声”三位一体的诗才能进入日本汉诗人的评价视野。在此基础上，《诗经》转变成了诗的最高典范。这种典范地位决定了日本汉诗经典化的路径。
《侗庵非诗话》的作者古贺侗庵（1788-1847）尤其强调《诗经》于入门者的典范作用。他赞同朱熹“《三百篇》性情之本”的论述，又沿承朱熹“读《诗》正在于吟咏讽诵，观其委曲折旋之意”的读诗方法，认为师法古人之诗，吟咏讽诵，是学诗的不二法门。
那么，在古人之诗中，《诗经》的地位又有何特殊？作者提到：“诗至《三百篇》超化人神,非人力可及，尽矣至矣。自非子贡、子夏之徒,未可与言。”（2160）可见，其典范地位在于其出神入化，尽善尽美。而正因为《诗经》的地位崇高，《诗经》的读者也应该具有一定的学识。古贺侗庵认为，只有孔门四科十哲中的子贡、子夏那样好古敏求的人才能与之谈论《诗经》。
作者将《诗经》和其他诗加以区分，体现了日本汉诗创作大众化的背景下的汉诗经典化意识。《侗庵非诗话》是一部批评本国诗话的著作。诗话的大量出版，以及职业诗人的出现被认为是江户时代日本汉诗人诗学自觉的体现。然而，作者却以之为非。在他看来，要作好诗，“故必作大儒，先大君子,然后可以有真好诗矣。甘自爲一诗人，则其诗必不足观也。”（2070）在儒者、君子、诗人的等级序列中，诗人的地位是最低的。而通过对《诗经》典范地位的树立，作者试图将这些以诗为业，却不在心性上修己问学的诗人及其作品排除在日本汉诗的经典脉络之外。

 
《诗经》是诗史、诗体之源
《诗经》的崇高地位亦影响到日本汉诗人对宏观诗史的认识。《诗经》就被日本汉诗人视作是诗史、诗体之源。而这一认识中，可以看到他们以中国诗歌传统为参照系，对诗的本质进行探讨。

诗与乐
日本汉诗人注意到《诗经》与后世诗歌之间的区别在于能否入乐。而《诗经》入乐又决定了后世诗得以在语言形式上继承《诗经》押韵的特征。可以说，以《诗经》为基础阐述诗乐关系，反映出日本汉诗人对诗的普遍特征，即音乐性的思考。
小野泉藏从风雅正变的角度说明了诗、乐分离的原因：“以《三百篇》言之，风雅之正者皆可被之管弦,而其变者皆徒诗也。但虽其被于管弦者，亦可以徒唱歌，此所谓行而不相悖者也。至于汉,则诗皆徒诗，而乐府则特制焉，其别判然不待明辨。”（《社友诗律论》，1707）这里可以看到，《诗经》中正风正雅即使与音乐分离，也可以歌唱。这种音乐性是后世诗乐分离的基础。
关于《诗经》自身的音乐性，《诗学逢原》从诗的分类着手，认为《诗经》原是六经之一，是圣人所写的音乐，根据古代的音乐进行演唱，用来教化百姓的（日本诗话丛书，2，2）。《唐诗平侧考》也指出，从入乐的《诗经》开始，诗的核心特征就是韵。（日本诗话丛书，2，125）《诗格集成》则引明代薛冈《天爵堂笔余》：“三百篇，诗之祖也”，及胡应麟：“三百篇，荐郊庙，被管弦，诗即乐府，乐府即诗也”（日本诗话丛书，3，381），以说明《诗经》的音乐性影响了日本汉诗人对诗之核心特征的理解。
而从《诗经》考察诗的音乐特征出发，日本汉诗人继而发现《尚书》中的一些韵文也具有诗的特性。《诗辙》就指出，《尚书·虞书》记载的“股肱喜哉！元首起哉！百工熙哉！”可以视作是诗的起源之一（日本诗话丛书，6，58）。这意味着，基于《诗经》，日本汉诗人对诗的音乐性有了更深入的认识，并在此基础上开始关注《诗经》以外的经典中的存在的诗意识。
 
诗与情
在认识以《诗经》为基础的诗的音乐性的同时，日本汉诗人也注意到后世诗人对诗的声律的过分雕琢，会有害于诗的精神内核——性情。但强调性情并不意味着对诗人个性的无限张扬。相对地，凭借《诗经》议论诗之性情的诗人，都注意到诗的性情或受制于与音调节奏的配合，或服从于对性情特质的具体规定。
小野泉藏曾批驳后世论诗者用声律肢解《诗经》章句的行为。他提到：“夫《三百篇》邈矣，秦汉而降，吐露性情而音调节奏自然动人者爲诗，诗而不能动人则不如不作之爲胜也……诗出性情者，自然也。声律者，人作也。”（1693）在他看来，《诗经》对诗的本质的规定不仅出于其音乐性，还在于其本是诗人性情之吐露。性情与诗的音调节奏的和谐使得诗具备感动人心的审美效果。从小野泉藏对《诗经》性情与声调关系的议论中可以看到，诗人以诗为载体对性情的发挥并不是没有限度的。
赤泽一堂《诗律》则认为，《诗经》作为诗体、诗史之源，其价值更在于性情。他发挥了儒家诗学重要命题之一的“诗言志”，对诗人、诗作提出了自己的标准：“诗虽有诸体不同，皆原于周，所以尊矣。……周诗三百，各有六义，曰风雅颂，是其格也。曰赋比兴，是其体也。是故爲诗者，须真才实学，本性反情。诗出于实情不可止之地，哭者善哭，喜者善喜，是爲真诗。”（3582）需要注意的是，这里的“真诗”和前文“真诗”命题中的自然真趣有着本质的不同。如果说前文之“自然”是和复古模拟的诗风相对，强调的是诗人在创作中的主体意识，那么此处“哭者善哭，喜者善喜”中，具体规定了何为“哭”，何为“喜”，只有符合这一先验规定的诗性表达才能算作是“真诗”。“实情不可止之地”也说明，在赤泽一堂的“真诗”命题中，诗人的个性表达实际上是服从于这一规定的。

诗与经 
《诗经》是首批进入日本的儒家经典。而随着日后东亚各国的交往深入，一部分发源于中国的文教制度，如五经博士、学寮等也在日本建立。这些制度促进了日本对于《诗经》的系统研究。而日本对《诗经》的经学研究也由此开始，一直延绵到战后。因此可以认为，在日本汉诗经典化的过程中，日本汉诗人对《诗经》话语的运用始终是与《诗经》的经学阐释相关的。
冢田大峰从诗史发展的视角出发，展开了诗歌发轫阶段“诗”与“经”的名实之辨。他的论点在当时研究《诗经》的儒者中较为难得。在《作诗质的》中提到，“诗”的产生是一系列文体逐渐定型和发展的结果。而《诗经》是这一过程的起源：“风雅之变，爲骚爲赋，乃至称诗。”（1441）在这里，《诗经》同骚体、赋体一同位于诗的序列中。而且，从《诗经》到骚赋，“诗”的概念是逐渐定型和发展的结果。这说明，《诗经》之风雅并不等同于诗，只能算是诗的早期形态之一。在这里，《诗经》作为后世诸种诗体的开端，作者将其诗体价值从经学阐释中独立出来。考虑到冢田大峰是通学朱子学、古学、阳明学的大儒，曾自注十三经，其经学学问在其督学的江户名古屋藩内有“大峰学”之称（三百藩家臣人名事典，新人物往来社，1988），这种对《诗经》诗体价值的强调是值得关注的。
津阪东阳则提出了相反的观点，将六经之一的《诗经》与“诗”对立，将学者与诗人对立，单纯突出其经学地位：“诗之于学者也，特其剩技耳。行有余力，乃以学之。近时学风轻薄,舍本而趋末，以诗爲性命。六经群史一切束之高阁。”（《夜航诗话》，4，1527）津阪东阳是江户中后期的儒者，而当时日本诗坛出现了相当多的职业诗人。这些诗人和江户时代初期、中期的儒者学问与文章兼修不同，他们以诗为业，有的还靠卖诗为生。加上町人阶层的作者加入到汉诗的创作活动中，俗语、俚语入诗已然成为一种风格。儒者东梦亭曾评价说：“少年轻俊之徒，风流自喜，忘吾本分,专心诗章,以要虚誉,四书五经舍而不讲。”（2857）由此可见当时诗风浮躁。在这样的背景下，津阪东阳对《诗经》的认识，可以认为是对以《诗经》为代表的雅正诗风、温柔敦厚之旨的回归。
与津阪东阳观点类似的还有小笠原优轩。同样是针对当时诗风，他批评时人苦学近代诗集，却将《诗经》四诗视作异调。对于这种异象，他号召有志之士“更读三百篇，而洗涤一过,而后诗人之雅致浑浑流出,句法清穆，格调高洁矣。”（3875）《诗经》相对于近时诗歌，或具体来说，强调“平侧之调”的近体诗，是古诗传统的源头。《诗经》的功用也因此在于洗涤诗人被平侧之调、靡靡句法玷污的心髓，使诗人复得雅致。而这种功用与儒家诗教中对《诗经》正人心、端正教的观念是同构的。

《诗经》阐释中的重要命题
上述论述证明，日本汉诗人以《诗经》论诗，反映出一定的经典化意识。将《诗经》作为构建诗歌传统的核心参照，体现出日本汉诗人的诗意识。而同时，除了对《诗经》本身的思考，围绕《诗经》展开的一系列重要的诗学命题，日本汉诗人也进行了阐释。
古贺侗庵在批驳古今诗话时曾感慨，儒家诗学有关《诗经》重要命题，如“诗言志”、“思无邪”、“兴观群怨”、“温柔敦厚”、“不以文害辞，不以辞害志”、“以意逆志”等，“学诗之要尽乎此矣”（2058）。而这些命题中，影响最深的应是“诗言志”。通过以“诗言志”为中心的阐释，日本汉诗人钩连起儒家诗学的其他重要命题，并在此基础上提出了评价诗和诗人的标准。这些标准是日本汉诗经典化的意识所在。


诗言志 
“诗言志”的命题在日本汉诗人看来，是与“思无邪”紧密相关的。“思无邪”规定了诗人言志的方式和诗的价值取向。《锦天山房诗话》对此二者关系的总结尤为精到：“夫诗者，言志也。志有邪正，故言有美恶。”（2947）
虎关师炼在日本第一部诗话《济北诗话》中对“诗言志”和“思无邪”进行了阐释：“夫诗者，志之所之也，性情也，雅正也。……今夫有人端居无事，忽焉思念出焉。其思念有正焉，有邪焉。君子之者，去其邪取其正，岂以其无事忽焉之思念为天，而不分邪正随之哉？……况诗人之者，元有性情之权，雅正之衡。不质于此，只任触感之兴，恐陷僻邪之坑。”（296）在这里，虎关师炼认识到诗人的个体意识在权衡性情雅正的过程中得以发挥。也就是说，诗是诗人对触物感兴进行剪裁的结果。
小笠原优轩指出，正因为诗是志之所至，思有正邪，诗人才要对诗的表达反复斟酌:“耻一言不爲戒，耻一句不自敬。”（3873）。也只有“防邪如雠，守正如城”，才能接近思无邪的境界。
以上论述中可以看到，诗人的创作应该根据儒家诗教思无邪的要求，选择合适的诗性语言进行言志，而后成诗。可以认为，这种观念尽管规定了诗的价值取向，但同时赋予了诗人一定的主体地位。
在此基础上，诗人有责任锻炼诗的语言，谨慎措辞，用善言来传达自己的心志。而这亦在儒家诗学“修辞立其诚”的传统之中。正如《诗法授幼抄》一书指出的：“盖诗，言志也。虽然言不善则志不达，其善言达志，在慎所由矣。”林荪坡《梧窗诗话》则将炼句和措辞的慎重视作是对心之“诚”的诗学实践：“诗者，言之永也。言者，心之声。言不可苟吐，苟吐之爲自欺者也。”“不自欺”是为“诚”。成徳隣、桧长裕亦认为，“诗者,君子之辞也，可不修乎?”
那么，如何锻炼诗的语言，以至于符合对无邪之志的言说？这里牵涉到日本汉诗人对诗人心志与诗的特殊语言形式，如用韵和声律等关系的思考。以下试呈现两种相对的观点。
小野泉藏认为，言志乃诗之本色，诗人咨嗟咏叹,自成音响。这是自《诗经》至汉魏以来的古诗传统。此后，“梁唐以下乃称声律，而诗之道自此拘矣”。在他看来，格律诗的传统是对诗道的约束，遮蔽了诗的本色。那么，何者才能算作是诗的本色？答案正在于诗人的感物言志。
释教存的观点则相反。“且也情动于中而形于言，言成声，声成文，文乃宫商是也。然则有语言则有声律，有声律则有格法，是势之所必至也。升堂入室，不得不由其门也。格法者，升堂入室之门也。”通过化用诗大序中对诗的发生结构的论述，作者构建了一条从格法入门，学成作诗的路径。和其他汉诗人强调诗人应重视学问、性情，认为雕琢声律有害于言志不同，释教存认识到，诗人的内在性情和外在的格调法度是诗发生过程中的不同环节。在这样的逻辑中，诗就是诗人生命、性情的延续，因此不能够将性情和格法割裂开来。
从以上围绕“诗言志”这一命题展开的论述中可以看到，日本汉诗人眼中的“诗言志”，其指向的是诗与诗人生命的结合。而对于诗的读者来说，这种指向的意义有二。
第一，诗可以同时体现普遍人性和诗人的个性气质。冢田大峰就认为：“诗者，所以言志。而后世之作诗虽多工设词,非其实情,然亦足以观其人之曲直刚柔矣”（1444）。在他看来，普遍人性并不会因为诗人工于诗语而被遮蔽。相反，诗对普遍人性的彰显是一种应然。同时他也指出：“以诗观人者，因其风调趣向，以可观其气质也”。这意味着，诗人的个性与普遍人性在诗中是可以并存，不相矛盾的。
第二，读诗的目的是知人之志，因此对读者来说，应用“以意逆志”的态度去阅读。而诗人各有其志，这就为诗的多样阐释开辟了空间。小笠原优轩谈读《诗经》之法，称：“读三百篇之法，必先得诗人之原志，而后见其若比、若兴、若赋。”（3875）有诗三百，即有诗人三百。友野霞舟也认为《诗经》记载了不同阶层和职业的诗人的心志，因此可以作为观察当时社会政教得失的依据。至于后世之诗，他认为：“一代自有一代之诗，指归虽同,气格各异”（3875）。对一人、一时、一代的关注，说明友野霞舟其人对诗的审美已经超越了对单一价值取向的追求。
从诗言志，到以意逆志，再到诗的多样阐释，《侗庵非诗话》中就写到这样一个例子：虽然杜甫的诗作在宋代以来的诗话中占据了重要的地位，但这些议论将杜诗中的草木禽兽，一字一句都用怨讽、刺乱来阐释，最终将杜诗和经史的理解结合在一起。在古贺侗庵看来，这种单一的阐释方式有损诗杜诗的价值：“如老杜诗古来注解且数百家，其能得老杜之心者无一二。往往固滞牵强，涂人耳目，杜诗妙处不可复睹。”（2067）
综上，“诗言志”这一命题尽管从一开始对诗人之志和诗的价值取向作了规定，但日本汉诗人对这一命题的阐释，在承认“思无邪”这一普遍价值的同时，也强调诗人修辞的主动性，以及诗发生过程中诗人生命与诗性表达的统一。市野迷庵有云：“诗者，志也。读其诗，而其人之志可知矣称。”（1679）有诗与志，也有其人、其志、其诗，这两组对立关系可以认为是一个适当精到的总结。
 

孔子删诗说 
孔子删诗说最早出于《史记·孔子世家》：“古者诗三千余篇，及至孔子，去其重，取可施于礼义，上采契后稷，中述殷周之盛，至幽厉之缺，始于衽席，故曰「关雎之乱以为风始，鹿鸣为小雅始，文王为大雅始，清庙为颂始」。”而班固在认同孔子删诗的同时，具体限定了孔子取诗的范围：“孔子纯取周诗，上采殷，下取鲁，凡三百五篇，遭秦而全者，以其讽诵，不独在竹帛故也。”至于《毛诗正义》：“孔子删定在三百一十一篇内，遭战国及秦而亡。”
“孔子删诗说”在日本汉诗人中也被广泛接受。他们的论述中，除了强调孔子删定诗经的理由是为了匡复古道，以诗为教之外，还发掘出删诗这一行为所表现出的孔子的诗才。在这样的论述逻辑中，孔子删诗的政教目的与《史记》中的最早论述无异，同时，作为典范诗人的孔子也完成了其在日本诗学中的形象建构。
根据司马迁对孔子删诗说的描述，这一行为的目的，是为了保留可以“施于礼义”的诗。班固也认为，孔子取周诗，是为了能使统治者“观风俗，知得失，自考正”。因此，孔子删诗说首先突出了诗的政教功能。日本汉诗人对孔子删诗说的发挥，主要是为了针对诗坛的不良风气。
《如云诗话》引菱屋孙兵卫之《淇园诗话》，批评诗人作诗长篇累牍，工于词藻的现象，认为这些雕琢无益于为人。作者凭借孔子删诗一说指出，孔子采诗删诗是为了宣扬“天下所宜志之志，因以立天下所宜道之道者也”（5106）。这才是儒家诗教提倡的温柔敦厚，其并非指向诗的辞藻风格。所以，从诗的内容上看，这些经过孔子删定而保留下来的诗，已经脱离了“田亩红女之谣”的范畴，成为了具有教化功能的“讽歌之辞”。
而江村北海对孔子删诗说的发挥则直接针对时风。他在评《诗学新论》的产生背景时指出，时人空论经学文章，以此博得虚名。在这样的条件下，学问也被认为无用于家国。在他看来，这种风气就如同中国春秋时期“周纲解纽，学教否否，君子道消，肉食不业”，已经到了必须纠正的地步。如果说，面对当时礼崩乐坏的局面，孔子的选择是删定《诗》《书》，为了匡复古道，以惠后学。那么在日本，是否也有这样一个人能够在论诗中恢复古业？在江村北海看来，《诗学新论》的作者原田东岳（1729-1783）可以担此重任。原田先受业于伊藤仁斋的古义学派，后来又师从服部南郭专心于古文辞学派（大分县教育会：《大分伟人传》，东京三省堂书店，明治40年，55-56）。这两个学派都提倡摒弃朱子学、阳明学的注释，直接阅读古代儒家经典。
江村北海用春秋与时事类比，将孔子删诗与原田作《诗学新论》类比，意味着诗的教化功能没有国别之分。以古代儒家经典为中介，圣人在经典中体现的王道和古义是共通于日中两国的。此外，他将原田与孔子相比附，实际上悬置了朱子学、阳明学等阐释学派，直接以日本儒者为中心，试图构建了日本诗论、儒学在儒家经典阐释史中的话语权，反映出了一定的自觉意识。
如前文所述，日本汉诗人对《诗经》的接受是广泛的。而其典范地位，亦有“万代诗法”（《济北诗话》）之称。因此，日本汉诗人在对孔子删诗说的阐释中，完成了对孔子典范诗人的形象的建构。
虎关师炼就将孔子视作诗人：“孔子诗虽不见，我知其为诗人矣。何者？以其删手也。方今诗人不能作诗者，岂能得删诗乎？若又不作诗之者，假有删，其编宁足行世乎？今见《三百篇》为万代诗法，是知仲尼为诗人也，只其诗不传世者，恐秦火耶？”（285）将《诗经》在诗学传统中的典范地位与孔子相关联的还有石川鸿斋。他也认为：“夫《国风》《雅颂》，孔子选其佳者爲三百篇，数变至唐，唐之诗人最多，又选其佳者而爲法尔。”（4835）
从这些论述中可以看到，《诗经》文本的典范地位确立后，孔子作为《诗经》编订者，其诗人身份才被建构。而这一诗人身份的特殊之处，在于其兼有作者与读者之角色。正因为孔子也是一个具备高度审美标准的诗的读者，他才能够通过删诗完成了对后世诗人的立法。




 
第三节 诗的音乐性：差异及克服
从本章第一节可以看到，日本列岛对诗的认识，同时受到中国诗学和本土上古歌谣的影响。而这双重影响都包含着对于诗的音乐性的认识。再加上日本汉诗人对《诗经》的接受中，入乐的《诗经》和后世诗歌的关系也是他们关注的焦点。因此，诗的音乐特征是日本汉诗人始终关注的一个重要问题。而这一问题又牵涉到对两国语言差异所带来的诗的价值判断的认识——如果诗律是诗的本质规定，那么无法完全规范地使用诗律的日本汉诗，是否在价值上天然地劣于中国诗歌？对这一问题，也引出了日本汉诗人克服两者差异的策略。
音乐性是诗的本质规定 
那么，诗的音乐特征包含哪些因素？诗的用韵、平仄，乃至形式的规整。而对这些因素的认识，是日本汉诗人对诗的本质规定之理解的重要组成。
赤泽一堂在其《诗律》一书中，就将诗律之于诗，类比为法律之于国家，认为音韵和谐是诗的本质：“如官府所颁甲条乙令，一一忆记，能断妄念，能诫恶事，便是笃行君子也。佳矣哉诗之有律。”（3581）在他看来，一国之法能够规范人的行为，使人行动谨慎，不至犯恶，因此，诗律之于诗，也是必需且有价值的：“诗主音韵。音韵不协，终不可爲诗也。”（3585）冢田大峰也认为，诗所以为诗，本质正在于声调协调：“诗者主讽咏。讽咏之调，古之诗者在五音宫商之协焉，近体之诗则在四声之协焉。……斯诗之所以爲诗亦可以知也。专尚其声调尔。”（1443）
然而，日本汉诗人尽管能通过训读或借由通译翻译的方式理解古代汉语，但古代汉语终究是异国的语言，他们在汉诗创作中也认识到了两种语言的差异。
赤泽一堂就曾描述过一个现象：被本国诗人视作大家的诗人，其作品在中国诗人看来价值全无：“长崎港汉人读本邦所称名家大家之诗，皆必废不取焉。无他，其人不知音韵故也。”（3585）在日本汉诗史中，江户时期日本汉诗人的创作已经相当纯熟，并且产生了一批在本国乃至东亚都具有影响力的诗人。然而，在这些诗人中，也有不知音韵的诗人。在此之后，赤泽一堂感慨，尽管古今诗人也常犯蜂腰，鹤膝等声病，但“汉人自有调音之法，可免其带齿粘喉之病也。本邦之人不可如此。”
冢田大峰也看到本国诗人在汉字四声、用韵上的问题：“而我方作诗者,徒分字之平仄耳,而不得辨四声。故虽巧作句，或声调不协，将有不可以讽咏者。”（1442）日本读汉字的读法分为音读和训读，但两者的结果都是不带有声调的，这就去除了汉诗用韵中最关键的因素。
日本汉诗人对本邦诗人不知四声的特点有所认识。然而，倘若将音韵和谐视作诗的本质规定，那么日本汉诗人的诗是否不能算作诗？在日本汉诗人承认诗是两国通用之传统的前提下，这种假设是对日本汉诗价值的挑战。对此，以上汉诗人分别提出了补救的方法。
冢田大峰认为，本国作诗者应当着重注意入声字：“作者虽不能悉辨四声，尤于入声字不可以不用心也。”相对于其他三声，入声韵的特点在于短促，而非调值的区分。因此，用对入声的强调进行弥补，是有一定依据的。
赤泽一堂则细辨四声的特点，以使诗的音韵有参差变换之妙。他提出了两点：第一，由于上声和平声相近，因而在作诗时要将两者相隔。第二，去声和入声则是“哑音”，相连会有期期艾艾之感，因此也需要避免连用。
这种对于本国诗人作诗特点的认识，也使得诗韵、诗律类著作在日本诗话中的占到了很高的比例。实际上，从空海《文镜密府论》第一次系统将中国诗学论述引入日本开始，如何根据诗韵、声律进行规范的创作就成为日本汉诗人的必修。
诗是华人之音
以汉字文化圈为中心，以《诗经》为源头构建的汉语诗歌的传统，本是有着自体的延续性的。通过汉字，诗歌形式乃至意象、典故在中日两国的诗中实现了共有。野口苏庵的《诗规》曾提到，当时的日本汉诗人无法对古人诗格作出有效的解释：“于是返而思之，与质之今人，不如索之古人。”从《诗规》一书所引的材料（严羽（《沧浪诗话》）、魏庆之（《诗人玉屑》）、王世贞（《艺苑卮言》））看，作者所谓“古人” ，指的是中国古代诗人。可见，在他看来，日本汉诗与中国诗歌为代表的汉语诗歌传统是一脉的。
然而正如上文所言，两国之间的语言差异是天然存在的。而对这种差异的认识使得上述延续的汉语诗歌传统产生了断裂的可能。在这样的情况下，对“诗”这一概念的国别性，在日本汉诗人对“诗”的认识和定义中得到了强调。他们承认本国汉诗传统与中国诗歌传统之间的界分，同时也认识到了中国诗歌传统对本国汉诗人创作的制约。《日本诗史》对此的总结最为精到：“夫诗，汉土声音也。我邦人不学诗则矣已，苟学之也，不能不承顺汉土也。”（46）。

差异及克服：对汉字表意特征的强调
而在一些日本汉诗人看来，尽管日本汉诗的创作确实受到中国诗歌传统的影响，但语言，特别是语音的差异并不妨碍日本人对诗意的理解。
小野招月认为，日本汉诗人在创作时：“况在此方用彼之言语以叙我之性情，摸其声调于髡须影响之间，不得不依准其一定之矩镬。”（1697）在这里，语言和性情的对立成为了日本汉诗生成过程中的特殊矛盾。在这样的情况下，日本汉诗人在创作时就必须依照汉语的声律规范。但在另一方面，他也从读诗的个人经验出发，指出日中两国诗人对于诗的节奏、意义的感受并无大异：“试取明清人评古诗者览之,曰某篇有调者，我亦觉其有调,日某字不响者，我亦觉其不响。非意有异同，所争音节而已。是故诗之惊心动魄总在吟诵之际，不必待细绎其义，而涕已坠之。定知声音之道，和汉无大异也。”（1710）
三绳桂林亦指出：“夫诗，华人之语也。修其辞者，学华人所爲也。若必欲爲和语，则自有国风三十一言在焉，何以诗爲？”（1409）在这里，华人之语被视为诗的本质属性。此处的“国风三十一言”并不是指《诗经》的国风，而是指以《万叶集》中五句三十一音的歌为代表的和歌。他反对当下诗人将本民族的语言写入诗中，正是要保持两种语言文学的泾渭分明。具体到汉诗创作中，则是要求汉诗人的修辞遵从中国诗歌传统。同时，他也注意到，两国语言的差异最主要还是语言层面上，至于意义则是相通的，所谓“辞无彼我，而有彼我者，音也。”（1413）在此基础上，他认为诗的价值不以两国语言语音之差别为标准，而是在于对意义的表达方式是否精工，诗格的彰显是否高昂。这意味着，通过一定的学习和训练，日本汉诗人也可以达到和中国诗人的高度。
这些论述若通过对汉字本身特点的分析也是可以成立的。汉字是形音义三者的结合。而日本汉诗人之所以能读中国诗人的作品，以至于能写汉诗，主要还是因为，相对于语音的历史变化，汉字的形状和字义是相对固定的。汉字的这一特征也使得汉字文化圈下的古代汉语诗歌传统能够在东亚地区生根、发展出各自的民族特色。
差异及克服：以诗与日本民族文学关系为中心
重新定义日本汉诗在整个东亚汉字圈为中心的汉语诗歌传统的位置，以及日本汉诗与中国诗歌传统的关系，也会引发日本汉诗人对“诗”与“歌”两种文体关系的反思。然而与三绳桂林强调诗、歌相异不同，也有汉诗人从歌、诗关系出发，试图克服日本汉诗与中国诗歌传统之间可能出现的断裂。具体来说，他们的策略主要从两者对普遍人情的表现和创作技巧两方面入手。
《诗辙》指出，诗是将人情语言中不能够说尽的事情，在咨嗟咏叹之余中所发出的。不管哪个国家，都应该有诗。本国的歌，其中的字原来是被翻译过来的缘故，因此其字都是训读。和歌就是和诗（日本诗话丛书，7，206）。
而俳谐是和歌的变体，所谓“古国风之一体”。金田梅邨提到，俳谐与诗尽管从文体发展的角度来看不属于同一个类别，但都是俳人、诗人诉说心曲，描摹所见之物的载体，因此，两者在创作上是相通的。赤泽一堂也表达过类似的观点：“二条家和歌者流之言曰：临题起思，应须仰看云之往来。作诗亦有此理。”（3582）
这些论述强调诗、歌乃至俳谐共有的言志功能。而到具体的创作中，兼康百济就认为，从以花为贵的立场出发，日中两国的人情是相通的：“本邦谓樱爲花，称花王。鹤林玉露云：洛阳人谓牡丹爲花，成都人谓海棠爲花，尊贵之也。可谓东西同一人情矣。”（《浪华诗话》，2648）
东梦亭在其《锄雨亭诗话》中提到：“诗人轻和歌，歌人亦仇视之（2915）。彼此俱非。至其妙悟，诗歌一致。”妙悟是诗人与歌人写出优秀作品的前提。同时，他引用了藤原爲家和藤原俊成对和歌创作之技法的论述，认为诗人和歌人在创作过程中，都会十分注意前后句子的衔接；另外，和歌的妙处不在于对细节的雕刻，而在于对整体的呈现，这种艺术观念也是诗人与歌人所共有的。
天地自然之元音：对人工声律的超越
市河宽斋曾言：“近体至唐而大定”（1473）《诗律》一书也指出：“近体之诗，虽有诸家不一，皆出于唐，所以不及矣。”（3582）这说明，日本汉诗人认识到诗的声调、格律在唐代已经大致定型。小野泉藏也认为后世诗人所依照的诗律，大多是指唐代的诗律。而他同时指出，诗的声律发展到唐代，成为后世诗人创作所必须依据之法，其原因并非是诗人们对声律的雕琢，而是出于天制：“天工人作，始非有二也。人岂以天地间所无者别制出一机轴者哉?故以声律爲唐之制作则不可也，天之制也。”（1703）他认为，人是天地万物的一种，因此人在诗歌格律上的制作是天地规律的体现。
而实际上，这种将诗的形式特点视作天地自然运作之结果的观点并不只是小野一家之言。而通过诗律与天地自然规律的统合，诗其本体也称为天地运作之结果，与诗人对诗律的精工没有关系。卢松江在其《唐诗平侧考》中提到，能够留存到后世的诗律法度，是因为这些诗律规范符合天地自然：“诗者,天地自然之音也,岂无自然和谐之律耶？若夫心之所之，与律抵牾，则诗非其诗，尚何自然和谐之有?”（5290）在这样的观念下，诗律的正体和拗变被统合在了自然之律下。只要是符合天地自然之音的，不论正拗，都是和谐适宜的。
日尾省斋在《诗格勘误》中引袁枚《随园诗话》：“夫诗爲天地元音，有定而无定，到恰好处自成音节，此中微妙，口不能言。试观《国风》《雅颂》《离骚》乐府，各有声调，无谱可填。”（3644）从中国诗歌传统来看，不同的诗体之所以有其特点，并非是因为人工制谱而形成的。诗是天地运作规律的体现。
那么，将诗作为天地元音，诗人又在诗的发生过程中承担了什么样的功能？《社友诗律论》云，学诗者，其首要在于能够辨别天地自然的音律，只有善于聆听，才能在创作中加以相应和协调：“故学者未知音律也，求善聆也。夫瓦釜金玉,谁不辨之?至其钟鼓铿钹，宫商相证，则调不调，必有善辨者矣。”（1705）如同一般的陶器和金属，它们之间的材料、音响的区别是容易辨认的。但是各个乐器之间倘若配合演奏出和谐的乐章，那么乐者首先要能辨别每个乐器的特质，而后再根据音律协调的规律作出调整。可以认为，以天地元音为诗之本质的诗的意识中，诗人感于物而发于声。冢田大峰所对诗人与诗的关系就曾有过这样的论述：“盖作诗者，素何由也?春秋风月之望，花鸟物候之看，水烟波之观，人世哀乐之会，触乎其物,应乎其事感于心胸，发于唇舌，乃假文词以伸其志情，斯所谓诗者也。”（1448）
可以看到，将诗视作天地自然之元音，超越了格律的人工生成之说，继而超越了日中两国语言差距对日本汉诗人规范使用格律的制约。



 
 第四节 文体自觉意识
诗的书面特征
从以上论述中可以看到，日本汉诗人将音乐性视作诗的核心特征。然而，在追求规范用韵、声律的过程中，一部分日本汉诗人意识到，两国语言存在着差异。这意味着，对他们来说，若作为“汉土声音”的诗及其声律，不仅可能无法完全掌握，甚至有害于本国诗人诗作的价值。这里以“汉土声音”为代表的语言差异观，实际上指涉的是语言的语音层面。而相对于其语音的历史变化而言，汉字的字义是相对固定的。因为汉字的这一特点，两国语言语音层面上的差异对汉诗人对文本的理解和创作并不构成无法克服的困难。
如果说诗的音乐性是从文学的口传时代在书面文字中的一种留存，那么，在音乐性之外，作为一种书面文体的诗有着怎样的特点？对这些问题的回应可以对日本汉诗人的诗意识作进一步的探寻。
菊池五山对诗的书面特征作了精到的总结：“诗人则识文字，故把口头之话化作笔端之话，把一场之话化作千万场之话，把对面数人化作不对面千万人，唯恐闻之喜之快之笑之记之忘之者之不多，是诗人之心而诗人之神通力也。”（1733）他认识到，诗是口头语言转化到书面语言的产物。而由于其书面的特质，诗的传播范围更广，成为诗人与读者进行对话的中介。
市野迷庵则是从诗人创作和读者接受的角度，看到了诗的语言和日常语言的区别：“是以言之所不能述，诗能出之；人之所不能睹，评能发之。”（1680）在他严重，诗歌一方面拓展、补充了日常语言，特别是口头语言在表意方面的缺憾；另一方面诗的价值的完善，也必须有评价者揭示他人所不能察见。如此，作为一种书面文体的诗，其语言在表意上就具有模糊性、朦胧美。
和其他文体的关系：以雅俗为中心
那么，诗与其他书面文体相比，又呈现出怎样的特点？长野丰山总结过：“有经语，有史语，有小说家之语，有语录随笔之语。论，记，序，书，尺牍之类，文体已异，语气自别断断不可混用也。有套语，有歇后之语，用之诗、尺牍、小文辞犹可也。至作大议论、大文章，则必不可用也。”（2680）在这里，作者具有相当的文体自觉意识。而从他对诗语的论述中也可以看到，诗与尺牍等文体的共同特点是短小精炼。另外，从语用色彩来说，作者认为诗与文的差异在于，诗可以加入习惯用语以表达轻松、诙谐，但其不可以用以进行严肃话题的议论。这种区分将“诗”分离出“经”的范畴，更强调诗的生活和娱乐性。
同样是从创作角度出发，山本北山的视角则更为微观。他观察到了诗与文在虚字使用上的不同。所谓“虚字”，即在诗中起到承接词句功能的字。如杜甫“久客惜人情，如何拒邻叟”中的“如何”；杜牧“千里暮云重叠翠,一溪寒水浅深清”中的“重叠”。作者认为，写诗和作文所用虚字不同，不可错用：“童蒙之游词场者，用虚字最难。而文自有文之虚字，诗自有诗之虚字，若失之用，文不文，诗不诗也。”（5542）
像“经”、“史”、“小说”等文体，均是从中国舶来的。而关于诗与日本民族文学之源的“歌”在用语上的区别，日本汉诗人也有相关的论述。总的来说，他们认为诗与歌最大的区别在于语言的雅俗。《诗学逢原》一书提到这样的观点：“有人认为，诗是风雅的容器，而不是俗用的物品。如果里面充斥了大量的常语、俚语，那么诗就不是诗，而是和日本的歌差不多的存在。特别是白居易的诗，有人就用这一点批评其诗不风雅。”（日本诗话丛书，2，27）在这里，语言的雅俗不仅区分了诗与歌，语言之“雅”还成为了汉诗经典化的重要依据。
对诗的语言之雅的追求无法否认儒家诗学的影响。本居宣长在其歌论著作《石上私漱言》中将歌与诗的意趣进行了比较，认为诗“以其国风习左右,故悉闻如说教而不生怀想”（东方文论选，774）。在本居宣长看来，儒家诗学对诗温柔敦厚之旨的要求，对诗的语言形式产生了影响：出于对正统价值的追求，诗人往往使用雅语。而本居宣长对诗的评价也因此不如本国之和歌。他认为，诗的雅语是诗人对语言加以粉饰的产物，遮蔽了对人之真情的表达；而和歌的语言相较而言更加生动活泼，也更能表现自然的情趣。
然而，从诗发展的客观规律来看，语言的雅俗并不构成诗的经典化的唯一依据。上文《诗学逢原》中提到的以“雅”作为批评白居易诗的观念，并不能否认白诗在平安朝时代的流行。而本居宣长的论述则是通过对诗中雅语和教化之价值观的贬斥，突出和歌在本国文艺中的优先地位，其论述是为其国学思想服务的。而其他汉诗人也对诗语的多样性有所认识。广濑淡窗有言：“诗无唐宋明清之时代的区分，只有巧拙雅俗之分。”（日本诗话丛书，4，246）对古代诗的学习，要注意到诗的文本自身的话语特殊性，去品味诗人在字句上的推敲。至于诗语的雅俗与否，并非评价诗的价值的唯一依据。而服部南郭在其《南郭先生灯下书》中的论述，不仅从不同的文体中发现语言的雅俗，还注意从四书五经的注释中去思考相关的问题。他发现朱熹对经典的注释中有时也会使用俗语（日本诗话丛书，1，54）。而朱子学在当时的日本被奉为唯一的正统思想。这证明语言之俗，有时并不能决定文本的思想纯正与否。因此，诗句中也应当可以用俗语。
诗有别才
综上，作为一种书面文体的诗，在形式和语言表达上有其特殊性。这就是所谓诗家语。而对诗家语的认识，可以看到日本汉诗人对诗这一文体的自觉意识。于是，诗才也被认为是一种特殊的才华。
广濑淡窗的弟子评价其师时认为，鉴赏诗的能力是创作好诗的前提：“世知淡窗师妙于诗，而不知其最深于知诗。唯其深于知诗,是以妙于诗。”（5378）“知诗”，即知道如何评价诗，知诗者往往拥有高深的学识和鉴赏能力。而“妙于诗”，当指善于诗的创作。广濑淡窗的汉诗成就很高，而这一成就离不开他对诗的深入理解和认知。他的学生说他：“故自三百篇及唐宋之作，沉潜涵泳,心会意融，于古人性情与古诗神味，莫不契合”。也就是说，这种理解和认知，又是长期浸晕在以诗经、唐宋诗为代表的诗歌传统中。在此过程中，人既吟味了古诗，又契合了古人的性情。因此，可以说古人性情和古诗神味是“知诗”的两个方面。以上这些都是妙于诗所必不可少的。
但在另一部分汉诗人眼中，一位诗人作诗的才能和论诗的才能是不同的。山田翠雨在《翠雨轩诗话》中就总结过：“凡作诗者无话,话诗者无诗,能诗能话兼之者鲜矣。”（5388）《锦天山房诗话》评价太宰春台时亦提到：“春台操行学术，卓绝时辈。其诗文似亦解作者之旨者矣。及其自运则椎鲁粗笨，殊乏兴象，宜乎诗有别才也。”（3059）在这里，友野霞舟说时人春台对诗的理解相当精到，以至于如同了解了原作者的心思一样，但是春台自己写诗却一般。友野霞舟将论诗的眼光和作诗的能力加以区分，是所谓“诗有别才”。













