* 绪论
** 选题意义
本文所论“汉诗史”之汉诗，指的是东亚各国诗人直接用汉语创作并遵从中国古典诗歌格律用韵的一种诗作形式。而在东亚各国的汉诗创作之中，日本汉诗有着1500年的历程，在风格上自成一体。其汉诗文献数量，仅据日籍《汉诗文图书目录》,从汉诗发韧的奈良时代至汉诗衰替的明治时代,先后问世的汉诗总集与别集达769种、2339册，保守估计日本汉诗的数量在二十万首以上。

中国对于日本汉诗的集中关注可以追溯到明清时期的诗选，以及《日本一鉴》、《皇明驭倭录》、《日本考》、《日本风土记》等中国人撰写的早期日本研究的专门著作。其中，清代著名文学家和经学家俞樾（1821-1907）编选的《东瀛诗选》是日本文学史上第一部由中国学者完成的日本汉诗选集，具有较高的诗学价值，在日本本土也反响颇大。
此后，中国学界对于日本汉诗的研究大致可以分为两个方向：

其一是关于汉文学视域下的汉诗研究。这一范式强调汉诗的文学性，同时将汉诗作为原发自中国古典诗的“变异体（variants）文学”。因此，这种范式具体从两方面展开：第一，以文学发生学的视角为中心，考察汉诗形成过程中异文化因素的形态、传递途径与媒介；第二，以受容研究为中心，考察汉诗发生中对中国古典诗人、诗作、诗论的本土化接受，或进一步在比较同一主题、形象的中国文学的基础上突出汉诗实践和理论的本土特色。

其二是域外汉籍视域下的汉诗研究，则是用东亚知识共同体的视角观照作为“诗人所在国的本民族文学”的汉诗。这一范式中，跨国别和地区的汉籍作为“中国文化的对话者、比较者和批判者的‘异域之眼’”而存在。另外，它与汉文学视阈下的汉诗研究的关注点不同，汉诗作为重建东亚之古典学的基本材料的一部分，在研究中呈现出东西对话和跨学科的立场。

而近现代日本学界对于本国汉诗的研究，则集中在对于汉诗文献的整理和出版上。富士川英郎等人编撰的《诗集·日本汉诗》20卷、《词华集·日本汉诗》11卷和《纪行日本汉诗》4卷，是日本汉诗研究的重要成果。此外，池田四郎次郎编《日本诗话丛书》十卷也展现出日本学者在诗话文献方面的用功。

然而，回顾日本汉诗研究的各种范式和成果之后，我们发现，对于现有的日本汉诗史著作，学界的梳理和研究是不足的。江村北海的《日本诗史》是日本本土第一部具有诗史性质的诗话著作，其《日本诗选》也是重要的选本。而学界对这些文本的研究以文献学的方法为主，或是考察《日本诗史》对中国诗话的接受。进入近代，日本出版了诸多《日本汉文学史》，然而专以日本汉诗史为书写对象的，只有菅谷军次郎的《日本汉诗史》。中国学界对于日本汉诗史的书写，集中在汉诗发源的奈良、平安时代，以及汉诗本土化意识发达的江户时代，在宏观角度上书写和研究日本汉诗史的专著还没有问世。

此外，对日本汉诗史的文学史方面的理论研究，在迄今的研究中也很相当少见。在现有研究中，在日本文学史、日本汉文学史、日本诗歌史等更多元的文学史传统中去定位和分析汉诗的也很少见，大多是就汉诗而论汉诗。即便在评价日本汉文学史一类的专著时，文献是否齐全也成为了评价该书学术价值的最重要基准之一。如此，文学知识建构、意识形态等核心问题就被回避了。

基于这样的情况，对于汉诗本体及其自身演进逻辑的思考自然难在现有研究中发现。也就是说，对日本汉诗史的理论研究的缺失，反映在现有的汉诗研究中，就呈现出就汉诗论汉诗的倾向。而面对洋洋大观的日本汉诗，日本汉诗史及其相关理论研究思考缺失，或是失声的现状，与上述业已成熟的几种研究范式是不相匹配的。

因此，本文试图梳理和评述现有日本汉诗史的著作，并尝试以文学史的理论思考去深入日本汉诗史书写中的基本问题，比如日本汉诗观念的生成、日本汉诗史的分期及其内在的演进逻辑。而通过对日本汉诗史的重新思考，有助于为日本汉诗研究提供新的可能和切入口。


** 国内外研究综述

*** 国内研究综述

**** 对日本汉诗史的书写

肖瑞峰《日本汉诗发展史》(第一卷)（吉林大学出版社，1992年）是中国学者所著的第一本日本汉诗史。
该书是我国学者第一部关于日本汉诗的著作，它弥补了国内这一学术研究领域的空白。全书将日本汉诗分为王朝时代、五山时代、江户时代与维新以后四部分，并对各时期汉诗创作的大致情况作了概述。
由于本书迄今为止只出版了一卷，因此，只能看到作者对王朝时代日本汉诗发展和审美特点的阐发。在评价该时期的日本汉诗时，作者以唐诗为基本参照系。若以唐诗为基准，固然能够发现早期汉诗的对句不齐、格律不严格一些特点，然而仅以此为根据，日本汉诗就只是中国古典诗歌的旁斜逸支，而失去了其自身在日本文学、文化脉络中的演进逻辑和动力。
而此类以单种文学传统作评价日本汉诗的参照系，也会造成评价标准的单一化，无法呈现日本汉诗独有的艺术价值。举例来说，一直到清末俞樾编辑《东瀛诗选》时，仍指出江户时期大多数日本汉诗人的作品中仍有许多平仄上的错误，他在编辑时还甚至亲自改写错误的部分。但江户时期的汉诗总体在日本汉诗史中获得的评价往往是最高的。这就说明单一的、固定的标准是无法适应日本汉诗自身的发展情况的。

严明的《东亚汉诗史论》（圣环图书，2011年）研究了东亚汉文学视域下的日本、朝鲜、越南汉诗。该书对日本汉诗史书写中的重要问题作了讨论：
第一是日本汉诗的源头和发展脉络。作者以汉诗创作主体的变迁作为主线，阐释了江户时代以前从贵族到僧侣的创作情况。在日本汉诗的整体发展中，作者尤为注意江户时期的汉诗在日本汉诗史中的地位。在这段历史中，明清时期的典籍输入以及在日本流传的速度快，加上本土印刷业的发达，使得日本汉诗人在诗学思想上不断革新。“诗”这一文体也在这段时期达到了审美独立性的高峰。
第二是日本汉诗整体的审美特点。作者认为，日本汉诗最突出的体裁是七言绝句。特别是江户时期到明治、大正时代，日本汉诗在绝句体的体裁下创作了相当数量的与本土历史、风光和精神有关的诗作。
第三是日本汉诗的经典选本情况。以朝鲜和越南的汉诗选集为坐标系，作者分析了日本汉诗在体裁、意象、主题上的本土意识。此外，在日本汉诗的本土意识中，作者特别关注了江户狂诗人大田南畝的《通诗选笑知》、《通诗选》等狂诗集。结合对日本狂诗的传统、发展和特征分析，突出了江户戏作文艺背景下狂诗独特的艺术价值。

严明的《近世东亚汉诗流变》（凤凰出版社，2018年）在体例、内容上都较《东亚汉诗史论》更加完整和丰富。全书一共四编，每一编分述日本、朝鲜、越南、琉球汉诗的流变。在诗史的分期上，选择15-19世纪的近世，对这一阶段的汉诗发展作了集中的梳理。
其中，“日本汉诗的近世流变”一编可以看作书写日本江户时期汉诗史的一次尝试。本编将江户时期的汉诗发展分了三个阶段：初期发展期、繁荣期和总结期。在每个阶段，作者均交代了当时的政治、思想和文化背景。
在论述具体的诗人和汉诗创作时，以诗人群体为单位进行组织，如以著名儒学者为中心，以林凤冈、木下顺庵、伊藤东涯（1670-1763）、荻生徂徕（1666-1728）等人及其门徒为代表；或是以诗社为中心，如幽兰社、混沌社、江户社为代表。值得注意的是，作者还特别  关注到江户时期女性诗人的创作和艺术成就，补充了前述汉诗史的写作。
本编第六至第九章分述江户汉诗的意象、情感和诗体特征。对于狂诗和绝句体的分析，可见于前述《东亚汉诗史论》。对江户汉诗中季节咏叹的重视，则呈现出作者对于江户汉诗本土意识的有益尝试，以及对日本汉诗创作与日本传统的物哀、幽玄等审美意识的相互融合所作的思考。
本编第九章从江户汉诗与明清诗学的关系出发，对日本第一部具有史诗性质的诗话著作《日本诗史》作了个案分析。
总体来说，全书，以及“日本汉诗的近世流变”一编中，较突出的是作者的比较文学意识。传统的汉诗研究局限在文献学和日中文学影响研究中，而作者注意探讨日本汉诗在日本文学、日本文化坐标系中的位置，对原有的研究范式有所突破。

综上，国内学者对日本汉诗史的书写集中在日本汉诗发轫与成熟的两个阶段。对于这两个阶段的梳理和评述，可以看到国内学者较为关注日本汉诗史中的两个问题：一是中国古典文学传统与日本汉诗的关系，二是日本汉诗的本土化色彩。这两个问题都是日本汉诗史研究中较为重要的。然而，由于采用了断代史的视角，虽然进行了相当程度的局部研究，但国内学界对于日本汉诗史的书写尚未能够从整体上观照日本汉诗的演进逻辑和动力因素。

**** 对日本汉诗史的研究
国内学界对于日本汉诗史专著的研究，散见于《论《诗薮》对《日本诗史》的影响》（文艺理论研究，2015年第35期），以及对《日本汉诗发展史》的几篇书评：《肖瑞峰副教授著《日本汉诗发展史》(第一卷)出版》（杭州大学学报（哲学社会科学版），1992年第3期）、《海外汉文学研究的拓荒之著──评《日本汉诗发展史》》（天府新论，1994年第5期）。而对日本汉诗史书写的理论研究，仅有《日本近代“诗史”观论析》（外国文学评论，2015年第1期）。

《论〈诗薮〉对〈日本诗史〉的影响》（文艺理论研究，2015年第35期）一文详实考察了江村北海《日本诗史》在形式、内容和诗歌审美方面对明代胡应麟《诗薮》的继承。作者提出，《日本诗史》的特色之一，就是对中国传统史书体例的运用，呈现出《日本诗史》中对史学传统的自觉运用。此外，“气运”的诗学概念被江村北海用以解释日本汉诗的发展动因。同时，“气运”也被用以论述汉诗的功能、中日两国古典诗传统的关系等日本汉诗史书写中的重要问题。对《日本诗史》体例和“气运”说的分析，突出了《日本诗史》的诗史意识。在诗史意识中，本文作者尤为强调江村北海提出的：日本汉诗发展与中国历代诗歌“二百年”的时间差的意义和对日本诗学界的影响。这是日本汉诗史书写中的一个重要命题，即日本汉诗与中国古典诗歌是两种不同历史时间中的产物。其中原因，固然有汉籍向域外传播和日本诗人阅读、接受汉籍之速度的影响。而更重要的是，两种不同的历史时间所隐含的前提是，日本汉诗自有其本体与演进逻辑。一些日本汉诗研究中的以中国古典诗歌为绝对参照系，单纯视日本汉诗为对中国古典诗歌模仿、接受的结果，实际上也是忽视了上述重要的前提。

《日本近代“诗史”观论析》一文，以近代日本汉文学史对“诗史”这一观念的阐释为对象， 梳理了中日两国文学传统的“诗史”内涵，并深入探讨了近代日本“诗史”中文学与历史、文学与经学的关系，以及“诗史”这一体裁的文体特点。从本文来看，日本古典诗学中的“诗史”共有三种内涵：诗歌发展史、咏史诗，以及评述实事、感慨个人际遇的作品。可以看到，以上“诗史”的内涵中，第二和第三类是较为相关的，即两者都注重以汉诗为媒介，呈现历史并参与历史。而作者特别提到，作为诗歌发展史的“诗史”并非被日本诗史观念所经常指涉。对于日本汉诗人在诗史观念上所作选择之倾向性的缘由，作者并没有给出解释。实际上，在这个没有被解释，或者解决的问题中，可以看到近代日本文学史书写的一个现象：在日本近代诸多有关汉文学史的书写中，《日本汉文学史》的成果是极丰富的，但是《日本汉诗史》的书写，只菅谷军次郎一人而已。

综上，虽然直接以日本汉诗史为研究对象的文章并不多，但国内学界已经注意到日本汉诗史的研究价值。其中，既有站在中日比较文学的立场进行个案研究，也有从宏观上对诗史这一概念作专门分析的。这些文章提示出构建日本汉诗史的几个基本问题：文学史的经典的成立与选择的问题，以及日本汉诗成立的思想背景、素偶体现的诗学观念、文体风格等。

**** 日本汉诗史书写中的相关问题研究

***** 日本汉诗的发生与文体特点

吴雨平的《橘与枳：日本汉诗的文体学研究》（中国社会科学出版社，2008）考察了日本汉诗文体发生和演化的历史。之所以以文体学为透视日本汉诗的角度，是因为作者将文体及文体意识作为艺术自觉的标志。也就是说，本书在勾勒日本汉诗的文体学特征及发展的同时，回答了这样一个问题，即日本汉诗之所以为日本汉诗，区别于中国古典诗歌及其他东亚国家的汉诗的原因是什么。
而对于日本汉诗的文体学研究，除了呈现出日本汉诗的整体风格的形成与变迁之外，同时以日本的民族文学和歌作为参照系，将日本汉诗重新纳入到日本文学史的文脉中。这种进路对于书写日本汉诗史的启发在于，提示研究者去思考汉诗与日本民族文学中其他艺术体裁之间的联系。容易想到，平安时代《和汉朗咏集》作为和歌与汉诗并置编辑的一次尝试，已经呈现出汉诗与和歌的互动。因此，以和歌为参照系，实际上是回归了日本汉诗自身演进的文化土壤。

马歌东的《日本汉诗渊源比较研究》（商务印书馆，2011）所收集的论文，专门考察了日本汉诗对中国古典诗歌传统的受容，并以两国诗的传统为中介，进行了中日文化渊源的比较研究。其中尤为人关注的是作者对于汉诗受容的语言机制——训读法的分析。事实上，对于训读法的研究有助于从发生学的角度理解汉诗的生成。因为日本汉诗是非汉语母语的日本人所写的古代汉语诗歌形式的文学样式，所以引入中日语言学相关的成果，尤其是对训读法的研究，有益于重新发现《怀风藻》——日本现存最古的汉诗集之前汉诗诗体的形成和发展的情况，构建起较为完备的日本汉诗史。



***** 日本诗话和日本汉诗选
日本诗话是日本文学评论史中的重要组成。根据日本学者船津富彦《关于日本的诗话》（《中国文学研究》，1990年第4期），日本的诗话从内容和体例上来可以分为几类：作诗法、对中国诗文的评论和译注、音韵研究，以及直接就诗学理论进行阐述的，议论的范围包括中日两国的诗作和诗风。这些类型的诗话都反映出日本诗人对汉诗创作和研究的自觉意识，因此从这些诗话中可以发现日本汉诗史研究中的有益的本土材料。
专著方面。蔡镇楚的《比较诗话学》（北京图书馆出版社，2006年）以各国诗话为对象，综合诗学和文化学的研究方法，在比较诗学理论方面具有一定的开创性。其中，作者将日本诗话放在中国诗话和朝鲜诗话的参照系中，既对日本诗话的发展史和整体特点做了概论，也呈现出东亚诗话体系的多个面向。
祁晓明的《江户时期的日本诗话》（中国社会科学出版社，2009年）是国内第一部系统研究日本诗话的专著。其中作者从诗歌本质论、诗韵诗律论、诗歌创作论等，多方面详细阐述了日本诗话的诗学思想。此外，作者还关注到了日本诗话作者的日本文学背景。汉诗与和歌、俳句，以及诗学与歌论之间的密切关系，这些都说明，在日本汉诗史的书写和理论研究中，应该重视日本汉诗所处的日本文学传统。
马歌东编选的《日本诗话二十种》（暨南大学出版社，2014年）以《日本诗话丛书》所收日本诗话为底本，精选虎关师炼《济北诗话》、菊池五山《五山堂诗话》等日本诗话中的代表作品。除正文外，每篇亦附有解题，较为精炼地概括每种诗话的内容和思想。
祁晓明的《中日诗学研究》（对外经济贸易大学出版社，2016年）所论述的命题依然集中在日本诗话。和《江户时期的日本诗话》相比，该书更多是以日本诗话作为考述中国古典诗学在域外接受的媒介，具备中日比较诗学的意识。两本著作一起来看的话，则突出了中日古典文学深层次的双向互动。

【

】

而近代以来，中国学界亦出版了许多日本汉诗选集。从这些选集中，可以看到国内学界对于日本汉诗研究的兴趣，也能看到从清末到现代，中国学者对于日本汉诗的关注方面和评价标准变化的轨迹。因此，对于日本汉诗史的书写和思考而言，中国人编日本汉诗选集也是重要的材料和研究对象。

王宝平的《近代以来中国人编日本诗（词）集述略》（天津师范大学学报（社会科学版），2013年第1期）对近代、中华民国时期以及二十世纪八十年代以降的选集情况作了评述。此文认为，清末陈鸿诰在日所编《日本同人诗选》四卷是中国人编日本汉诗集的滥觞。除了个人层面的文化往来，该时期其他的汉诗选集也依赖中日两国外交关系的建立与深入。到了中华民国时期，中国人所编日本汉诗集仅有三部，都反映出编选者欲以日本汉诗救中国士风的心情。二十世纪八十年代以降的中国人编日本汉诗集则呈现出多种面向。除了编选、点校，这一时期中国学者也注重对日本汉诗进行理论批评。这和中国学界对日本汉诗研究逐渐重视的趋势是相合的。


*** 国外研究综述

**** 对日本汉诗史的书写
江村北海（1713-1788）的《日本诗史》是日本第一部具有诗史性质的诗话著作。该书刊行于明和八年（1771年）。根据日本《国书总目录》，该书共五卷三册。唯一的写本藏于日本宫内厅书陵部。而版本则分别藏于国立国会图书馆、内阁文库、静嘉堂文库、庆应大学图书馆。其中，该书的活字本可见于《日本儒林丛书》第三册和《日本诗话丛书》第一册。尽管有这些版本，但是该书在刊行后就没有再版。

《日本诗史》起稿于明和三年（1766年），成稿于明和五年（1768年）。原本计划出版十卷，但因为经费原因，只出版了现存世的五卷。据江户狂歌三大家之一大田南畝（1749-1823）记载，天明八年一月三十日（1788年3月7日）在京都发生的特大火灾中，《日本诗史》的原版被烧毁。

现存的五卷中，卷一阐述了日本诗学变迁的概略，时间从白凤时代（654年-710年）到庆长末年（1614年）的朝廷文学。卷二在时间上与卷一相同，内容分为十二个部分，分别论述武士、医生、隐者、僧侣、闺阁等诗作。卷三记载了元和元年（1615年）之后的文学情况。所记载的作品以京师之地为创作中心，另有日本其他地方的文学。卷四同样记载了元和元年以后的江户文艺，以林凤冈（1645-1732）、木下顺庵（1621-1699）及其门徒为代表的诗作为中心。卷五顺承着第三、第四卷对京师以外地方文学的记载。全书的重点在卷三及以后，也就是元和年之后的文学。

菅谷军次郎（？-1965）的《日本汉诗史》（大东出版社，1941）是日本第一部以“日本汉诗史”为题的专著。作者菅谷军次郎曾在太田中学校（今于茨城县常陆太田市）任教，后在宫城学院女子大学担任讲师，关注唐宋文学及思想。在日本文部省主办的夏季讲习会上看到了与日本汉诗相关的讲义题目，他便有了梳理日本汉诗之历史的想法。

本书叙述了奈良时代以前到明治时代，约一千二百四十年的日本汉诗的变迁沿革。本书对于汉诗发展的分期遵循日本历史的朝代分期。每一章的内容基本涉及四部分：和汉诗创作有关的风俗、诗风、音韵学与作诗法、主要作者和作品。
这本《日本汉诗史》的创作背景以及作者的思想也是值得注意的。在本书自序中，菅谷军次郎特别提到此书成书年份，恰逢日本所谓“皇纪二千六百年”，即昭和十五年（1940年），特以此书献给“八纮一宇之荣耀”的天皇。而“八纮一宇”正是日本在二战中正当化本国侵略行为的全国性口号。此外，作者也提到当时正值“对日本精神进行总动员”的时代，人们对汉诗越发重视，因此可以认为汉诗在作者眼中是有着构建、动员日本精神之作用的。其中，尊皇者藤田东湖、吉田松阴、广濑武夫等人的诗，充满了慷慨和发愤之情，以及对天皇的忠诚，更是被作者认为有着培育日本民族刚健性格、忠君奉国的实用作用。

综上，日本现存的两部日本汉诗史，在成立背景和诗学观念上各自具有鲜明的特色。这两本著作是梳理现有日本汉诗史的书写时所必须要处理的。江村北海的《日本诗史》在日本汉诗史的书写上具有开创性的意义，可以反映出江户时期，也就是现有研究中普遍认为的日本汉诗发展的成熟期中的诗学思想。但菅谷军次郎的《日本汉诗史》，似乎淹没于日本近代出版的诸多日本汉文学史的著作中，少有人发现它的学术价值。然而，如果考虑到日本近代思想的转型和文学潮流在西方文艺思想进入后发生的变化，那么我们也能发现这本日本近代仅有的汉诗史的尊皇观念，以及从中反映出的日本汉诗与国家权力、国家意志之间在历史上的复杂关系。


**** 日本汉诗和诗话选集
日本在近代以来，对本国汉诗的文献整理工作用力颇深，为构建日本汉诗史提供了基本且必要的材料。以下分别从总集和选集的出版作简要概述：
总集：
十九世纪八十年代之前，主要有池田四郎次郎编《日本诗话丛书》十卷（1921年, 日本文会堂书店）, 汇聚了日本诗话的基本资料, 计64种，是目前出版的唯一一部日本诗话总集，但实际上《日本诗话丛书》所收日本诗话为59种,包括狭义诗话38种，广义诗话21种，和文诗话29种,汉文诗话30种。此外，还有长泽规矩也编《和刻本汉诗集成》（全30辑》（汲古书院，1974-1979年）；山岸德平校注《五山文学集·江户汉诗集》（日本古典文学大系89，岩波书店，1966年）；玉村竹二编《五山文学新集》（全六册）（东京大学出版社，1967—1972 年）；上村观光编《五山文学全集》（思文阁，1973年）等。
八十年代后，日本汉诗文献最大规模的整理出版，为富士川英郎等人编纂，汲古书院出版的影印集。富士川等人经过多年的文献考证和版本收集，于1983年至1990年编成《诗集·日本汉诗》20卷和《词华集·日本汉诗》11 卷，每卷卷首附以对所收录的诗人或诗集的解说，以及对原著版本保存情况的介绍。《词华集》收录了平安时代至明治初年的部分汉诗总集作品，其中包括一些此前未曾公开过的诗集，如内阁文库秘藏市川宽斋手写本《日本诗纪》，友野霞舟未刊行的《熙朝诗荟》等。此外，富士川英郎等人还编纂了《纪行日本汉诗》（共四卷）（汲古书院，1991-1993年）。

选集：
八十年代以前主要有结城蓄堂编撰《和汉名诗钞》（文会堂书店，1909 年）； 结城蓄堂编撰《续和汉名诗钞》，（文会堂书店，1909 年）；雅文会编《大正诗文》（雅文会，1915-1927年）；山口准著《日本名诗选精讲》（金铃社，1943年）；猪口笃志《日本汉诗》，（明治书院，1978年）。猪口笃志《日本汉诗》收录作品范围涵盖到战后初期。
八十年代后到二十世纪末主要有神田喜一郎《明治汉诗文集》（筑摩书房，1983年）；小岛宪之《王朝汉诗选》（岩波书店，1987年）；日野龙夫、德田武、揖斐高编纂《江户诗人选集》（共十卷）（岩波书店，1990-1993年）；富士川英郎ほか编《日本汉诗人选集》（既刊13卷）（研文出版，1999-2010）。

**** 多种文学史传统：日本文学史、日本汉文学史
日本文学史方面：
较有代表性的几种日本文学史，分别是市古贞次的《日本文学史概说》（秀英出版, 1959年）、小西甚一的《日本文学史》（讲谈社，1993年）、加藤周一的《日本文学史序说》（筑摩书房，1999年）、古桥信孝《日本文学の流れ》（岩波书店，2010年）。这些日本文学史跨越了较长时间，呈现出不同时代、不同作者的文学史观念和书写方法。
总体来看，日本文学史的分期大多采用古代（或上古）、中世（或中古）、近世（或近代）等历史的描述，其中日本汉诗的起源于中世（或中古）时代，以律令制国家的成立为基本背景。而在此之前的文学样式，如歌谣等，都被认为是日本原始社会集体生活的文艺表现，也被视作日本文学的真正起源。这种将古代与中世分述的文学史书写方式，暗示了汉诗所在的日本汉文脉与和文脉自源头便是两种平行的传统——前者是书面的、表意的文字文学传统的开端，而后者则是语音的、表音性的文学传统的起始。

此外，欧美学界的日本文学史也应被注意到。阿斯顿（W.G.Aston，1841-1911）的《日本文学史》（A History of Japanese Literature，D.Appleton and Company, 1899）是第一部用英语写作的日本文学史，对考述欧美学界对日本文学传统及其中汉诗的描述有很大的参考价值。这本日本文学史以体裁为界，将奈良时代的日本文学分为散文和诗歌两种传统。如此，汉诗便与《万叶集》为代表的和歌处于名为诗歌（poetry）的相同脉络中了。而从整体看，阿斯顿关注到各个文学体裁在整个日本文学史中的消长，以及各个体裁在每个分期中的代表样式。其中，镰仓幕府时代之后的诗歌体裁中，汉诗就很少出现了，逐渐占据该体裁主流的是俳谐、徘文，以及狂歌。特别是该书对江户时期诗歌体裁创作状况的描述，与东亚学者普遍所认为的“江户时期是日本汉诗本土意识和本土色彩较为突出的阶段”的观点相左。
美籍日裔学者白根治夫（Haruo Shirane）等编撰的《剑桥日本文学史》（The Cambridge History of Japanese Literature，Cambridge University Press, 2016)则是对近年来欧美学界日本文学研究成果的集中呈现。和阿斯顿的著作相比，该书不再以西方文学中的体裁概念去统摄全篇的布局，而是以日本历史为分期，在每个分期的叙述中先概述该时期文学的总体样貌，再对文学思潮做总结，最后分述具有代表性的文体类型。而这些文体类型之间的关系是平行的，并没有明确的时间上的先后。
此外，著名日本学家唐纳德·基恩（Donald Lawrence Keene，1922-2019）的著作：《墙内的世界：前现代的日本文学，1600-1867》（World Within Walls: Japanese Literature of the Pre-Modern Era, 1600-1867；Charles E. Tuttle.. 1976) 、《心之种：早期到十六世纪末的日本文学》（Seeds in the Heart: Japanese Literature from Earliest Times to the Late Sixteenth Century；Columbia University Press, 1999）等也呈现出关于日本文学发展的整体风貌。

总体来说，这些欧美的日本文学史著作在叙事模式等方面呈现出与中国和日本学界成果相异的样貌，可以成为日本汉诗史研究过程中的他山之石。

日本汉文学史方面：
日本汉文学史、日本文学史等相关著作，在文学史的分期意识、评价观念和叙述方式上都对日本汉诗史的书写和理论思考有很大的参考价值。此外，在日本汉文学史和日本文学史的叙事传统和文脉中，也能重新发现和定位日本汉诗在更多文学史传统的位置。	
在通史方面有芳贺矢一《日本汉文学史》（富山房，1928年）是日本第一部“日本汉文学史”，此书除总论外，分上古、中古、近古、近世四章，写到江户时期为止。此外还有冈田正之《日本汉文学史》（东京共立社，1929年），1954年又由东京吉川弘文馆出版增订版。该书在“序说”以外，分“朝绅文学时代”、“缁流文学时代”二篇，每篇又分四期，只写到五山时期。
户田浩晓《日本汉文学通史》（武藏野书院，1957年）是第一部由著者本人在生前出版而且又比较完整的日本汉文学史，时间从大和时代一直到大正时期。这之后还出现了神田喜一郎《日本の汉文学》（岩波书店，1959年）；市川本太郎《日本汉文学史概说》（东洋学术研究会，1969年）；山岸德平：《日本汉文学史论考》，（岩波书店，1974年）；猪口笃志《日本汉文学史》（角川书店，1984年）等日本汉文学通史。
	其中猪口笃志的《日本汉文学史》比其他基本著作更能全面的反映日本汉文学史，这本书是时间线最长（从古代一直到昭和年代）、诗人写的最多、汉诗引用最多的一部，也是水平较高的一部。
	该书较为重视对各个时期汉文学发生的背景的阐述，包括外交、汉籍输入、教育制度等。除了汉诗文，本书亦将外交国书、律令及律令注释、和汉辞典、佛经等文本纳入日本汉文学史的观照范围，体现出较为宽泛的文学观念。这些材料集中出现在上古至奈良、平安朝的阶段，较完整地呈现了汉文体的面貌。同时，以这些材料为参照系，也能发现汉诗是怎样发展成一种审美自觉的文体的。
	此外，本书亦涉及到日本文学史、日本诗歌史所很少观照到的明治开始的近代汉文学情况。可以看到，这一时期的汉诗总体上增多了对国势、时事的吟咏感叹，反映出时代的风貌。
	而汉诗的创作者，其教育背景、职业经历、文学素养等，都呈现出多元的样态。譬如明治的诗人森槐南，他既善作诗，还长于填词，又是精于中国戏曲、小说的研究。此外，小说家夏目漱石幼年习汉学，成年后留学英国的经历，除以小说闻名外，汉诗造诣也颇高。从这些汉诗作者的身上，可以反观日本近代文学的丰富样貌。这也说明，应该在书写新的日本汉诗史时，应该将近代日本汉诗放在更多的文学、思想脉络中考察。


*** 总结 
一、对于“日本汉诗史”的研究和梳理不足。国内学界并未专门对现有的日本汉诗史性质的著作作过系统的梳理和研究。日本学界在近代文学史观念输入以后，对于诗（歌）史的构建集中在短歌、俳句和新体诗上，很少见对于汉诗传统的宏观性建构。此外，日本学界虽然编撰了诸多《日本汉文学史》的著作，但是在专门的日本汉诗史的书写上，只有菅谷军次郎一部专著而已。对于该国最早的一部诗史性质的著作及其作者江村北海的研究，日本研究者的目光主要投入在《日本诗选》的文献学研究，以及在近世日本汉学的视域中研究江村北海的生平和教育思想。

二、《日本汉诗史》的史观问题。由于缺乏对菅谷军次郎这部汉诗史的专门研究，因此关于该书作者、体例、内容和成书背景的各自情况和相互关系，是无法在现有的研究中体现的。以上反映出现有研究中对于日本近代以后的汉诗的重视是不足的。实际上，将近代视作日本汉诗史的衰替期是较为普遍的观点。然而，对于近代日本汉诗的衰替与近代日本思潮，特别是文艺思想的关系，现有研究中并没有进行深入的讨论。

三、对于“日本汉诗史”的理论思考不足。虽然中国的汉诗研究，特别是日本汉诗研究的成果已经很丰富，但是对日本汉诗史的书写以及理论思考却关注不够。而日本学界虽然长于汉诗文献的搜集与版本的整理，但对于专门的汉诗史的书写及研究，几乎很少能够看到自觉的意识。

四、中国只有断代史，缺乏从整体角度的对日本汉诗史的梳理。《日本汉诗发展史》（第一卷）的论述重点在王朝时代（奈良时代到平安时代）的汉诗，而《东亚汉诗史论》、《近世东亚汉诗流变》对日本汉诗史的书写则集中在近世。从日本汉诗史的整体视角来看，这两个时代正是日本汉诗起源与达到顶峰，是具有特别研究价值的。然而，断代史视角固然能够对某一个时期的汉诗作较为全面的整理与批评，但是由于缺乏一种全景的视角，无法系统呈现日本汉诗自身的发展动力与演进逻辑。



** 研究思路和方法
本文拟分为四个部分：

第一部分是评述现有的日本汉诗史著作。在这一部分，选取了现有日本汉诗史的经典著作。它们分别是：江村北海的《日本诗史》、菅谷军次郎的《日本汉诗史》、肖瑞峰的《日本汉诗发展史》以及严明的《近世东亚汉诗流变》。本部分在评述以上日本汉诗史著作时，注重对两个基本问题的回答：什么是日本汉诗？日本汉诗发展动力和演进逻辑是什么？对这两个问题的解答，反映出每个作者的日本汉诗史观。具体来说，第二个问题可以通过对每本著作的文本进行细读作具体的阐述；而相对而言，第一个问题，即对“什么是日本汉诗”这个问题的解答，可能并不会显明地出现在文本中，因此需要以每本著作所采用的参照系作为起点观察。

第二部分讨论日本汉诗人的诗意识。首先，讨论中国诗学传统，以及本国固有歌谣和宗教生活对《怀风藻》前诗意识的影响。其次，透视日本汉诗人论诗文本中对以《诗经》为中心的相关命题的使用方式，较为全面地揭示日本汉诗人对“诗”的认识。之所以《诗经》为切入口，是因为《诗经》是对日本汉诗人诗意识影响时间最长、范围最深远的文本。随后，以音乐性为日本汉诗人诗意识的核心，分析两国语言差异下日本汉诗人的调和策略，以此为基础揭示日本汉诗人对诗的本土认识。最后，在探究日本汉诗人的文体自觉意识，并以此为基础讨论日本他们对诗才的理解。

第三部分围绕日本汉诗史的分期问题展开。首先阐述日本汉诗人在论诗时所体现的分期意识。其次梳理现有日本汉诗史的分期方式。最后从多种民族文学史中，在定位日本汉诗位置的基础上，重估现有日本汉诗史的分期。

第四部分以“正变”关系为中心对日本汉诗史的演进动力进行分析。这一关系既是对诗史演进动力的进行考察的成熟视角，又揭示了日本汉诗史发展与中国诗歌传统之影响的关系，突出了日本汉诗史自身的特殊性。这一部分首先以温柔敦厚的诗教和规范创作的诗法格调作为重构正变关系的基点。在此基础上，以雅俗之辨和声律正变观为中心，说明日本汉诗人重构本国汉诗传统发展动力和方向时的多重路径。最后，分析日本汉诗的生成机制，以此为基础找到日本汉诗传统相对于中国诗歌传统变异的原因，以解释其发展动力。
